# Generated by Django 5.0.3 on 2024-03-22 21:10
import os

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


sql_location = os.path.join(
    os.path.abspath(os.path.dirname(__file__)),
    "..",
    "sql",
    "view-vueda_workflow_objectstateproxy.sql",
)

with open(sql_location, mode="r") as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectStateProxy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "vueda_workflow_objectstateproxy",
                "managed": False,
                "default_related_name": "object_states_proxy",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "default_related_name": "states",
            },
        ),
        migrations.CreateModel(
            name="StatePermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grant_or_deny", models.BooleanField()),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.permission")),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vueda_workflow.state")),
            ],
            options={
                "default_related_name": "state_permissions",
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="vueda_workflow.state")),
            ],
            options={
                "default_related_name": "transitions",
            },
        ),
        migrations.CreateModel(
            name="TransitionPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.permission")),
                (
                    "transition",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vueda_workflow.transition"),
                ),
            ],
            options={
                "default_related_name": "transition_permissions",
            },
        ),
        migrations.CreateModel(
            name="TransitionSource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="vueda_workflow.state")),
                (
                    "transition",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="vueda_workflow.transition"),
                ),
            ],
            options={
                "default_related_name": "transition_sources",
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "default_related_name": "workflows",
            },
        ),
        migrations.AddField(
            model_name="transition",
            name="workflow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="vueda_workflow.workflow"),
        ),
        migrations.AddField(
            model_name="state",
            name="workflow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vueda_workflow.workflow"),
        ),
        migrations.CreateModel(
            name="ObjectState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="vueda_workflow.state")),
                (
                    "workflow",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="vueda_workflow.workflow"),
                ),
            ],
            options={
                "default_related_name": "object_states",
            },
        ),
        migrations.CreateModel(
            name="InitialState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vueda_workflow.state")),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_state",
                        to="vueda_workflow.workflow",
                    ),
                ),
            ],
            options={
                "default_related_name": "initial_states",
            },
        ),
        migrations.CreateModel(
            name="HistoricalObjectState",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="vueda_workflow.objectstate",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vueda_workflow.state",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vueda_workflow.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical object state",
                "verbose_name_plural": "historical object states",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WorkflowPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.permission")),
                (
                    "workflow",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vueda_workflow.workflow"),
                ),
            ],
            options={
                "default_related_name": "workflow_permissions",
            },
        ),
        migrations.AddConstraint(
            model_name="statepermission",
            constraint=models.UniqueConstraint(fields=("state", "permission", "group"), name="unique_state_permission"),
        ),
        migrations.AddConstraint(
            model_name="transitionpermission",
            constraint=models.UniqueConstraint(
                fields=("transition", "permission"), name="unique_transition_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionsource",
            constraint=models.UniqueConstraint(fields=("transition", "source"), name="unique_transition_source"),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(fields=("code",), name="unique_workflow_code"),
        ),
        migrations.AddConstraint(
            model_name="transition",
            constraint=models.UniqueConstraint(fields=("workflow", "code"), name="unique_transition_code"),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(fields=("workflow", "code"), name="unique_state_code"),
        ),
        migrations.AddConstraint(
            model_name="objectstate",
            constraint=models.UniqueConstraint(fields=("workflow", "object_id"), name="unique_object_state"),
        ),
        migrations.AddConstraint(
            model_name="initialstate",
            constraint=models.UniqueConstraint(fields=("workflow", "state"), name="unique_workflow_initial_state"),
        ),
        migrations.AddConstraint(
            model_name="workflowpermission",
            constraint=models.UniqueConstraint(fields=("workflow", "permission"), name="unique_workflow_permission"),
        ),
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS vueda_workflow_objectstateproxy;",
        ),
    ]
