# Generated by Django 5.0.2 on 2024-03-15 19:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="transition",
            name="code",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="code",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
