# Generated by Django 5.0.4 on 2024-04-26 17:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transition",
            name="code",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
