# Generated by Django 5.1.7 on 2025-07-10 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_workflow", "0002_statepermission_historical_group_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="initialstate",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "initial_states",
                "ordering": ["workflow__code", "state__code"],
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "states",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="statepermission",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "state_permissions",
                "ordering": [
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "historical_permission_codename",
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="transition",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "transitions",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="transitionpermission",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "transition_permissions",
                "ordering": [
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "historical_permission_codename",
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="transitionsource",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "transition_sources",
                "ordering": ["source__code", "transition__code"],
            },
        ),
        migrations.AlterModelOptions(
            name="workflow",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "workflows",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="workflowpermission",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "workflow_permissions",
                "ordering": [
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "historical_permission_codename",
                ],
            },
        ),
    ]
