# Generated by Django 5.2.4 on 2025-07-17 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_workflow", "0003_alter_initialstate_options_alter_state_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statepermission",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "state_permissions",
                "ordering": ["historical_permission_codename"],
            },
        ),
        migrations.AlterModelOptions(
            name="transitionpermission",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "transition_permissions",
                "ordering": ["historical_permission_codename"],
            },
        ),
        migrations.AlterModelOptions(
            name="workflowpermission",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "workflow_permissions",
                "ordering": ["historical_permission_codename"],
            },
        ),
    ]
