# Generated by Django 5.0.4 on 2024-05-06 19:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_historicalinitialstate_historicalstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstatepermission",
            name="historical_permission_codename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicaltransitionpermission",
            name="historical_permission_codename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalworkflow",
            name="historical_app_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalworkflow",
            name="historical_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalworkflowpermission",
            name="historical_permission_codename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="statepermission",
            name="historical_permission_codename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transitionpermission",
            name="historical_permission_codename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workflow",
            name="historical_app_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workflow",
            name="historical_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workflowpermission",
            name="historical_permission_codename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalstatepermission",
            name="historical_permission_content_type_app_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalstatepermission",
            name="historical_permission_content_type_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicaltransitionpermission",
            name="historical_permission_content_type_app_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicaltransitionpermission",
            name="historical_permission_content_type_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalworkflowpermission",
            name="historical_permission_content_type_app_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalworkflowpermission",
            name="historical_permission_content_type_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="statepermission",
            name="historical_permission_content_type_app_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="statepermission",
            name="historical_permission_content_type_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transitionpermission",
            name="historical_permission_content_type_app_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transitionpermission",
            name="historical_permission_content_type_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workflowpermission",
            name="historical_permission_content_type_app_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workflowpermission",
            name="historical_permission_content_type_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalstatepermission",
            name="historical_group_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="statepermission",
            name="historical_group_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
