# Generated by Django 5.2.8 on 2025-11-20 01:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_workflow", "0004_alter_statepermission_options_and_more"),
        ("vueda_vdq", "0002_workflow_migrations_2025_09_22"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltransitionsource",
            name="fail_with_silent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transitionsource",
            name="fail_with_silent",
            field=models.BooleanField(default=False),
        ),
    ]
