# Generated by Django 5.2.8 on 2025-12-04 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_workflow", "0005_historicaltransitionsource_fail_with_silent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltransitionsource",
            old_name="fail_with_silent",
            new_name="ignored",
        ),
        migrations.RenameField(
            model_name="transitionsource",
            old_name="fail_with_silent",
            new_name="ignored",
        ),
    ]
