# Generated by Django 6.1 on 2026-09-02 19:36

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("vueda_workflow", "0006_rename_fail_with_silent_historicaltransitionsource_ignored_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("historical_app_label", models.CharField(blank=True, max_length=255)),
                ("historical_model", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflow",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_workflowevent" ("code", "content_type_id", "historical_app_label", "historical_model", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."code", NEW."content_type_id", NEW."historical_app_label", NEW."historical_model", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="41f013447e3541b990daaffe0fa01a8acb523406",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_a73e8",
                    table="vueda_workflow_workflow",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflow",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_workflowevent" ("code", "content_type_id", "historical_app_label", "historical_model", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."code", NEW."content_type_id", NEW."historical_app_label", NEW."historical_model", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="07f4e8ecc45a4427b301426a378e862489b0f5ff",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_0c791",
                    table="vueda_workflow_workflow",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflow",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_workflowevent" ("code", "content_type_id", "historical_app_label", "historical_model", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."code", OLD."content_type_id", OLD."historical_app_label", OLD."historical_model", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="8351d364163278d3f8f4e3226945a1d0acb49141",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_5633c",
                    table="vueda_workflow_workflow",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="workflowevent",
            name="content_type",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="workflowevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workflowevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.workflow",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflowevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="4b80bb11cec9abaceca2be14f554e845078e19c9",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_bf160",
                    table="vueda_workflow_workflowevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
