# Generated by Django 6.1 on 2026-09-04 16:14

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("vueda_workflow", "0007_workflowevent_workflow_insert_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitialStateEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectStateEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("object_id", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StateEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StatePermissionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("historical_permission_codename", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_app_label", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_model_name", models.CharField(blank=True, max_length=100)),
                ("historical_group_name", models.CharField(blank=True, max_length=150)),
                ("grant_or_deny", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransitionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransitionPermissionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("historical_permission_codename", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_app_label", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_model_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransitionSourceEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("ignored", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkflowPermissionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("historical_permission_codename", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_app_label", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_model_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="initialstate",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_initialstateevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id", "workflow_id") VALUES (NEW."id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."state_id", NEW."workflow_id"); RETURN NULL;',
                    hash="ec1618fa2045a6609f464ad9452933ed5ac6e101",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_1c33b",
                    table="vueda_workflow_initialstate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="initialstate",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_initialstateevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id", "workflow_id") VALUES (NEW."id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."state_id", NEW."workflow_id"); RETURN NULL;',
                    hash="b4957b1d236d9d65543f5b86be037e0ffd636fd0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1bbe2",
                    table="vueda_workflow_initialstate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="initialstate",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_initialstateevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id", "workflow_id") VALUES (OLD."id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."state_id", OLD."workflow_id"); RETURN NULL;',
                    hash="f6202240b513b49addd403461fd7b169986cb9ed",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_c2d68",
                    table="vueda_workflow_initialstate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="objectstate",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_objectstateevent" ("id", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id", "workflow_id") VALUES (NEW."id", NEW."object_id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."state_id", NEW."workflow_id"); RETURN NULL;',
                    hash="3d66dd7cbd31633f1b3ea3ff3d194847f663cb9d",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_239db",
                    table="vueda_workflow_objectstate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="objectstate",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_objectstateevent" ("id", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id", "workflow_id") VALUES (NEW."id", NEW."object_id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."state_id", NEW."workflow_id"); RETURN NULL;',
                    hash="457811a8b0968a0f5e91c1106e11ac76a1437674",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_648f6",
                    table="vueda_workflow_objectstate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="objectstate",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_objectstateevent" ("id", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id", "workflow_id") VALUES (OLD."id", OLD."object_id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."state_id", OLD."workflow_id"); RETURN NULL;',
                    hash="473b3235a281c1e99c72ab1784d0700258bc4a56",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_438f5",
                    table="vueda_workflow_objectstate",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="state",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_stateevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "workflow_id") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."workflow_id"); RETURN NULL;',
                    hash="393f8c4fe6ffc685a3b759924c228277466ce9be",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3496c",
                    table="vueda_workflow_state",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="state",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_stateevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "workflow_id") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."workflow_id"); RETURN NULL;',
                    hash="5fd78b69c859ee5ea184d7133bdc7fb1daedfa32",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_7c7e6",
                    table="vueda_workflow_state",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="state",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_stateevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "workflow_id") VALUES (OLD."code", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."workflow_id"); RETURN NULL;',
                    hash="fd505c82347cbf5b33f77af86f30902dafdb18e7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_08e6d",
                    table="vueda_workflow_state",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="statepermission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_statepermissionevent" ("grant_or_deny", "group_id", "historical_group_name", "historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id") VALUES (NEW."grant_or_deny", NEW."group_id", NEW."historical_group_name", NEW."historical_permission_codename", NEW."historical_permission_content_type_app_label", NEW."historical_permission_content_type_model_name", NEW."id", NEW."permission_id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."state_id"); RETURN NULL;',
                    hash="fd9611a23c04518923025d78c394613c71da1ce1",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_772cb",
                    table="vueda_workflow_statepermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="statepermission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_statepermissionevent" ("grant_or_deny", "group_id", "historical_group_name", "historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id") VALUES (NEW."grant_or_deny", NEW."group_id", NEW."historical_group_name", NEW."historical_permission_codename", NEW."historical_permission_content_type_app_label", NEW."historical_permission_content_type_model_name", NEW."id", NEW."permission_id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."state_id"); RETURN NULL;',
                    hash="8444dfd362ef9ce8e81538d8f9ef708781f048f5",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c2427",
                    table="vueda_workflow_statepermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="statepermission",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_statepermissionevent" ("grant_or_deny", "group_id", "historical_group_name", "historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "state_id") VALUES (OLD."grant_or_deny", OLD."group_id", OLD."historical_group_name", OLD."historical_permission_codename", OLD."historical_permission_content_type_app_label", OLD."historical_permission_content_type_model_name", OLD."id", OLD."permission_id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."state_id"); RETURN NULL;',
                    hash="047bc89b09c40a1ff6a744e948c397b4d8f26ac9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_8ef28",
                    table="vueda_workflow_statepermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transition",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_transitionevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_id", "workflow_id") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."target_id", NEW."workflow_id"); RETURN NULL;',
                    hash="8b7ce8c192f658faf0e927e957b6a487dfc5d327",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_5ac08",
                    table="vueda_workflow_transition",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transition",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_transitionevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_id", "workflow_id") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."target_id", NEW."workflow_id"); RETURN NULL;',
                    hash="fa8e8883f8f90178523529d1453d35b8a44bc6a7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6be79",
                    table="vueda_workflow_transition",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transition",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_transitionevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "target_id", "workflow_id") VALUES (OLD."code", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."target_id", OLD."workflow_id"); RETURN NULL;',
                    hash="370244d6431b611f1a6e2b7d3dc8c4c642af27e3",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a70b6",
                    table="vueda_workflow_transition",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionpermission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_transitionpermissionevent" ("historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transition_id") VALUES (NEW."historical_permission_codename", NEW."historical_permission_content_type_app_label", NEW."historical_permission_content_type_model_name", NEW."id", NEW."permission_id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."transition_id"); RETURN NULL;',
                    hash="1b63e1b33718dd3e5dfeb9fea76d60c377fa9db6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_31522",
                    table="vueda_workflow_transitionpermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionpermission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_transitionpermissionevent" ("historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transition_id") VALUES (NEW."historical_permission_codename", NEW."historical_permission_content_type_app_label", NEW."historical_permission_content_type_model_name", NEW."id", NEW."permission_id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."transition_id"); RETURN NULL;',
                    hash="57f4f54e4d89b1eed4cdfeac8d688d3865d57721",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_35498",
                    table="vueda_workflow_transitionpermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionpermission",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_transitionpermissionevent" ("historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "transition_id") VALUES (OLD."historical_permission_codename", OLD."historical_permission_content_type_app_label", OLD."historical_permission_content_type_model_name", OLD."id", OLD."permission_id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."transition_id"); RETURN NULL;',
                    hash="fef71612716070be3df4cc02d4b63b6ad9911a27",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_5313c",
                    table="vueda_workflow_transitionpermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionsource",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_transitionsourceevent" ("id", "ignored", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "transition_id") VALUES (NEW."id", NEW."ignored", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."source_id", NEW."transition_id"); RETURN NULL;',
                    hash="aec8030bbb0970ee6527f34bb081ff8d1fbaadfa",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_bb218",
                    table="vueda_workflow_transitionsource",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionsource",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_transitionsourceevent" ("id", "ignored", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "transition_id") VALUES (NEW."id", NEW."ignored", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."source_id", NEW."transition_id"); RETURN NULL;',
                    hash="b14a3526cfbc633d07c50abafbabf5d4439a1bd7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_f6d06",
                    table="vueda_workflow_transitionsource",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionsource",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_transitionsourceevent" ("id", "ignored", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "transition_id") VALUES (OLD."id", OLD."ignored", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."source_id", OLD."transition_id"); RETURN NULL;',
                    hash="9a6f61c78b80e96b70630d57db597ae50ce79e46",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_54395",
                    table="vueda_workflow_transitionsource",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflowpermission",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_workflowpermissionevent" ("historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "workflow_id") VALUES (NEW."historical_permission_codename", NEW."historical_permission_content_type_app_label", NEW."historical_permission_content_type_model_name", NEW."id", NEW."permission_id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."workflow_id"); RETURN NULL;',
                    hash="12873eea1bd2fb6e6db76e46ce685d4331c7fad8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_7fa70",
                    table="vueda_workflow_workflowpermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflowpermission",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_workflow_workflowpermissionevent" ("historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "workflow_id") VALUES (NEW."historical_permission_codename", NEW."historical_permission_content_type_app_label", NEW."historical_permission_content_type_model_name", NEW."id", NEW."permission_id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."workflow_id"); RETURN NULL;',
                    hash="e2ee61659ec1ef5f715d5295225e4bb9a82c2e15",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_29725",
                    table="vueda_workflow_workflowpermission",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflowpermission",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_workflow_workflowpermissionevent" ("historical_permission_codename", "historical_permission_content_type_app_label", "historical_permission_content_type_model_name", "id", "permission_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "workflow_id") VALUES (OLD."historical_permission_codename", OLD."historical_permission_content_type_app_label", OLD."historical_permission_content_type_model_name", OLD."id", OLD."permission_id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."workflow_id"); RETURN NULL;',
                    hash="29524c9a60b67119eaf1453192c2a0fb9aa33754",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_7dc49",
                    table="vueda_workflow_workflowpermission",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="initialstateevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="initialstateevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.initialstate",
            ),
        ),
        migrations.AddField(
            model_name="initialstateevent",
            name="state",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.state",
            ),
        ),
        migrations.AddField(
            model_name="initialstateevent",
            name="workflow",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.workflow",
            ),
        ),
        migrations.AddField(
            model_name="objectstateevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="objectstateevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.objectstate",
            ),
        ),
        migrations.AddField(
            model_name="objectstateevent",
            name="state",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.state",
            ),
        ),
        migrations.AddField(
            model_name="objectstateevent",
            name="workflow",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.workflow",
            ),
        ),
        migrations.AddField(
            model_name="stateevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="stateevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.state",
            ),
        ),
        migrations.AddField(
            model_name="stateevent",
            name="workflow",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.workflow",
            ),
        ),
        migrations.AddField(
            model_name="statepermissionevent",
            name="group",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="statepermissionevent",
            name="permission",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="statepermissionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="statepermissionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.statepermission",
            ),
        ),
        migrations.AddField(
            model_name="statepermissionevent",
            name="state",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.state",
            ),
        ),
        migrations.AddField(
            model_name="transitionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="transitionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.transition",
            ),
        ),
        migrations.AddField(
            model_name="transitionevent",
            name="target",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.state",
            ),
        ),
        migrations.AddField(
            model_name="transitionevent",
            name="workflow",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.workflow",
            ),
        ),
        migrations.AddField(
            model_name="transitionpermissionevent",
            name="permission",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="transitionpermissionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="transitionpermissionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.transitionpermission",
            ),
        ),
        migrations.AddField(
            model_name="transitionpermissionevent",
            name="transition",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.transition",
            ),
        ),
        migrations.AddField(
            model_name="transitionsourceevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="transitionsourceevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.transitionsource",
            ),
        ),
        migrations.AddField(
            model_name="transitionsourceevent",
            name="source",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.state",
            ),
        ),
        migrations.AddField(
            model_name="transitionsourceevent",
            name="transition",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.transition",
            ),
        ),
        migrations.AddField(
            model_name="workflowpermissionevent",
            name="permission",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="workflowpermissionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workflowpermissionevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_workflow.workflowpermission",
            ),
        ),
        migrations.AddField(
            model_name="workflowpermissionevent",
            name="workflow",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="vueda_workflow.workflow",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="initialstateevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="0b93254c1681b660c367d36b735d8e72d4bdb93b",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_b61bd",
                    table="vueda_workflow_initialstateevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="objectstateevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="ce99419005ef43c7b5d0b947b219046490dcdc64",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_bd8a7",
                    table="vueda_workflow_objectstateevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="stateevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2661d7d1f46ee4ce4b59f53206ceb09de5ed2e6d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_bd044",
                    table="vueda_workflow_stateevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="statepermissionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="263e80b982111e16b0dbe617f002d1922fa1a1d4",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d21a6",
                    table="vueda_workflow_statepermissionevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a81c98998c794c875f4d78450e0f765aab193280",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_1bde1",
                    table="vueda_workflow_transitionevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionpermissionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="26e5a13db93911da91ba769d59d758d87fef3c4f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_b0edf",
                    table="vueda_workflow_transitionpermissionevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="transitionsourceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="d733cf7c018c72ab16d64ff8203d5b29705bc1ac",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_a534f",
                    table="vueda_workflow_transitionsourceevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workflowpermissionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="206aeaa1a7f4ec63f62f311c0e46df31d6f7104c",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d8d75",
                    table="vueda_workflow_workflowpermissionevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
