# Generated by Django 5.2.15 on 2026-06-29 18:51
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_updating_bad_migrations", "0001_initial"),
    ]

    operations = []
