# Generated by Django 5.2.15 on 2026-06-29 18:51
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
from django.db import migrations


history_change_reason = "Workflow Migration - 0003_workflow_migrations_2026_06_29"
migration_app_label = "workflow_updating_bad_migrations"
changed_data = [


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_updating_bad_migrations", "0002_workflow_migrations_2026_06_29"),
    ]

    operations = []
