import { renderCodeInline, renderFrontmatter, renderTable } from "./markdown.js";

const code = renderCodeInline;
const anchor = (kind, name) => `${kind}-${name.toLowerCase().replaceAll("_", "-")}`;
const link = (kind, name) => `[${code(name)}](#${anchor(kind, name)})`;
const source = (location) => code(`${location.file}:${location.line}`);

function conditions(read) {
    const scope = read.function === "get_production_defaults" ? "Production defaults" : "Base defaults";
    return [scope, ...read.conditions.map(code)].join("; ");
}

function renderConfig(entry) {
    const lines = [`### ${entry.name} {#${anchor("config", entry.name)}}`, "", entry.description, ""];
    lines.push(`Django setting paths: ${entry.settings.map(code).join(", ")}.`, "");
    if (entry.when) {
        lines.push(`Applies: ${entry.when}`, "");
    }
    lines.push(
        renderTable(
            ["Accessor", "Default or requirement", "Scope", "Read at"],
            entry.reads.map((read) => [
                code(read.accessor === "__call__" ? "env(...)" : `env.${read.accessor}(...)`),
                read.default === null ? "Required when read" : code(read.default),
                conditions(read),
                source(read.source),
            ]),
        ),
        "",
    );
    return lines;
}

function renderSetting(entry) {
    const lines = [`### ${entry.name} {#${anchor("setting", entry.name)}}`, "", entry.description, ""];
    if (entry.configKey) {
        lines.push(`Config input: ${link("config", entry.configKey)}.`, "");
    }
    if (entry.definitions.length) {
        lines.push("<details>", "<summary>Factory declarations and overrides</summary>", "");
        for (const definition of entry.definitions) {
            const target =
                definition.path[0] +
                definition.path
                    .slice(1)
                    .map((part) => `[${JSON.stringify(part)}]`)
                    .join("");
            const operation = definition.operation === "Add" ? "+=" : "=";
            lines.push(
                `${conditions(definition)}. Source: ${source(definition.source)}.`,
                "",
                "```python",
                `${target} ${operation} ${definition.expression}`,
                "```",
                "",
            );
        }
        lines.push("</details>", "");
    } else {
        lines.push("The defaults factories do not set this Django setting.", "");
    }
    if (entry.reads.length) {
        const fallbacks = [
            ...new Set(entry.reads.filter((read) => read.fallback !== null).map((read) => read.fallback)),
        ];
        if (fallbacks.length) {
            lines.push(
                `Local fallback values: ${fallbacks.map(code).join(", ")}. These apply only at the read sites that supply them.`,
                "",
            );
        } else if (entry.reads.some((read) => read.access !== "hasattr")) {
            lines.push("No fallback at the direct read sites. The setting must exist when those reads execute.", "");
        } else {
            lines.push("VUEDA checks whether this setting exists before using it.", "");
        }
        lines.push(
            "<details>",
            "<summary>Read locations</summary>",
            "",
            renderTable(
                ["Source", "Access", "Local fallback"],
                entry.reads.map((read) => [
                    source(read.source),
                    code(read.access),
                    read.fallback === null ? "None supplied" : code(read.fallback),
                ]),
            ),
            "",
            "</details>",
            "",
        );
    }
    return lines;
}

export function renderConfigurationBundle(bundle) {
    const lines = [
        renderFrontmatter({
            title: "Server configuration",
            type: "reference",
            audience: "integrator",
            status: "final",
        }),
        "<!-- Generated by docs-tooling. Edit docs-tooling/configuration.json and the server sources. -->",
        "",
        "# Server configuration",
        "",
        "Config keys are inputs read through the env adapter by `get_defaults` and `get_production_defaults`. Django settings are the values the application reads after settings assembly. A config key can supply a differently named or nested Django setting.",
        "",
        "Defaults below are Python expressions from source, not values from a running project. A key without a default is required whenever its read executes. Production keys apply only when calling `get_production_defaults`; Mailgun keys apply only with that email backend. Projects can override the returned Django settings.",
        "",
        "The settings inventory includes direct reads, local fallbacks, and selected conditional factory outputs. Standard Django settings used without changing their meaning can have explicit exemptions, listed below. Factory declarations show source expressions and overrides in order; they do not evaluate local variables or optional imports.",
        "",
        "See [Configuration surface and defaults](../core-concepts/configuration-surface-and-defaults) for assembly and override behavior, and [Configure cache and sessions](../guides/configure-cache-and-sessions) for cache setup. Client configuration belongs in the [JavaScript API reference](./api/js/).",
        "",
        "## Config keys",
        "",
        renderTable(
            ["Key", "Django setting paths", "Default or requirement"],
            bundle.config.map((entry) => [
                link("config", entry.name),
                entry.settings.map(code).join(", "),
                [
                    ...new Set(
                        entry.reads.map((read) => (read.default === null ? "Required when read" : code(read.default))),
                    ),
                ].join("; "),
            ]),
        ),
        "",
    ];
    for (const entry of bundle.config) {
        lines.push(...renderConfig(entry));
    }
    lines.push(
        "## Django settings",
        "",
        "Local fallbacks belong to individual reads. They do not replace values supplied by the defaults factories or by a project's settings module.",
        "",
        bundle.settings.map((entry) => `- ${link("setting", entry.name)}`).join("\n"),
        "",
    );
    for (const entry of bundle.settings) {
        lines.push(...renderSetting(entry));
    }
    lines.push(
        "## Django exemptions",
        "",
        ...bundle.djangoExemptions.map((entry) => `- ${code(entry.name)}: ${entry.reason}`),
        "",
    );
    return new Map([["configuration.md", lines.join("\n")]]);
}
