# Generated by Django 5.0.4 on 2024-05-13 19:35
from django.apps import apps as django_apps
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def make_sure_contenttypes_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_deleted")
    create_contenttypes(app, interactive=False)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_deleted", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_contenttypes_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group
                (
                    name
                )
            VALUES
                (
                    'WorkflowDeletedAdmin'
                ),
                (
                    'WorkflowDeletedWorker'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group
            WHERE
                name in ('WorkflowDeletedAdmin', 'WorkflowDeletedWorker');""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_permission
                (
                    name,
                    content_type_id,
                    codename
                )
            VALUES
                (
                    'Can Do Something',
                    (
                        SELECT
                            id
                        FROM
                            django_content_type
                        WHERE
                            app_label = 'workflow_deleted'
                            AND model = 'workflowdeleted'
                    ),
                    'can_do_something'
                ),
                (
                    'Can Do Something Else',
                    (
                        SELECT
                            id
                        FROM
                            django_content_type
                        WHERE
                            app_label = 'workflow_deleted'
                            AND model = 'workflowdeleted'
                    ),
                    'can_do_something_else'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_permission
            WHERE
                codename in ('can_do_something', 'can_do_something_else')
                AND content_type_id = (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_deleted'
                        AND model = 'workflowdeleted'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group_permissions
                (
                    group_id,
                    permission_id
                )
            VALUES
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedAdmin'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_deleted'
                                    AND model = 'workflowdeleted'
                        )
                    )
                ),
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedWorker'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_deleted'
                                    AND model = 'workflowdeleted'
                        )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group_permissions
            WHERE
                group_id IN (
                    SELECT
                        id
                    FROM
                        auth_group
                    WHERE
                        name in ('WorkflowDeletedAdmin', 'WorkflowDeletedWorker')
                );""",
        ),
    ]
