# Generated by Django 5.0.4 on 2024-05-13 20:56
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.utils import timezone


history_change_reason = "Workflow Migration - 0003_workflow_migrations_2024_05_13"
history_date = None
migration_app_label = "workflow_deleted"
changed_data = [
    {
        "added": {
            "initialstate": {
                "state_id": {"code": "state_1", "workflow_id": {"code": "deleted_workflow"}},
                "workflow_id": {"code": "deleted_workflow"},
            },
            "state": [
                {"code": "state_3", "name": "State 3", "workflow_id": {"code": "deleted_workflow"}},
                {"code": "state_1", "name": "State 1", "workflow_id": {"code": "deleted_workflow"}},
                {"code": "state_2", "name": "State 2", "workflow_id": {"code": "deleted_workflow"}},
            ],
            "statepermission": [
                {
                    "grant_or_deny": False,
                    "group_id": {"name": "WorkflowDeletedAdmin"},
                    "historical_group_name": "WorkflowDeletedAdmin",
                    "historical_permission_codename": "can_do_something",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "can_do_something",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "state_id": {"code": "state_1", "workflow_id": {"code": "deleted_workflow"}},
                },
                {
                    "grant_or_deny": True,
                    "group_id": {"name": "WorkflowDeletedWorker"},
                    "historical_group_name": "WorkflowDeletedWorker",
                    "historical_permission_codename": "can_do_something_else",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "can_do_something_else",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "state_id": {"code": "state_1", "workflow_id": {"code": "deleted_workflow"}},
                },
                {
                    "grant_or_deny": True,
                    "group_id": {"name": "WorkflowDeletedAdmin"},
                    "historical_group_name": "WorkflowDeletedAdmin",
                    "historical_permission_codename": "update_workflowdeleted",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "update_workflowdeleted",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "state_id": {"code": "state_2", "workflow_id": {"code": "deleted_workflow"}},
                },
            ],
            "transition": [
                {
                    "code": "go_to_state_3",
                    "name": "Go To State 3",
                    "target_id": {"code": "state_3", "workflow_id": {"code": "deleted_workflow"}},
                    "workflow_id": {"code": "deleted_workflow"},
                },
                {
                    "code": "go_to_state_2",
                    "name": "Go To State 2",
                    "target_id": {"code": "state_2", "workflow_id": {"code": "deleted_workflow"}},
                    "workflow_id": {"code": "deleted_workflow"},
                },
                {
                    "code": "go_to_state_1",
                    "name": "Go To State 1",
                    "target_id": {"code": "state_1", "workflow_id": {"code": "deleted_workflow"}},
                    "workflow_id": {"code": "deleted_workflow"},
                },
            ],
            "transitionpermission": [
                {
                    "historical_permission_codename": "can_do_something_else",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "can_do_something_else",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "deleted_workflow"}},
                },
                {
                    "historical_permission_codename": "update_workflowdeleted",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "update_workflowdeleted",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "deleted_workflow"}},
                },
                {
                    "historical_permission_codename": "can_do_something",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "can_do_something",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "transition_id": {"code": "go_to_state_2", "workflow_id": {"code": "deleted_workflow"}},
                },
            ],
            "transitionsource": [
                {
                    "source_id": {"code": "state_2", "workflow_id": {"code": "deleted_workflow"}},
                    "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "deleted_workflow"}},
                },
                {
                    "source_id": {"code": "state_3", "workflow_id": {"code": "deleted_workflow"}},
                    "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "deleted_workflow"}},
                },
                {
                    "source_id": {"code": "state_1", "workflow_id": {"code": "deleted_workflow"}},
                    "transition_id": {"code": "go_to_state_2", "workflow_id": {"code": "deleted_workflow"}},
                },
            ],
            "workflow": {
                "code": "deleted_workflow",
                "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                "historical_app_label": "workflow_deleted",
                "historical_model": "workflowdeleted",
                "name": "Deleted Workflow",
            },
            "workflowpermission": [
                {
                    "historical_permission_codename": "can_do_something",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "can_do_something",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "workflow_id": {"code": "deleted_workflow"},
                },
                {
                    "historical_permission_codename": "can_do_something_else",
                    "historical_permission_content_type_app_label": "workflow_deleted",
                    "historical_permission_content_type_model_name": "workflowdeleted",
                    "permission_id": {
                        "codename": "can_do_something_else",
                        "content_type_id": {"app_label": "workflow_deleted", "model": "workflowdeleted"},
                    },
                    "workflow_id": {"code": "deleted_workflow"},
                },
            ],
        },
        "changed": None,
        "deleted": None,
    }
]


def forwards_migrate_workflow(apps, schema_editor):
    set_history_date()

    for changed_item in changed_data:
        added = changed_item["added"]
        changed = changed_item["changed"]
        deleted = changed_item["deleted"]

        # Add and Change
        handle_workflow(apps, added=added, changed=changed)
        handle_workflow_permission(apps, added=added, changed=changed)
        handle_state(apps, added=added, changed=changed)
        handle_state_permission(apps, added=added, changed=changed)
        handle_initial_state(apps, added=added, changed=changed)
        handle_transition(apps, added=added, changed=changed)
        handle_transition_permission(apps, added=added, changed=changed)
        handle_transition_source(apps, added=added, changed=changed)

        # Delete - Do this last, in case any objects, before they were changed, were using what is being deleted.
        handle_transition_source(apps, deleted=deleted)
        handle_transition_permission(apps, deleted=deleted)
        handle_transition(apps, deleted=deleted)
        handle_initial_state(apps, deleted=deleted)
        handle_state_permission(apps, deleted=deleted)
        handle_state(apps, deleted=deleted)
        handle_workflow_permission(apps, deleted=deleted)
        handle_workflow(apps, deleted=deleted)


def backwards_migrate_workflow(apps, schema_editor):
    pass
    # reversing=True

    # handle_workflow(apps, deleted=deleted)

    # We need to do added before changed when we reverse.
    # handle_workflow(apps, added=added)
    # handle_workflow(apps, changed=changed, reversing=True)


def handle_workflow(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_workflow = apps.get_model("workflow", "HistoricalWorkflow")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "workflow"

    # Make sure we change workflow before we add or delete anything, so if the
    # code changes, everything will be able to get the workflow with the new code.
    if changed is not None and model_name in changed:
        data = changed[model_name]

        workflow = model_workflow.objects.get(**data["id"])

        del data["id"]

        # The changed workflow fields have a tuple with 2 values, the other fields do not.
        # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
        for key, values in data.items():
            if type(values) is not tuple:
                continue

            old_value, new_value = values

            if reversing:
                setattr(workflow, key, old_value)

            else:
                setattr(workflow, key, new_value)

        workflow.save()

        add_history_to_data(
            data,
            workflow,
            "~",
            fields=(
                "id",
                "code",
                "content_type_id",
                "historical_app_label",
                "historical_model",
                "name",
            ),
        )
        historical_workflow.objects.create(**data)

    if added is not None and model_name in added:
        data = added[model_name]

        content_type = model_content_type.objects.get(**data["content_type_id"])
        data["content_type_id"] = content_type.pk

        workflow = model_workflow.objects.create(**data)

        add_history_to_data(data, workflow, "+")
        historical_workflow.objects.create(**data)

    if deleted is not None and model_name in deleted:
        data = deleted[model_name]

        content_type = model_content_type.objects.get(**data["content_type_id"])
        data["content_type_id"] = content_type.pk

        workflow = model_workflow.objects.get(**data["id"])

        del data["id"]

        add_history_to_data(data, workflow, "-")
        historical_workflow.objects.create(**data)
        workflow.delete()


def handle_workflow_permission(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_workflow_permission = apps.get_model("workflow", "HistoricalWorkflowPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_workflow_permission = apps.get_model("workflow", "WorkflowPermission")
    model_name = "workflowpermission"

    if added is not None and model_name in added:
        for data in added[model_name]:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.create(**data)

            add_history_to_data(data, workflow_permission, "+")
            historical_workflow_permission.objects.create(**data)

    if changed is not None and model_name in changed:
        for data in changed[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            new_permission_ids = []
            for permission_id in data["permission_id"]:
                content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                permission_id["content_type_id"] = content_type.pk
                permission = model_permission.objects.get(**permission_id)
                new_permission_ids.append(permission.pk)
            data["permission_id"] = new_permission_ids

            # The changed historical permission fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(workflow_permission, key, old_value)

                else:
                    setattr(workflow_permission, key, new_value)

            workflow_permission.save()

            add_history_to_data(
                data,
                workflow_permission,
                "~",
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "workflow_id",
                ),
            )
            historical_workflow_permission.objects.create(**data)

    if deleted is not None and model_name in deleted:
        for data in deleted[model_name]:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow_permission, "-")
            historical_workflow_permission.objects.create(**data)
            workflow_permission.delete()


def handle_state(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_state = apps.get_model("workflow", "HistoricalState")
    model_state = apps.get_model("workflow", "State")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "state"

    if added is not None and model_name in added:
        for data in added[model_name]:
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            state = model_state.objects.create(**data)

            add_history_to_data(data, state, "+")
            historical_state.objects.create(**data)

    if changed is not None and model_name in changed:
        for data in changed[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # The changed fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(state, key, old_value)

                else:
                    setattr(state, key, new_value)

            state.save()

            add_history_to_data(
                data,
                state,
                "~",
                fields=(
                    "id",
                    "code",
                    "name",
                    "workflow_id",
                ),
            )
            historical_state.objects.create(**data)

    if deleted is not None and model_name in deleted:
        for data in deleted[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            state = model_state.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state, "-")
            historical_state.objects.create(**data)
            state.delete()


def handle_state_permission(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_state_permission = apps.get_model("workflow", "HistoricalStatePermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_group = apps.get_model("auth", "Group")
    model_permission = apps.get_model("auth", "Permission")
    model_state = apps.get_model("workflow", "State")
    model_state_permission = apps.get_model("workflow", "StatePermission")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "statepermission"

    if added is not None and model_name in added:
        for data in added[model_name]:
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["group_id"])
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.create(**data)

            add_history_to_data(data, state_permission, "+")
            historical_state_permission.objects.create(**data)

    if changed is not None and model_name in changed:
        for data in changed[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            group = model_group.objects.get(**get_id_values_from_item(data["id"]["group_id"], reversing=reversing))
            data["id"]["group_id"] = group.pk
            state_permission = model_state_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            new_permission_ids = []
            for permission_id in data["permission_id"]:
                content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                permission_id["content_type_id"] = content_type.pk
                permission = model_permission.objects.get(**permission_id)
                new_permission_ids.append(permission.pk)
            data["permission_id"] = new_permission_ids

            new_group_ids = []
            for group_id in data["group_id"]:
                group = model_group.objects.get(**group_id)
                new_group_ids.append(group.pk)
            data["group_id"] = new_group_ids

            # The changed fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(state_permission, key, old_value)

                else:
                    setattr(state_permission, key, new_value)

            state_permission.save()

            add_history_to_data(
                data,
                state_permission,
                "~",
                fields=(
                    "id",
                    "grant_or_deny",
                    "group_id",
                    "historical_group_name",
                    "historical_permission_codename",
                    "permission_id",
                    "state_id",
                ),
            )
            historical_state_permission.objects.create(**data)

    if deleted is not None and model_name in deleted:
        for data in deleted[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["id"]["group_id"])
            data["id"]["group_id"] = group.pk
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state_permission, "-")
            historical_state_permission.objects.create(**data)
            state_permission.delete()


def handle_initial_state(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_initial_state = apps.get_model("workflow", "HistoricalInitialState")
    model_initial_state = apps.get_model("workflow", "InitialState")
    model_state = apps.get_model("workflow", "State")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "initialstate"

    if added is not None and model_name in added:
        data = added[model_name]

        workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
        data["state_id"]["workflow_id"] = workflow.pk
        state = model_state.objects.get(**data["state_id"])
        data["state_id"] = state.pk
        data["workflow_id"] = workflow.pk

        initial_state = model_initial_state.objects.create(**data)

        add_history_to_data(data, initial_state, "+")
        historical_initial_state.objects.create(**data)

    if changed is not None and model_name in changed:
        data = changed[model_name]

        data["id"]["state_id"] = get_id_values_from_item(data["id"]["state_id"], reversing=reversing)
        workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
        data["id"]["state_id"]["workflow_id"] = workflow.pk
        state = model_state.objects.get(**data["id"]["state_id"])
        data["id"]["state_id"] = state.pk
        data["id"]["workflow_id"] = workflow.pk

        initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

        del data["id"]

        # The state is the only thing that can change, so we
        # can use what exists above, since it is the same data.
        initial_state.state_id = state.pk
        initial_state.save()

        add_history_to_data(
            data,
            initial_state,
            "~",
            fields=(
                "id",
                "state_id",
                "workflow_id",
            ),
        )
        historical_initial_state.objects.create(**data)

    if deleted is not None and model_name in deleted:
        data = deleted[model_name]

        workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
        data["id"]["state_id"]["workflow_id"] = workflow.pk
        data["state_id"]["workflow_id"] = workflow.pk
        state = model_state.objects.get(**data["id"]["state_id"])
        data["id"]["state_id"] = state.pk
        data["state_id"] = state.pk
        data["id"]["workflow_id"] = workflow.pk
        data["workflow_id"] = workflow.pk

        initial_state = model_initial_state.objects.get(**data["id"])

        del data["id"]

        add_history_to_data(data, initial_state, "-")
        historical_initial_state.objects.create(**data)
        initial_state.delete()


def handle_transition(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_transition = apps.get_model("workflow", "HistoricalTransition")
    model_state = apps.get_model("workflow", "State")
    model_transition = apps.get_model("workflow", "Transition")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "transition"

    if added is not None and model_name in added:
        for data in added[model_name]:
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.create(**data)

            add_history_to_data(data, transition, "+")
            historical_transition.objects.create(**data)

    if changed is not None and model_name in changed:
        for data in changed[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # The changed fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(transition, key, old_value)

                else:
                    setattr(transition, key, new_value)

            transition.save()

            add_history_to_data(
                data,
                transition,
                "~",
                fields=(
                    "id",
                    "code",
                    "name",
                    "target_id",
                    "workflow_id",
                ),
            )
            historical_transition.objects.create(**data)

    if deleted is not None and model_name in deleted:
        for data in deleted[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition, "-")
            historical_transition.objects.create(**data)
            transition.delete()


def handle_transition_permission(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_transition_permission = apps.get_model("workflow", "HistoricalTransitionPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_transition = apps.get_model("workflow", "Transition")
    model_transition_permission = apps.get_model("workflow", "TransitionPermission")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "transitionpermission"

    if added is not None and model_name in added:
        for data in added[model_name]:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.create(**data)

            add_history_to_data(data, transition_permission, "+")
            historical_transition_permission.objects.create(**data)

    if changed is not None and model_name in changed:
        for data in changed[model_name]:
            transition = model_transition.objects.get(**data["id"]["workflow_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # The permission is the main thing that can change.
            content_type = model_content_type.objects.get(**data["id"]["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            transition_permission.permission_id = permission.pk

            # The changed historical permission fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(transition_permission, key, old_value)

                else:
                    setattr(transition_permission, key, new_value)

            transition_permission.save()

            add_history_to_data(
                data,
                transition_permission,
                "~",
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "transition_id",
                ),
            )
            historical_transition_permission.objects.create(**data)

    if deleted is not None and model_name in deleted:
        for data in deleted[model_name]:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_permission, "-")
            historical_transition_permission.objects.create(**data)
            transition_permission.delete()


def handle_transition_source(apps, *, added=None, changed=None, deleted=None, reversing=False):
    historical_transition_source = apps.get_model("workflow", "HistoricalTransitionSource")
    model_state = apps.get_model("workflow", "State")
    model_transition = apps.get_model("workflow", "Transition")
    model_transition_source = apps.get_model("workflow", "TransitionSource")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_name = "transitionsource"

    if added is not None and model_name in added:
        for data in added[model_name]:
            workflow = model_workflow.objects.get(**data["source_id"]["workflow_id"])
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["source_id"])
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.create(**data)

            add_history_to_data(data, transition_source, "+")
            historical_transition_source.objects.create(**data)

    if changed is not None and model_name in changed:
        for data in changed[model_name]:
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # The source is the only thing that can change, so we
            # can use what exists above, since it is the same data.
            transition_source.source_id = state.pk
            transition_source.save()

            add_history_to_data(
                data,
                transition_source,
                "~",
                fields=(
                    "id",
                    "permission_id",
                    "transition_id",
                ),
            )
            historical_transition_source.objects.create(**data)

    if deleted is not None and model_name in deleted:
        for data in deleted[model_name]:
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_source, "-")
            historical_transition_source.objects.create(**data)
            transition_source.delete()


def add_history_to_data(history_data, obj, history_type, fields=()):
    # For changed history
    for field_name in fields:
        history_data[field_name] = getattr(obj, field_name)

    # For all history
    history_data["history_change_reason"] = history_change_reason
    history_data["history_date"] = history_date
    history_data["history_relation_id"] = obj.pk
    history_data["history_type"] = history_type
    history_data["id"] = obj.pk


def get_id_values_from_item(values, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
    if type(values) is tuple:
        return values[1 if reversing else 0]

    return values


def get_id_values_from_dict(id_data, reversing=False):
    results = {}
    for field_name, values in id_data.items():
        results[field_name] = get_id_values_from_item(values)

    return results


def set_history_date():
    global history_date
    history_date = timezone.now()


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config(migration_app_label)
    create_permissions(app, interactive=False)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_deleted", "0002_create_workflow_deleted_permissions"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow,
            reverse_code=backwards_migrate_workflow,
        ),
    ]
