# Generated by Django 5.0.4 on 2024-05-23 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_deleted", "0003_workflow_migrations_2024_05_13"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_transitionsource
                WHERE
                    transition_id IN (
                        SELECT
                            T.id
                        FROM
                            vueda_workflow_transition T
                        JOIN
                            vueda_workflow_workflow W ON T.workflow_id = W.id
                        WHERE
                            W.code = 'deleted_workflow'
                    );""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_transitionsource
                    (
                        transition_id,
                        source_id,
                        ignored
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_transition
                            WHERE
                                code = 'go_to_state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        FALSE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_transition
                            WHERE
                                code = 'go_to_state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        FALSE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_transition
                            WHERE
                                code = 'go_to_state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_3'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        FALSE
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_transitionpermission
                WHERE
                    transition_id IN (
                        SELECT
                            T.id
                        FROM
                            vueda_workflow_transition T
                        JOIN
                            vueda_workflow_workflow W ON T.workflow_id = W.id
                        WHERE
                            W.code = 'deleted_workflow'
                    );""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_transitionpermission
                    (
                        permission_id,
                        historical_permission_codename,
                        historical_permission_content_type_app_label,
                        historical_permission_content_type_model_name,
                        transition_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'can_do_something',
                        'workflow_deleted',
                        'workflowdeleted',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_transition
                            WHERE
                                code = 'go_to_state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something_else'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'can_do_something_else',
                        'workflow_deleted',
                        'workflowdeleted',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_transition
                            WHERE
                                code = 'go_to_state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'update_workflowdeleted'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'update_workflowdeleted',
                        'workflow_deleted',
                        'workflowdeleted',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_transition
                            WHERE
                                code = 'go_to_state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_transition
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'deleted_workflow'
                    );""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_transition
                (
                    name,
                    code,
                    workflow_id,
                    target_id
                )
                VALUES
                    (
                        'Go To State 2',
                        'go_to_state_2',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    ),
                    (
                        'Go To State 1',
                        'go_to_state_1',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    ),
                    (
                        'Go To State 3',
                        'go_to_state_3',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_3'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    historical_permission_codename = 'can_do_something'
                    AND
                    historical_permission_content_type_app_label = 'workflow_deleted'
                    AND
                    historical_permission_content_type_model_name = 'workflowdeleted'
                    AND
                    historical_group_name = 'WorkflowDeletedAdmin';
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    historical_permission_codename = 'can_do_something_else'
                    AND
                    historical_permission_content_type_app_label = 'workflow_deleted'
                    AND
                    historical_permission_content_type_model_name = 'workflowdeleted'
                    AND
                    historical_group_name = 'WorkflowDeletedWorker';
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    historical_permission_codename = 'update_workflowdeleted'
                    AND
                    historical_permission_content_type_app_label = 'workflow_deleted'
                    AND
                    historical_permission_content_type_model_name = 'workflowdeleted'
                    AND
                    historical_group_name = 'WorkflowDeletedAdmin';""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_statepermission
                    (
                        state_id,
                        permission_id,
                        historical_permission_codename,
                        historical_permission_content_type_app_label,
                        historical_permission_content_type_model_name,
                        group_id,
                        historical_group_name,
                        grant_or_deny
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'can_do_something',
                        'workflow_deleted',
                        'workflowdeleted',
                        (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedAdmin'),
                        'WorkflowDeletedAdmin',
                        FALSE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something_else'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'can_do_something_else',
                        'workflow_deleted',
                        'workflowdeleted',
                        (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedWorker'),
                        'WorkflowDeletedWorker',
                        TRUE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'update_workflowdeleted'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'update_workflowdeleted',
                        'workflow_deleted',
                        'workflowdeleted',
                        (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedAdmin'),
                        'WorkflowDeletedAdmin',
                        TRUE
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_initialstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'deleted_workflow'
                    );""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'deleted_workflow'
                                )
                        )
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_state
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'deleted_workflow'
                    );""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_state
                    (
                        name,
                        code,
                        workflow_id
                    )
                VALUES
                    (
                        'State 1',
                        'state_1',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        )
                    ),
                    (
                        'State 2',
                        'state_2',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        )
                    ),
                    (
                        'State 3',
                        'state_3',
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        )
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_workflowpermission
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'deleted_workflow'
                    );""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_workflowpermission
                    (
                        workflow_id,
                        permission_id,
                        historical_permission_codename,
                        historical_permission_content_type_app_label,
                        historical_permission_content_type_model_name
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'can_do_something',
                        'workflow_deleted',
                        'workflowdeleted'
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'deleted_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something_else'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        ),
                        'can_do_something_else',
                        'workflow_deleted',
                        'workflowdeleted'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    auth_group_permissions
                WHERE
                    group_id IN (
                        SELECT
                            id
                        FROM
                            auth_group
                        WHERE
                            name in ('WorkflowDeletedAdmin', 'WorkflowDeletedWorker')
                    );""",
            reverse_sql="""
                INSERT INTO
                    auth_group_permissions
                    (
                        group_id,
                        permission_id
                    )
                VALUES
                    (
                        (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedAdmin'),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        )
                    ),
                    (
                        (SELECT id FROM auth_group WHERE name = 'WorkflowDeletedWorker'),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something_else'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_deleted'
                                        AND model = 'workflowdeleted'
                            )
                        )
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    auth_group
                WHERE
                    name in ('WorkflowDeletedAdmin', 'WorkflowDeletedWorker');""",
            reverse_sql="""
                INSERT INTO
                    auth_group
                    (
                        name
                    )
                VALUES
                    (
                        'WorkflowDeletedAdmin'
                    ),
                    (
                        'WorkflowDeletedWorker'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                DELETE FROM
                    vueda_workflow_workflow
                WHERE
                    code = 'deleted_workflow';""",
            reverse_sql="""
                INSERT INTO
                    vueda_workflow_workflow
                (
                    name,
                    code,
                    content_type_id,
                    historical_app_label,
                    historical_model
                )
                VALUES
                (
                    'Deleted Workflow',
                    'deleted_workflow',
                    (
                        SELECT
                            id
                        FROM
                            django_content_type
                        WHERE
                            app_label = 'workflow_deleted' AND
                            model = 'workflowdeleted'
                    ),
                    'workflow_deleted',
                    'workflowdeleted'
                );""",
        ),
    ]
