version: 2
updates:
    - package-ecosystem: "uv"
      directory: "/server"
      schedule:
          interval: "daily"
          time: "09:00"
          timezone: "Canada/Mountain"
      pull-request-branch-name:
          separator: "-"
      commit-message:
          prefix: "chore"
      open-pull-requests-limit: 10
      allow:
          - dependency-type: "all"
      assignees:
          - "arrai-innovations/developers"
    - package-ecosystem: "uv"
      directory: "/docs-tooling"
      schedule:
          interval: "daily"
          time: "09:00"
          timezone: "Canada/Mountain"
      pull-request-branch-name:
          separator: "-"
      commit-message:
          prefix: "chore"
      open-pull-requests-limit: 10
      allow:
          - dependency-type: "all"
      assignees:
          - "arrai-innovations/developers"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "09:00"
          timezone: "Canada/Mountain"
      pull-request-branch-name:
          separator: "-"
      commit-message:
          prefix: "chore"
      open-pull-requests-limit: 10
      allow:
          - dependency-type: "all"
      assignees:
          - "arrai-innovations/developers"
