# Generated by Django 5.2.15 on 2026-07-01 20:17
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
# Never modify this migration.  It is here for verifying updating works.
import copy
import datetime

from django.conf import settings
from django.db import migrations

from vueda.workflow.management.commands.makeworkflowmigrations import backwards_migrate_workflow
from vueda.workflow.management.commands.makeworkflowmigrations import forwards_migrate_workflow
from vueda.workflow.management.commands.makeworkflowmigrations import make_sure_permissions_exist


history_change_reason = "Workflow Migration - 0004_workflow_migrations_2026_07_01"
migration_app_label = "workflow_updating"
changed_data = [
    {
        "changes": {
            "code": "state_z",
            "id": {"code": "state_z", "workflow_id": {"code": "workflow_updating_workflow"}},
            "name": "State Z",
            "workflow_id": {"code": "workflow_updating_workflow"},
        },
        "history_date": datetime.datetime(2026, 7, 1, 20, 0, 50, 777052, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
]


def forwards_migrate_workflow_through_imports(apps, schema_editor):  # pragma: no cover
    # Copied changed_data, so tests can migrate forwards and backwards.
    forwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def backwards_migrate_workflow_through_imports(apps, schema_editor):  # pragma: no cover
    # Copied changed_data, so tests can migrate forwards and backwards.
    backwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def make_sure_permissions_exist_through_imports(apps, schema_editor):  # pragma: no cover
    make_sure_permissions_exist(migration_app_label)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("confirmation", "0002_gadget"),
        ("erring", "0002_workflow_migrations_2026_03_24"),
        ("logging", "0001_initial"),
        ("store", "0008_order_item_formatted_name"),
        ("vueda_release", "0001_initial"),
        ("vueda_user", "0005_sync_group_changes"),
        ("vueda_workflow", "0006_rename_fail_with_silent_historicaltransitionsource_ignored_and_more"),
        ("employee", "0001_initial"),
        ("workflow_updating", "0003_workflow_migrations_2026_06_30"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow,
            reverse_code=backwards_migrate_workflow,
        ),
    ]
