# Generated by Django 6.1 on 2026-09-24 22:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlainProbe",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="ProbeLookup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("probe_note", models.CharField(blank=True, default="lookup", max_length=64)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="ProbeMulti",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("probe_note", models.CharField(blank=True, default="from-a", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeOptedOut",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("token", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeTracked",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("token", models.CharField(blank=True, max_length=255)),
                ("probe_note", models.CharField(blank=True, default="tracked", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeUntracked",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="ProbeProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("features.probetracked",),
        ),
        migrations.CreateModel(
            name="PlainProbeEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeLookupEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("probe_note", models.CharField(blank=True, default="lookup", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeMultiEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("probe_note", models.CharField(blank=True, default="from-a", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeOptedOutEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("token", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeTrackedEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("probe_note", models.CharField(blank=True, default="tracked", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="plainprobeevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="plainprobeevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.plainprobe",
            ),
        ),
        migrations.AddField(
            model_name="probelookupevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probelookupevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probelookup",
            ),
        ),
        migrations.AddField(
            model_name="probemultievent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probemultievent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probemulti",
            ),
        ),
        migrations.AddField(
            model_name="probeoptedoutevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probeoptedoutevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probeoptedout",
            ),
        ),
        migrations.AddField(
            model_name="probetrackedevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probetrackedevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probetracked",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobe",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_plainprobeevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="3eec425c281220de3a63f52075e176bbf5618207",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_37628",
                    table="features_plainprobe",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobe",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "features_plainprobeevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id"); RETURN NULL;',
                    hash="f240894f2eac04440bb55bd5325781238a3e6b55",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_dc43e",
                    table="features_plainprobe",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobe",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_plainprobeevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="5cc6e711c242f4894467e11a4421736cc7d2e13d",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_dbb83",
                    table="features_plainprobe",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookup",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probelookupevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="485d88291bbf758b0e704a50105eb5644096fd4e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_66b25",
                    table="features_probelookup",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookup",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "features_probelookupevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="dc6a8aa88c4b3dbb93bff78c9d347bfb31604ae1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_e9bc4",
                    table="features_probelookup",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookup",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probelookupevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (OLD."code", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."probe_note"); RETURN NULL;',
                    hash="db8f922b244453cda50f6c050d2b038eb270f5b7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_1344e",
                    table="features_probelookup",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemulti",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probemultievent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="1a38e20ad328ea649505fab55d7c877031c216f8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_de138",
                    table="features_probemulti",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemulti",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "features_probemultievent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="c5c76349af78c7b14934471c0c839fc9be48a2e5",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c8462",
                    table="features_probemulti",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemulti",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probemultievent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."probe_note"); RETURN NULL;',
                    hash="ba337e833ced8082044f63f547fed608f71544cb",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_be036",
                    table="features_probemulti",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedout",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probeoptedoutevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."token"); RETURN NULL;',
                    hash="9aa759e1065928c9bcd3b8f869ad1bf7bde815f8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_225d3",
                    table="features_probeoptedout",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedout",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."formatted_name" IS DISTINCT FROM (NEW."formatted_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."token" IS DISTINCT FROM (NEW."token"))',
                    func='INSERT INTO "features_probeoptedoutevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."token"); RETURN NULL;',
                    hash="9bd09b469f97d85900ac6b92679bbca08114adf3",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d88fe",
                    table="features_probeoptedout",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedout",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probeoptedoutevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."token"); RETURN NULL;',
                    hash="0e9d91daa41f394eb6ee40463f5c4a2b5cc5d1f7",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_2275f",
                    table="features_probeoptedout",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetracked",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probetrackedevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note", "secret") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."probe_note", NEW."secret"); RETURN NULL;',
                    hash="873702dc1c118fa69354380b93d3a3d6624a2ca6",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_960bb",
                    table="features_probetracked",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetracked",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."formatted_name" IS DISTINCT FROM (NEW."formatted_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."probe_note" IS DISTINCT FROM (NEW."probe_note") OR OLD."secret" IS DISTINCT FROM (NEW."secret"))',
                    func='INSERT INTO "features_probetrackedevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note", "secret") VALUES (NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."probe_note", NEW."secret"); RETURN NULL;',
                    hash="1be4f0df6f72afe181ddbd96b0dba491bf6f9b05",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d3995",
                    table="features_probetracked",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetracked",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probetrackedevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note", "secret") VALUES (OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."probe_note", OLD."secret"); RETURN NULL;',
                    hash="cc26c2d9edbb8f05421dd03788b5f1d7963ad310",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a634b",
                    table="features_probetracked",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="42da3815852cef3780cc279c4427b331ebc1550d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_a69ff",
                    table="features_plainprobeevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookupevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="1e14cc7f86d6a8360fc7650af5abede05d007924",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_83e22",
                    table="features_probelookupevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemultievent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="550158f6882676e8b559b10010dea6e4270b2bbf",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_82935",
                    table="features_probemultievent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedoutevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="82704c19a62e775bd1571b5f9ca56f8a3741e4f9",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_431bb",
                    table="features_probeoptedoutevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetrackedevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="e366477da5afaa3b93104ae8fafa65d9d0504737",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_52c2e",
                    table="features_probetrackedevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
