# Generated by Django 6.1 on 2026-09-02 19:36

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("features", "0001_initial"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlainProbeEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeLookupEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("probe_note", models.CharField(blank=True, default="lookup", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeMultiEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("probe_note", models.CharField(blank=True, default="from-a", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeOptedOutEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("token", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbeTrackedEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("probe_note", models.CharField(blank=True, default="tracked", max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="probeoptedout",
            name="secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="probeoptedout",
            name="token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="probetracked",
            name="secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="probetracked",
            name="token",
            field=models.CharField(blank=True, max_length=255),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobe",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_plainprobeevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="99016f7a56961e0d7bf0e0ef174e3184df845b1c",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_37628",
                    table="features_plainprobe",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobe",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "features_plainprobeevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="b8937733959246092b77152e6c19307f50583b52",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_dc43e",
                    table="features_plainprobe",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobe",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_plainprobeevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="74d846b558e9eb446b373525ee70418434c8981a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_dbb83",
                    table="features_plainprobe",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookup",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probelookupevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="6b040fe725c76564dd898615e5cea4e7d71b3b22",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_66b25",
                    table="features_probelookup",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookup",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "features_probelookupevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."code", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="e09a693da2389fb7461154bbe34a42ea1dbd19eb",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_e9bc4",
                    table="features_probelookup",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookup",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probelookupevent" ("code", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (OLD."code", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."probe_note"); RETURN NULL;',
                    hash="b01d978f8120e945bfcb53ea2bfe025176b6c844",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_1344e",
                    table="features_probelookup",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemulti",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probemultievent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="eb5f0890dad423b11bad122c4aac786eba879b56",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_de138",
                    table="features_probemulti",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemulti",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "features_probemultievent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."probe_note"); RETURN NULL;',
                    hash="0893bbb25b0940c82239c91404f16e59f009b9ee",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c8462",
                    table="features_probemulti",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemulti",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probemultievent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."probe_note"); RETURN NULL;',
                    hash="7d81dacf9dbcabb7478fa4787ce70ba5aa987e60",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_be036",
                    table="features_probemulti",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedout",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probeoptedoutevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."token"); RETURN NULL;',
                    hash="a56f92b1b3273709504112aa5eaafbf50432df85",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_225d3",
                    table="features_probeoptedout",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedout",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."formatted_name" IS DISTINCT FROM (NEW."formatted_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."token" IS DISTINCT FROM (NEW."token"))',
                    func='INSERT INTO "features_probeoptedoutevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."token"); RETURN NULL;',
                    hash="6a3fddb1eaa456d484712a36bebffe8b6fa2f43a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d88fe",
                    table="features_probeoptedout",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedout",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probeoptedoutevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "token") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."token"); RETURN NULL;',
                    hash="e46ea13a300bbe47778d719c001afe905fb71da9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_2275f",
                    table="features_probeoptedout",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetracked",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probetrackedevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note", "secret") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."probe_note", NEW."secret"); RETURN NULL;',
                    hash="cc1a19dbfbf328d9663839d524fa98ef1c57daad",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_960bb",
                    table="features_probetracked",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetracked",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."formatted_name" IS DISTINCT FROM (NEW."formatted_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."probe_note" IS DISTINCT FROM (NEW."probe_note") OR OLD."secret" IS DISTINCT FROM (NEW."secret"))',
                    func='INSERT INTO "features_probetrackedevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note", "secret") VALUES (NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."probe_note", NEW."secret"); RETURN NULL;',
                    hash="1910c07ce5b456e5822a942d0dfdb6f6b09b6745",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d3995",
                    table="features_probetracked",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetracked",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "features_probetrackedevent" ("id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "probe_note", "secret") VALUES (OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."probe_note", OLD."secret"); RETURN NULL;',
                    hash="5b6bf7125be449fc9cfc363fa777445462439586",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_a634b",
                    table="features_probetracked",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="plainprobeevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="plainprobeevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.plainprobe",
            ),
        ),
        migrations.AddField(
            model_name="probelookupevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probelookupevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probelookup",
            ),
        ),
        migrations.AddField(
            model_name="probemultievent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probemultievent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probemulti",
            ),
        ),
        migrations.AddField(
            model_name="probeoptedoutevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probeoptedoutevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probeoptedout",
            ),
        ),
        migrations.AddField(
            model_name="probetrackedevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="probetrackedevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="features.probetracked",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="plainprobeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="42da3815852cef3780cc279c4427b331ebc1550d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_a69ff",
                    table="features_plainprobeevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probelookupevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="1e14cc7f86d6a8360fc7650af5abede05d007924",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_83e22",
                    table="features_probelookupevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probemultievent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="550158f6882676e8b559b10010dea6e4270b2bbf",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_82935",
                    table="features_probemultievent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probeoptedoutevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="82704c19a62e775bd1571b5f9ca56f8a3741e4f9",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_431bb",
                    table="features_probeoptedoutevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="probetrackedevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="e366477da5afaa3b93104ae8fafa65d9d0504737",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_52c2e",
                    table="features_probetrackedevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
