line-length = 120
target-version = "py311"
# Adds to the defaults excludes.
extend-exclude = [
    ".circleci",
    ".git",
    ".github",
    "server/tests/group_updating_bad_migrations/migrations/0003_group_permission_migrations_2026_06_29.py",
    "server/tests/workflow_updating_bad_migrations/migrations/0003_workflow_migrations_2026_06_29.py",
]
force-exclude = true

[lint]
select = [
    "A",
    "B0",
    "C4",
    "C90",
    "DJ",
    "E",
    "W",
    "F",
    "FIX",
    "G",
    "I",
    "INP",
    "N",
    "PLC",
    "PLE",
    "PLR2004",
    "Q",
    "RUF",
    "SIM",
    "T10",
    "T20",
    "TID",
    "UP",
]
ignore = [
    "E501",
    "F811",
    "FIX002",
    "PLC0415",
    "RUF005",
    "RUF012",
    "RUF021",
    "SIM105",
    "SIM108",
    "UP017",
]

[lint.per-file-ignores]
"server/tests/*" = [
    "DJ008",
    "SIM",
    "T201",
]
"server/vueda/__main__.py" = [
    "T201",
]
"scripts/*" = [
    "T201",
]

[lint.isort]
known-first-party = [
    "vueda",
    "tests",
]
force-single-line = true
lines-after-imports = 2

[lint.mccabe]
max-complexity = 20

[lint.flake8-tidy-imports]
ban-relative-imports = "all"
