# Generated by Django 5.0.4 on 2024-05-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_changed", "0003_workflow_migrations_2024_05_14"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    auth_permission
                    (
                        name,
                        content_type_id,
                        codename
                    )
                VALUES
                    (
                        'Can Do Another Thing',
                        (
                            SELECT
                                id
                            FROM
                                django_content_type
                            WHERE
                                app_label = 'workflow_changed'
                                AND model = 'workflowchanged'
                        ),
                        'can_do_another_thing'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
