# Generated by Django 5.0.4 on 2024-05-01 16:58

from django.conf import settings
from django.db import migrations
from django.utils.timezone import now


def create_system_user(apps, scheme_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.create(
        password="",
        is_superuser=True,
        is_active=True,
        email="system_user@example.com",
        name="System User",
        date_joined=now(),
        is_system=True,
    )


def delete_system_user(apps, scheme_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.filter(
        email="system_user@example.com",
        name="System User",
        is_system=True,
    ).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_system_user, reverse_code=delete_system_user),
    ]
