# Generated by Django 5.0.6 on 2024-07-08 16:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vueda_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChange",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_name", models.CharField(blank=True, max_length=100)),
                ("group_name_old", models.CharField(blank=True, max_length=100)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("added", "added"),
                            ("associated", "associated"),
                            ("changed", "changed"),
                            ("unassociated", "unassociated"),
                            ("deleted", "deleted"),
                        ],
                        max_length=100,
                    ),
                ),
                ("when", models.DateTimeField(auto_now=True)),
                ("historical_permission_codename", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_app_label", models.CharField(blank=True, max_length=100)),
                ("historical_permission_content_type_model_name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "group_change",
                "verbose_name_plural": "group_changes",
            },
        ),
    ]
