# Generated by Django 5.2.7 on 2025-10-29 23:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mfa", "0003_authenticator_type_uniq"),
        ("vueda_user", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("sms", "Phone SMS"),
                            ("email", "Email"),
                            ("totp", "Time Based Key from an Authenticator App"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "authenticator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device",
                        to="mfa.authenticator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "totp_devices",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("authenticator", "method", "user"),
                        name="uniq_authenticator_method_user",
                    )
                ],
            },
        ),
    ]
