# Generated by Django 5.2.11 on 2026-03-13 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_user", "0003_totpdevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="totpdevice",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "totp_devices",
                "ordering": ["method"],
            },
        ),
    ]
