# Generated by Django 5.2.11 on 2026-04-21 00:00

from django.core.management import call_command
from django.db import migrations
from django.db import models


def sync_group_changes(apps, schema_editor):
    call_command("sync_group_changes")


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_user", "0004_alter_totpdevice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchange",
            name="when",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(sync_group_changes, migrations.RunPython.noop),
    ]
