# Generated by Django 5.2.15 on 2026-06-29 20:25

from django.db import migrations


def move_list_permission(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    try:
        auth_permission_ct = ContentType.objects.get(app_label="auth", model="permission")
    except ContentType.DoesNotExist:
        return

    list_perm = Permission.objects.filter(codename="list_permission").exclude(content_type=auth_permission_ct)
    if list_perm.exists():
        perm = list_perm.get()
        perm.content_type = auth_permission_ct
        perm.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("vueda_user", "0005_sync_group_changes"),
    ]

    operations = [
        migrations.RunPython(move_list_permission, migrations.RunPython.noop, elidable=True),
    ]
