# Generated by Django 6.1 on 2026-09-02 19:36

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mfa", "0003_authenticator_type_uniq"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("vueda_user", "0005_sync_group_changes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPDeviceEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("sms", "Phone SMS"),
                            ("email", "Email"),
                            ("totp", "Time Based Key from an Authenticator App"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="totpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_user_totpdeviceevent" ("authenticator_id", "email", "id", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "user_id") VALUES (NEW."authenticator_id", NEW."email", NEW."id", NEW."method", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone_number", NEW."user_id"); RETURN NULL;',
                    hash="1e6c1948f8ec11edf0935d331be660fd186de554",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_f6db1",
                    table="vueda_user_totpdevice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="totpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_user_totpdeviceevent" ("authenticator_id", "email", "id", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "user_id") VALUES (NEW."authenticator_id", NEW."email", NEW."id", NEW."method", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone_number", NEW."user_id"); RETURN NULL;',
                    hash="993423b1b8325e6cdd76f491ae87b95230453baa",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_e5ade",
                    table="vueda_user_totpdevice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="totpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_user_totpdeviceevent" ("authenticator_id", "email", "id", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "user_id") VALUES (OLD."authenticator_id", OLD."email", OLD."id", OLD."method", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone_number", OLD."user_id"); RETURN NULL;',
                    hash="52126f5eb4d011f78bf15f596b9a90126d55bbbe",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_9ee6b",
                    table="vueda_user_totpdevice",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="totpdeviceevent",
            name="authenticator",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="mfa.authenticator",
            ),
        ),
        migrations.AddField(
            model_name="totpdeviceevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="totpdeviceevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_user.totpdevice",
            ),
        ),
        migrations.AddField(
            model_name="totpdeviceevent",
            name="user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="totpdeviceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="89071d019861ffe6993eb22a0a78e59baf84d6b4",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d8243",
                    table="vueda_user_totpdeviceevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
