# Generated by Django 6.1 on 2026-09-02 19:36

import django.contrib.postgres.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("available_for_sale", models.BooleanField(db_default=True)),
                (
                    "buzz_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255), null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="product",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "product_productevent" ("available_for_sale", "buzz_words", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."available_for_sale", NEW."buzz_words", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="a353a04cf272fc85c9c6881f17a8814bcf278aef",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_b0648",
                    table="product_product",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="product",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "product_productevent" ("available_for_sale", "buzz_words", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."available_for_sale", NEW."buzz_words", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="5fd74de31e59a8ea3933d58179d98e4024009912",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_57ecc",
                    table="product_product",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="product",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "product_productevent" ("available_for_sale", "buzz_words", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."available_for_sale", OLD."buzz_words", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="468aa92122178e7145e5bcf6078d7f9b3013376b",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_7462c",
                    table="product_product",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="productevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="productevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="product.product",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="productevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="45188cd524c038333e1c5b836f663cfaf832cb02",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ed20c",
                    table="product_productevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
