# Generated by Django 6.1 on 2026-09-10 17:29

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_delete_historicalproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCascadeOrderedByFormattedName",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["formatted_name"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ProductCascadeOwner",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.AlterModelOptions(
            name="productmodelorderinglookupformattedname",
            options={
                "base_manager_name": "objects",
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ["formatted_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCascadeOrderedNote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "ordered_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="product.productcascadeorderedbyformattedname",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.AddField(
            model_name="productcascadeorderedbyformattedname",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_rows",
                to="product.productcascadeowner",
            ),
        ),
    ]
