"""Monkey-patches Django permission codenames to use CRUDL naming conventions."""

__all__ = ()

# Must be imported in your project settings.py in order for things
# to get patched before they are used to create permissions.

# Patch get_permission_codename, so that it converts add, view, and change into create, read and update respectively.
# This appears to be the only way we can change the history table permissions, without patching more things.
from django.conf import settings
from django.contrib import auth
from django.core.signals import setting_changed


auth.django_get_permission_codename = auth.get_permission_codename

# Cache PERMISSION_NAMES_MAPPING so the hot path of every permission check doesn't hit
# Django's settings lookup, but keep the cache stale-free by clearing it on setting_changed.
# This lets override_settings(PERMISSION_NAMES_MAPPING=...) reach get_permission_codename
# and get_builtin_permissions immediately, unlike binding the mapping to a module global at import.
_permission_names_mapping_cache = None


def get_permission_names_mapping():
    """Return PERMISSION_NAMES_MAPPING, read at call time and cached until the setting changes."""
    global _permission_names_mapping_cache
    if _permission_names_mapping_cache is None:
        _permission_names_mapping_cache = settings.PERMISSION_NAMES_MAPPING
    return _permission_names_mapping_cache


def _clear_permission_names_mapping_cache(*, setting, **kwargs):
    if setting == "PERMISSION_NAMES_MAPPING":
        global _permission_names_mapping_cache
        _permission_names_mapping_cache = None


setting_changed.connect(_clear_permission_names_mapping_cache)


def get_permission_codename(action, opts):
    """
    Return the codename of the permission for the specified action, in the crud style.
    add = create
    view = read
    change = update
    delete doesn't change
    list is new
    """
    action = get_permission_names_mapping().get(action, action)
    return auth.django_get_permission_codename(action, opts)


auth.get_permission_codename = get_permission_codename


# Patch get_builtin_permissions, so that it converts add, view, and change into create, read and update respectively.
# This appears to be the only way we can change the history table permissions, without patching more things.
from django.contrib.auth import management  # noqa E402


def get_builtin_permissions(opts):
    """
    Return (codename, name) for all autogenerated permissions, in the crud style.
    add = create
    view = read
    change = update
    delete doesn't change
    list is new

    This is a customized django function, since we need to update the action name within a loop.
    https://github.com/django/django/blob/f302343380c77e1eb5dab3b64dd70895a95926ca/django/contrib/auth/management/__init__.py#L22-L35
    """
    permission_names_mapping = get_permission_names_mapping()
    perms = []
    for action in opts.default_permissions:
        action = permission_names_mapping.get(action, action)
        perm = (
            get_permission_codename(action, opts),
            f"Can {action} {opts.verbose_name_raw}",
        )
        # Make sure we don't add the same perm in the list twice, which can happen if older sites map list to view.
        # create_permissions in django would then try to create the
        # same permission twice, and get a duplicate key violation.
        if perm not in perms:
            perms.append(perm)
    return perms


management._get_builtin_permissions = get_builtin_permissions


# Patch Options.__init__ to inject "list" into default_permissions for every model.
# This runs before any model modules are imported (patch_django is imported from settings.py),
# so it covers all models including third-party ones. Models that explicitly declare
# default_permissions in their Meta override this via contribute_to_class, so VuedaModel
# and any model that opts out of "list" are unaffected.
from django.db.models.options import Options as _Options  # noqa E402

_original_options_init = _Options.__init__


def _patched_options_init(self, meta, app_label=None):
    _original_options_init(self, meta, app_label)
    if "list" not in self.default_permissions:
        self.default_permissions = self.default_permissions + ("list",)


_Options.__init__ = _patched_options_init


# We also need to patch the perms_map in vueda\core\permissions.py and
# vueda\workflow\permissions.py, if the permissions are not set to the default.
# This selects which further patches apply, so it must run at import time, before
# permissions are created. Unlike get_permission_codename and get_builtin_permissions
# above, this decision does not move to call time; it reads the setting once here.
permission_names_mapping = settings.PERMISSION_NAMES_MAPPING

if (
    "add" not in permission_names_mapping
    and "add" in permission_names_mapping.values()
    or "change" not in permission_names_mapping
    and "change" in permission_names_mapping.values()
    or "view" not in permission_names_mapping
    and "view" in permission_names_mapping.values()
):
    from vueda.core.permissions import ObjectPermissions

    if "vueda.workflow" in settings.INSTALLED_APPS:
        from vueda.workflow.permissions import WorkflowObjectPermissions

if "add" not in permission_names_mapping and "add" in permission_names_mapping.values():
    ObjectPermissions.perms_map["POST"] = ["%(app_label)s.add_%(model_name)s"]
    if "vueda.workflow" in settings.INSTALLED_APPS:
        WorkflowObjectPermissions.perms_map["POST"] = ["%(app_label)s.add_%(model_name)s"]

if "change" not in permission_names_mapping and "change" in permission_names_mapping.values():
    ObjectPermissions.perms_map["PUT"] = ["%(app_label)s.change_%(model_name)s"]
    ObjectPermissions.perms_map["PATCH"] = ["%(app_label)s.change_%(model_name)s"]
    if "vueda.workflow" in settings.INSTALLED_APPS:
        WorkflowObjectPermissions.perms_map["PUT"] = ["%(app_label)s.change_%(model_name)s"]
        WorkflowObjectPermissions.perms_map["PATCH"] = ["%(app_label)s.change_%(model_name)s"]

if "view" not in permission_names_mapping and "view" in permission_names_mapping.values():
    ObjectPermissions.perms_map["GET"] = ["%(app_label)s.view_%(model_name)s"]
    if "vueda.workflow" in settings.INSTALLED_APPS:
        WorkflowObjectPermissions.perms_map["GET"] = ["%(app_label)s.view_%(model_name)s"]
