version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  detect-code-changes:
    jobs:
      - path-filtering/filter:
          name: detect-code-changes
          mapping: |
              client/.* run-client-workflows true .circleci/client.yml
              server/.* run-server-workflows true .circleci/server.yml
          base-revision: v2.x.x
          config-path: .circleci/no-changes.yml
          filters:
            tags:
              only:
                - /.*/
