# Generated by Django 5.2.8 on 2025-11-25 20:04
from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_initial_state")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


def create_objects(apps, schema_editor):
    WorkflowInitialState = apps.get_model("workflow_initial_state", "WorkflowInitialState")

    WorkflowInitialState.objects.create(name="Test1")
    WorkflowInitialState.objects.create(name="Test2")
    WorkflowInitialState.objects.create(name="Test3")
    WorkflowInitialState.objects.create(name="Test4")
    WorkflowInitialState.objects.create(name="Test5")


def delete_objects(apps, schema_editor):
    WorkflowInitialState = apps.get_model("workflow_initial_state", "WorkflowInitialState")

    WorkflowInitialState.objects.get(name="Test1").delete()
    WorkflowInitialState.objects.get(name="Test2").delete()
    WorkflowInitialState.objects.get(name="Test3").delete()
    WorkflowInitialState.objects.get(name="Test4").delete()
    WorkflowInitialState.objects.get(name="Test5").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_initial_state", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_objects, reverse_code=delete_objects),
    ]
