# Generated by Django 5.2.8 on 2025-11-25 20:42
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_initial_state", "0002_create_objects"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflow
            (
                code,
                name,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'initial_state_workflow_test',
                'Initial State Workflow Test',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_initial_state' AND
                        model = 'workflowinitialstate'
                ),
                'workflow_initial_state',
                'workflowinitialstate'
            );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_workflow
            WHERE
                code = 'initial_state_workflow_test';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_state
                (
                    code,
                    name,
                    workflow_id
                )
            VALUES
                (
                    'first',
                    'First',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                ),
                (
                    'second',
                    'Second',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                ),
                (
                    'third',
                    'Third',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                ),
                (
                    'fourth',
                    'Fourth',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_state
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'initial_state_workflow_test'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'first'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'initial_state_workflow_test'
                                )
                        )
                    );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_objectstate
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );
            DELETE FROM
                vueda_workflow_initialstate
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
        ),
    ]
