# Generated by Django 5.2.8 on 2025-11-25 20:42
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_initial_state", "0002_create_objects"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflow
            (
                code,
                name,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'initial_state_workflow_test',
                'Initial State Workflow Test',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_initial_state' AND
                        model = 'workflowinitialstate'
                ),
                'workflow_initial_state',
                'workflowinitialstate'
            );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_workflow
            WHERE
                code = 'initial_state_workflow_test';""",
        ),
        migrations.RunSQL(
            sql="""
            WITH USER_SYSTEM AS (
                SELECT
                    id
                FROM
                    employee_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflow
            (
                id,
                code,
                name,
                historical_app_label,
                historical_model,
                history_date,
                history_change_reason,
                history_type,
                content_type_id,
                history_relation_id,
                history_user_id
            )
            SELECT
                W.id,
                W.code,
                W.name,
                W.historical_app_label,
                W.historical_model,
                '2025-11-25 13:11:30.000000-06',
                'Migration - 0003_create_workflow_and_history',
                '+',
                W.content_type_id,
                W.id,
                USER_SYSTEM.id
            FROM
                vueda_workflow_workflow W,
                USER_SYSTEM
            WHERE
                W.code = 'initial_state_workflow_test';""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_historicalworkflow
            WHERE
                code = 'initial_state_workflow_test';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_state
                (
                    code,
                    name,
                    workflow_id
                )
            VALUES
                (
                    'first',
                    'First',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                ),
                (
                    'second',
                    'Second',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                ),
                (
                    'third',
                    'Third',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                ),
                (
                    'fourth',
                    'Fourth',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'initial_state_workflow_test'
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_state
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            WITH USER_SYSTEM AS (
                SELECT
                    id
                FROM
                    employee_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalstate
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                workflow_id
            )
            SELECT
                S.id,
                S.code,
                S.name,
                '2025-11-25 13:17:10.000000-06',
                'Migration - 0003_create_workflow_and_history',
                '+',
                S.id,
                USER_SYSTEM.id,
                S.workflow_id
            FROM
                vueda_workflow_state S,
                USER_SYSTEM
            WHERE
                S.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_historicalstate
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'initial_state_workflow_test'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'first'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'initial_state_workflow_test'
                                )
                        )
                    );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_objectstate
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );
            DELETE FROM
                vueda_workflow_initialstate
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            WITH USER_SYSTEM AS (
                SELECT
                    id
                FROM
                    employee_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalinitialstate
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                state_id,
                workflow_id
            )
            SELECT
                I.id,
                '2025-11-25 13:20:30.000000-06',
                'Migration - 0003_create_workflow_and_history',
                '+',
                I.id,
                USER_SYSTEM.id,
                (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'first'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'initial_state_workflow_test'
                        )
                ) AS state_id,
                I.workflow_id
            FROM
                vueda_workflow_initialstate I,
                USER_SYSTEM
            WHERE
                I.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                )
                AND
                I.state_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'first'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'initial_state_workflow_test'
                        )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_historicalinitialstate
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'initial_state_workflow_test'
                );""",
        ),
    ]
