version: 2.1
orbs:
    github: arrai/github@3.0.0
    pypi: arrai/pypi@3.1.0
    pytest: arrai/pytest@8.1.5
    ruff: arrai/ruff@1.0.0
    safety: arrai/safety@4.0.0
    utils: arrai/utils@1.16.3
executors:
    base:
        docker:
            - image: cimg/base:current
    python311:
        docker:
            - image: cimg/python:3.11
            - image: cimg/postgres:15.12
            - image: cimg/redis:6.2
    python311-base:
        docker:
            - image: cimg/python:3.11
jobs:
    build:
        executor: python311-base
        resource_class: small
        steps:
            - checkout
            - run:
                  name: Verify Git Tag Matches Python Version
                  command: |
                      GIT_TAG=$(git describe --tags --exact-match 2>/dev/null)

                      if [ $? -ne 0 ]; then
                        echo "No exact match Git tag found."
                        exit 1
                      fi

                      PYTHON_VERSION=$(python -c "import vueda; print(vueda.__version__)")

                      if [ "$GIT_TAG" == "v$PYTHON_VERSION" ]; then
                        echo "Git tag matches the Python version: $GIT_TAG"
                        exit 0
                      else
                        echo "Git tag ($GIT_TAG) does not match the Python version ($PYTHON_VERSION)."
                        exit 1
                      fi
            - run:
                  name: Build Package
                  command: |
                      pip install --user --upgrade build
                      python -m build --wheel
            - save_cache:
                  paths:
                      - ~/project/dist
                  key: build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
    run_pipeline:
        parameters:
            vcs:
                type: enum
                enum: [bitbucket, github]
                default: github
            org:
                type: string
                default: ${CIRCLE_PROJECT_USERNAME}
            project:
                type: string
            token:
                type: string
                default: ${CIRCLECI_API_TOKEN}
        executor: base
        resource_class: small
        steps:
            - run:
                  name: Run Pipeline
                  command: |
                      curl --location \
                           --request POST "https://circleci.com/api/v2/project/<<parameters.vcs>>/<<parameters.org>>/<<parameters.project>>/pipeline" \
                           --header 'Content-Type: application/json' \
                           --user "<<parameters.token>>:"
workflows:
    test:
        jobs:
            - pytest/pytest:
                  name: pytest
                  executor: python311
                  context: arrai-global
                  pipenv_cache_key_version: "2"
                  config:
                      - run:
                            name: Copy config
                            command: cp .env.circleci .env.local
                  filters: # filters required since `build_*` has filters
                      branches:
                          only: /.*/
                      tags:
                          only: /.*/
            - run_pipeline:
                  name: run-sems-server-pipeline-main
                  requires:
                      - pytest
                  project: sems-server
                  filters:
                      branches:
                          only:
                              - main

            - run_pipeline:
                  name: run-wayfinders-server-pipeline-main
                  requires:
                      - pytest
                  project: wayfinders-server
                  filters:
                      branches:
                          only:
                              - main
            # todo: docs?
            - build:
                  name: build
                  requires:
                      - pytest
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - github/create_release:
                  name: release_on_github
                  context: arrai-global
                  requires:
                      - build
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - pypi/upload_release:
                  name: publish
                  context: arrai-private-package-publishing
                  cache_key: build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
                  requires:
                      - build
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - run_pipeline:
                  name: run-sems-server-pipeline-tag
                  requires:
                      - publish
                  project: sems-server
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - run_pipeline:
                  name: run-wayfinders-server-pipeline-tag
                  requires:
                      - publish
                  project: wayfinders-server
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
    lint:
        jobs:
            - ruff/ruff_fixed_ip:
                  name: ruff
                  context: arrai-global
                  executor: python311-base
                  filters:
                      branches:
                          only:
                              - main
            - ruff/ruff:
                  name: ruff-no-badge
                  executor: python311-base
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
    audit:
        jobs:
            - safety/safety_fixed_ip:
                  name: safety
                  context: arrai-global
                  executor: safety/python311
                  filters:
                      branches:
                          only:
                              - main
            - safety/safety:
                  name: safety-no-badge
                  context: arrai-global
                  executor: safety/python311
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
