version: 2.1
orbs:
    flake8: arrai/flake8@20.0.0
    github: arrai/github@3.0.0
    pytest: arrai/pytest@8.0.1
    safety: arrai/safety@3.0.1
    utils: arrai/utils@1.10.0
executors:
    base:
        docker:
            - image: cimg/base:current
    python311:
        docker:
            - image: cimg/python:3.11
            - image: cimg/postgres:15.5
            - image: cimg/redis:6.2
    python311-base:
        docker:
            - image: cimg/python:3.11
workflows:
    test:
        jobs:
            - pytest/pytest:
                  name: pytest
                  executor: python311
                  context: arrai-global
                  pipenv_cache_key_version: "2"
                  presetup:
                      - run:
                            name: Testing
                            command: |
                                which pipenv
                                pipenv --version
                  filters: # filters required since `build_*` has filters
                      branches:
                          only: /.*/
                      tags:
                          only: /.*/
    lint:
        jobs:
            - flake8/flake8_pipenv:
                  name: flake8
                  context: arrai-global
                  executor: python311-base
                  flake8_cmd: pflake8
                  filters:
                      branches:
                          only:
                              - main
                  wd: ./
            - flake8/flake8_pipenv:
                  name: flake8-no-badge
                  executor: python311-base
                  flake8_cmd: pflake8
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
                  wd: ./
    audit:
        jobs:
            - safety/safety:
                  name: safety
                  context: arrai-global
                  executor: safety/python311
                  filters:
                      branches:
                          only:
                              - main
            - safety/safety:
                  name: safety-no-badge
                  context: arrai-global
                  executor: safety/python311
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
