export * from "./WidgetCheckbox.vue";
export * from "./WidgetHtml.vue";
export * from "./WidgetInput.vue";
export * from "./WidgetRadio.vue";
export * from "./WidgetSelect.vue";
export * from "./WidgetTextarea.vue";
export { default as WidgetCheckbox } from "./WidgetCheckbox.vue";
export { default as WidgetHtml } from "./WidgetHtml.vue";
export { default as WidgetInput } from "./WidgetInput.vue";
export { default as WidgetRadio } from "./WidgetRadio.vue";
export { default as WidgetSelect } from "./WidgetSelect.vue";
export { default as WidgetTextarea } from "./WidgetTextarea.vue";
