# Generated by Django 5.2.15 on 2026-06-29 18:51
# Modified using VUEDA makegroupmigrations command.  Please do not delete this comment.
from django.db import migrations


changed_data = [


class Migration(migrations.Migration):
    dependencies = [
        ("group_updating_bad_migrations", "0002_group_permission_migrations_2026_06_29"),
    ]

    operations = []
