# Generated by Django 5.0.2 on 2024-02-20 17:03

import django.contrib.auth.models
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.contrib.postgres.operations import CreateCollation
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations
from django.db import models

import vueda.user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "email",
                    models.EmailField(
                        db_collation="case_insensitive", max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("email"), output_field=models.CharField()
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("is_system", models.BooleanField(default=False, verbose_name="system")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "users",
                "ordering": ("-date_joined",),
            },
            managers=[
                ("objects", vueda.user.models.VUEDAUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_number", models.CharField(max_length=255)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            models.F("employee_number"), output_field=models.CharField()
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "employees",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("employee_number", models.CharField(max_length=255)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            models.F("employee_number"), output_field=models.CharField()
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="tests.employee",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical employee",
                "verbose_name_plural": "historical employees",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tests.employee")),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_supervisors",
                        to="tests.employee",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Value(" on "),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("period_start"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_start"), "month"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_start"), "day"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                            models.Value(" to "),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("period_end"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_end"), "month"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_end"), "day"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheets",
                "ordering": ["period_start", "employee__employee_number"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTimesheet",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tests.employee",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Value(" on "),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("period_start"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_start"), "month"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_start"), "day"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                            models.Value(" to "),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("period_end"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_end"), "month"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                            models.Value("/"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    django.db.models.functions.datetime.Extract(models.F("period_end"), "day"),
                                    output_field=models.CharField(),
                                ),
                                2,
                                models.Value("0"),
                            ),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tests.employee",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="tests.timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical timesheet",
                "verbose_name_plural": "historical timesheets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tests.timesheet")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                                output_field=models.CharField(),
                            ),
                            models.Value(" - "),
                            django.db.models.functions.comparison.Cast(
                                models.F("hours"), output_field=models.CharField()
                            ),
                            models.Value(" hours"),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheet_entries",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTimesheetEntry",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                                output_field=models.CharField(),
                            ),
                            models.Value(" - "),
                            django.db.models.functions.comparison.Cast(
                                models.F("hours"), output_field=models.CharField()
                            ),
                            models.Value(" hours"),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tests.timesheet",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="tests.timesheetentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical timesheet entry",
                "verbose_name_plural": "historical timesheet entrys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("available_for_sale", models.BooleanField(db_default=True)),
                (
                    "buzz_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255), null=True, size=None
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("available_for_sale", models.BooleanField(db_default=True)),
                (
                    "buzz_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255), null=True, size=None
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="tests.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        TrigramExtension(),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["email"], name="gin_email_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="gin_name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
