# Generated by Django 5.0.2 on 2024-03-05 20:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "employees",
            },
        ),
        migrations.AlterModelOptions(
            name="timesheet",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheets",
            },
        ),
        migrations.AddField(
            model_name="historicaltimesheet",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tests.employee",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheet_supervisors",
                to="tests.employee",
            ),
        ),
    ]
