# Generated by Django 5.0.2 on 2024-03-07 21:53

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0003_product_alter_timesheetentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="buzz_words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="buzz_words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255), null=True, size=None
            ),
        ),
    ]
