# Generated by Django 5.0.3 on 2024-06-13 21:27

from django.db import migrations

import vueda.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_historicalproduct_buzz_words_product_buzz_words"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", vueda.user.models.VUEDAUserManager()),
            ],
        ),
    ]
