# Generated by Django 5.0.7 on 2024-07-29 19:20

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tests", "0005_alter_user_managers"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["email"], name="gin_email_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="gin_name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
