# Generated by Django 5.0.6 on 2024-06-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "permissions": [
                    ("read_permission", "Can read permissions"),
                ],
            },
        ),
    ]
