# Generated by Django 5.1 on 2024-08-16 17:16

import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0006_user_gin_email_idx_user_gin_name_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="formatted_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    models.F("employee_number"), output_field=models.CharField()
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="formatted_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Cast(
                    models.F("employee_number"), output_field=models.CharField()
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="formatted_name",
            field=models.GeneratedField(db_persist=True, expression=models.F("name"), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name="historicaltimesheet",
            name="formatted_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    models.Value(" on "),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("period_start"), "year"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_start"), "month"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_start"), "day"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                    models.Value(" to "),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("period_end"), "year"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_end"), "month"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_end"), "day"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="historicaltimesheetentry",
            name="formatted_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                        output_field=models.CharField(),
                    ),
                    models.Value(" - "),
                    django.db.models.functions.comparison.Cast(models.F("hours"), output_field=models.CharField()),
                    models.Value(" hours"),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="formatted_name",
            field=models.GeneratedField(db_persist=True, expression=models.F("name"), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="formatted_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    models.Value(" on "),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("period_start"), "year"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_start"), "month"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_start"), "day"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                    models.Value(" to "),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("period_end"), "year"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_end"), "month"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                    models.Value("/"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.datetime.Extract(models.F("period_end"), "day"),
                            output_field=models.CharField(),
                        ),
                        2,
                        models.Value("0"),
                    ),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="formatted_name",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.text.Concat(
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                        output_field=models.CharField(),
                    ),
                    models.Value("/"),
                    django.db.models.functions.comparison.Cast(
                        django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                        output_field=models.CharField(),
                    ),
                    models.Value(" - "),
                    django.db.models.functions.comparison.Cast(models.F("hours"), output_field=models.CharField()),
                    models.Value(" hours"),
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="formatted_name",
            field=models.GeneratedField(db_persist=True, expression=models.F("email"), output_field=models.CharField()),
        ),
    ]
