# Test-related configurations
TIME_ZONE = "America/Edmonton"
ALLOWED_HOSTS = "demo.vueda.dev"
CSRF_TRUSTED_ORIGINS = "https://demo.vueda.dev"
SECRET_KEY = "test-secret-key"
DATABASE_URL = "postgresql://vueda@/vueda"
TEST_POSTGRES_DB = "dbname=postgres user=postgres"
DATABASE_BACKUP_DIR = ""
STATIC_ROOT = ""
STATICFILES_DIRS = ""
AUTH_USER_MODEL = "tests.User"
CORS_ALLOWED_ORIGINS = "https://demo.vueda.dev"
MAILGUN_API_KEY = ""
MAILGUN_SENDER_DOMAIN = ""
MAILGUN_WEBHOOK_SIGNING_KEY = ""
ANYMAIL_WEBHOOK_SECRET = ""
FRONTEND_DOMAIN = ""
FRONTEND_RESET_URL = ""
FRONTEND_LOGIN_URL = ""
SUPPORT_EMAIL = ""
SITE_NAME = ""
