[build-system]
requires = ["setuptools>=69.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vueda"
description = """\
Vue.js User Experience for Django Administration (VUEDA) - Server Library

`vueda-server`, the counterpart to `vueda-client`, is designed for projects that
integrate Vue.js frontends with Django REST Framework backends. This server
library enhances Django's native authentication and permissions systems
with default DRF classes and optimizes integration with `django-filters`,
`drf-flex-fields`, and `drf-writable-nested`. It offers essential out-of-the-box
functionalities such as custom workflow management, audit trails (with DRF
support for `django-simple-history`), and both row-level and field-level
permissions. Additionally, `vueda-server` provides DRF classes to expose Django
model details to the frontend, filtered by user permissions. It is built with
customization in mind, offering most features as base classes that can be
extended in your application, ensuring both control and adaptability.
"""
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "Arrai Innovations", email = "support@arrai.com" }
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: BSD License",
    "License :: OSI Approved :: The 3-Clause BSD License (BSD-3-Clause)",
    "Environment :: Console",
    "Framework :: Django",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
]
dynamic = ["dependencies", "version"]

[project.urls]
repository = "https://github.com/arrai-innovations/vueda-server/"

[project.scripts]
vueda = "vueda.__main__:main"

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
"*" = ["*.css", "*.html", "*.jinja2", "*.js", "*.sql"]

[tool.setuptools.packages.find]
include = ["vueda*"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
version = { attr = "vueda.__version__" }

[tool.flake8]
enable-extensions='G' # Enables flake8-logging-format
exclude = ".git,*/static/CACHE/*,docs,node_modules,*venv*"
per-file-ignores = """
*/migrations/*: I100, IS001, N806, I201
"""
extend-ignore = [
    # (flake8-builtins) builtin names used as class attributes (e.g. `id`, `type`, `help`)
    "A003",
    # (flake8) Black incompatibility - see https://github.com/PyCQA/pycodestyle/issues/373
    "E203",
    # (flake8-logging-format) false-positives for anything calling `.warn()`
    "G010",
    # (flake8-fixme) "hack" comments
    "T103",
    # we are already covered by F401, thanks.
    "F811",
    # T002 Python 2.x reserved word print used.
    # do not care if stuff works on python 2
    "T002",
    # let black handle long lines
    "E501",
    # allow print in scripts, pre-file-ignores does not work
    "T201"
]
max-complexity = 20
max-line-length = 120
# flake8-import-order
application-import-names = [
    "vueda",
    "tests"
]
import-order-style = 'pycharm'
# pep8-naming
ignore-names = [
    # defaults
    'setUp',
    'tearDown',
    'setUpClass',
    'tearDownClass',
    'setUpTestData',
    'failureException',
    'longMessage',
    'maxDiff',
    # custom (ideally, we'd want "assert*")
]
# not sure the format, but this does not work
# pre-file-ignores = """
#    vueda/update.py:
#    vueda/__main__.py:T201
# """

[tool.pycodestyle]
max-line-length = 120
exclude = ".git,*/static/CACHE/*,docs,node_modules,*venv*"

[tool.black]
line-length = 120

[tool.coverage.run]
branch = true
parallel = true
concurrency = ["multiprocessing"]
source = ["./vueda"]
omit = [
    "*/migrations/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "except ImportError",
    "raise ImportError"
]

[tool.pylint.master]
load-plugins = ['pylint_django']

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = ['missing-docstring', 'invalid-name']

[tool.pylint.design]
max-parents = 13

[tool.pylint.typecheck]
generated-members = ['REQUEST', 'acl_users', 'aq_parent', "[a-zA-Z]+_set{1,2}", 'save', 'delete']

[tool.pytest.ini_options]
django_find_project = false
pythonpath = ["."]
DJANGO_SETTINGS_MODULE = "tests.settings"
addopts = "--ds=tests.settings --create-db"
testpaths = ["tests"]
python_files = [
    "test_*.py"
]
filterwarnings = [
    "ignore:Passing None for the middleware get_response argument is deprecated:DeprecationWarning",
    "ignore:The providing_args argument is deprecated:DeprecationWarning",
    "ignore:.*You can remove default_app_config:PendingDeprecationWarning",
    "ignore:Model observation with save points is unsupported and will result in unexpected beauvoir."
]

[tool.isort]
multi_line_output = 3
force_single_line = true
force_grid_wrap = false
lines_after_imports = 2
line_length = 120

# Add application import names to the first-party section
known_first_party = ["vueda", "tests"]
