# Generated by Django 5.1.5 on 2025-04-08 21:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReleaseNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("notes", models.TextField(default="")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
