# Generated by Django 6.1 on 2026-09-03 16:30

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("vueda_release", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseNoteEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("title", models.CharField(default="", max_length=255)),
                ("notes", models.TextField(default="")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="releasenote",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_release_releasenoteevent" ("date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."date", NEW."id", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."title"); RETURN NULL;',
                    hash="74a66ed0370a1d8c4105c1d22acdc48a116efe30",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_45805",
                    table="vueda_release_releasenote",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="releasenote",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_release_releasenoteevent" ("date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."date", NEW."id", NEW."notes", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."title"); RETURN NULL;',
                    hash="9ef08ebb7caf4673c9fb23d6cef202cb5dffb14a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_5bb6c",
                    table="vueda_release_releasenote",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="releasenote",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_release_releasenoteevent" ("date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (OLD."date", OLD."id", OLD."notes", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."title"); RETURN NULL;',
                    hash="56581b999818076e21d0bb7d3207e1a85f9e55ad",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_f5a12",
                    table="vueda_release_releasenote",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="releasenoteevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="releasenoteevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_release.releasenote",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="releasenoteevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="64d24b9cc0753da3d0d9bfe10b08ddc71bd0a789",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_595c1",
                    table="vueda_release_releasenoteevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
