# Generated by Django 5.1.2 on 2025-01-14 19:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogRecords",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("process_id", models.IntegerField()),
                ("traceback", models.TextField()),
            ],
            options={
                "verbose_name": "Log record",
                "verbose_name_plural": "Log records",
            },
        ),
    ]
