# Generated by Django 5.0.4 on 2024-06-11 22:10

import django.db.models.deletion
from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.db import models


def make_sure_permissions_exist(apps, schema_editor):
    for app_name in ("vueda_workflow", "workflow_added"):
        app = django_apps.get_app_config(app_name)
        create_permissions(app, interactive=False)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0001_initial"),
        ("vueda_workflow", "__latest__"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowAdded",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "permissions": (
                    ("can_do_something", "Can do something"),
                    ("can_do_something_else", "Can do something else"),
                ),
            },
        ),
        migrations.CreateModel(
            name="HistoricalWorkflowAdded",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="workflow_added.workflowadded",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical workflow added",
                "verbose_name_plural": "historical workflow addeds",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(models.Model,),
        ),
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group
                (
                    name
                )
            VALUES
                (
                    'WorkflowAddedAdmin'
                ),
                (
                    'WorkflowAddedWorker'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group
            WHERE
                name IN ('WorkflowAddedAdmin', 'WorkflowAddedWorker');""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group_permissions
                (
                    group_id,
                    permission_id
                )
            VALUES
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowAddedAdmin'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id IN (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                            )
                    )
                ),
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowAddedWorker'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id IN (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group_permissions
            WHERE
                group_id IN (
                    SELECT
                        id
                    FROM
                        auth_group
                    WHERE
                        name IN ('WorkflowAddedAdmin', 'WorkflowAddedWorker')
                );""",
        ),
    ]
