# Generated by Django 5.0.4 on 2024-05-13 16:05

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_added")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_added", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_workflow
            (
                name,
                code,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'Added Workflow',
                'added_workflow',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_added' AND
                        model = 'workflowadded'
                ),
                'workflow_added',
                'workflowadded'
            );""",
            reverse_sql="""
            DELETE FROM
                workflow_workflow
            WHERE
                code = 'added_workflow';""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicalworkflow
                (
                    id,
                    code,
                    name,
                    historical_app_label,
                    historical_model,
                    history_date,
                    history_change_reason,
                    history_type,
                    content_type_id,
                    history_relation_id,
                    history_user_id
                )
                SELECT
                    W.id,
                    W.code,
                    W.name,
                    'workflow_added',
                    'workflowadded',
                    '2024-05-13 14:30:01',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    W.content_type_id,
                    W.id,
                    SYSTEM_USER.id
                FROM
                    workflow_workflow W,
                    SYSTEM_USER
                WHERE
                    W.code = 'added_workflow';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group
                (
                    name
                )
            VALUES
                (
                    'WorkflowAddedAdmin'
                ),
                (
                    'WorkflowAddedWorker'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group
            WHERE
                name IN ('WorkflowAddedAdmin', 'WorkflowAddedWorker');""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_permission
                (
                    name,
                    content_type_id,
                    codename
                )
            VALUES
                (
                    'Can Do Something',
                    (
                        SELECT
                            id
                        FROM
                            django_content_type
                        WHERE
                            app_label = 'workflow_added'
                            AND model = 'workflowadded'
                    ),
                    'can_do_something'
                ),
                (
                    'Can Do Something Else',
                    (
                        SELECT
                            id
                        FROM
                            django_content_type
                        WHERE
                            app_label = 'workflow_added'
                            AND model = 'workflowadded'
                    ),
                    'can_do_something_else'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_permission
            WHERE
                codename IN ('can_do_something', 'can_do_something_else')
                AND content_type_id = (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_added'
                        AND model = 'workflowadded'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group_permissions
                (
                    group_id,
                    permission_id
                )
            VALUES
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowAddedAdmin'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id IN (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                            )
                    )
                ),
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowAddedWorker'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id IN (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group_permissions
            WHERE
                group_id IN (
                    SELECT
                        id
                    FROM
                        auth_group
                    WHERE
                        name IN ('WorkflowAddedAdmin', 'WorkflowAddedWorker')
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_workflowpermission
                (
                    workflow_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name
                )
            VALUES
                (
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something',
                    'workflow_added',
                    'workflowadded'
                ),
                (
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something_else',
                    'workflow_added',
                    'workflowadded'
                );""",
            reverse_sql="""
            DELETE FROM
                workflow_workflowpermission
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        workflow_workflow
                    WHERE
                        code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicalworkflowpermission
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    workflow_id
                )
                SELECT
                    W.id,
                    '2024-05-13 14:30:02',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    W.id,
                    SYSTEM_USER.id,
                    W.permission_id,
                    W.historical_permission_codename,
                    W.historical_permission_content_type_app_label,
                    W.historical_permission_content_type_model_name,
                    W.workflow_id
                FROM
                    workflow_workflowpermission W,
                    SYSTEM_USER
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_state
                (
                    name,
                    code,
                    workflow_id
                )
            VALUES
                (
                    'State 1',
                    'state_1',
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow')
                ),
                (
                    'State 2',
                    'state_2',
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow')
                ),
                (
                    'State 3',
                    'state_3',
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow')
                );""",
            reverse_sql="""
                DELETE FROM
                    workflow_state
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    S.id,
                    S.code,
                    S.name,
                    '2024-05-13 14:30:03',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    S.id,
                    SYSTEM_USER.id,
                    S.workflow_id
                FROM
                    workflow_state S,
                    SYSTEM_USER
                WHERE
                    S.workflow_id IN (
                        SELECT
                            id
                        FROM
                            workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (SELECT id FROM workflow_workflow WHERE code = 'added_workflow'),
                        (
                            SELECT
                                id
                            FROM
                                workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        )
                    );""",
            reverse_sql="""
                DELETE FROM
                    workflow_initialstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicalinitialstate
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    state_id,
                    workflow_id
                )
                SELECT
                    I.id,
                    '2024-05-13 14:30:04',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    I.id,
                    SYSTEM_USER.id,
                    I.state_id,
                    I.workflow_id
                FROM
                    workflow_initialstate I,
                    SYSTEM_USER
                WHERE
                    I.workflow_id IN (
                        SELECT
                            id
                        FROM
                            workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    workflow_statepermission
                    (
                        state_id,
                        permission_id,
                        historical_permission_codename,
                        historical_permission_content_type_app_label,
                        historical_permission_content_type_model_name,
                        group_id,
                        historical_group_name,
                        grant_or_deny
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_added'
                                        AND model = 'workflowadded'
                            )
                        ),
                        'can_do_something',
                        'workflow_added',
                        'workflowadded',
                        (SELECT id FROM auth_group WHERE name = 'WorkflowAddedAdmin'),
                        'WorkflowAddedAdmin',
                        FALSE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something_else'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_added'
                                        AND model = 'workflowadded'
                            )
                        ),
                        'can_do_something_else',
                        'workflow_added',
                        'workflowadded',
                        (SELECT id FROM auth_group WHERE name = 'WorkflowAddedWorker'),
                        'WorkflowAddedWorker',
                        TRUE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                workflow_state
                            WHERE
                                code = 'state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'update_workflowadded'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_added'
                                        AND model = 'workflowadded'
                            )
                        ),
                        'update_workflowadded',
                        'workflow_added',
                        'workflowadded',
                        (SELECT id FROM auth_group WHERE name = 'WorkflowAddedAdmin'),
                        'WorkflowAddedAdmin',
                        TRUE
                    );""",
            reverse_sql="""
                DELETE FROM
                    workflow_statepermission
                WHERE
                    historical_permission_codename = 'can_do_something'
                    AND
                    historical_permission_content_type_app_label = 'workflow_added'
                    AND
                    historical_permission_content_type_model_name = 'workflowadded'
                    AND
                    historical_group_name = 'WorkflowAddedAdmin';
                DELETE FROM
                    workflow_statepermission
                WHERE
                    historical_permission_codename = 'can_do_something_else'
                    AND
                    historical_permission_content_type_app_label = 'workflow_added'
                    AND
                    historical_permission_content_type_model_name = 'workflowadded'
                    AND
                    historical_group_name = 'WorkflowAddedWorker';
                DELETE FROM
                    workflow_statepermission
                WHERE
                    historical_permission_codename = 'update_workflowadded'
                    AND
                    historical_permission_content_type_app_label = 'workflow_added'
                    AND
                    historical_permission_content_type_model_name = 'workflowadded'
                    AND
                    historical_group_name = 'WorkflowAddedAdmin';""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicalstatepermission
                (
                    id,
                    grant_or_deny,
                    history_date,
                    history_change_reason,
                    history_type,
                    group_id,
                    history_relation_id,
                    history_user_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    historical_group_name,
                    state_id
                )
                SELECT
                    S.id,
                    S.grant_or_deny,
                    '2024-05-13 14:30:05',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    S.group_id,
                    S.id,
                    SYSTEM_USER.id,
                    S.permission_id,
                    S.historical_permission_codename,
                    S.historical_permission_content_type_app_label,
                    S.historical_permission_content_type_model_name,
                    S.historical_group_name,
                    S.state_id
                FROM
                    workflow_statepermission S,
                    SYSTEM_USER
                WHERE
                    S.state_id IN (
                        SELECT
                            WS.id
                        FROM
                            workflow_state WS
                        JOIN
                            workflow_workflow W ON WS.workflow_id = W.id
                        WHERE
                            W.code = 'added_workflow'
                    )
                    AND
                    S.permission_id IN (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename IN ('can_do_something', 'can_do_something_else', 'update_workflowadded')
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                            )
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO workflow_transition (name, code, workflow_id, target_id)
            VALUES
                (
                    'Go To State 2',
                    'go_to_state_2',
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            workflow_state
                        WHERE
                            code = 'state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    'Go To State 1',
                    'go_to_state_1',
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            workflow_state
                        WHERE
                            code = 'state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    'Go To State 3',
                    'go_to_state_3',
                    (SELECT id FROM workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            workflow_state
                        WHERE
                            code = 'state_3'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                workflow_transition
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        workflow_workflow
                    WHERE
                        code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicaltransition
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    target_id,
                    workflow_id
                )
                SELECT
                    T.id,
                    T.code,
                    T.name,
                    '2024-05-13 14:30:06',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    T.id,
                    SYSTEM_USER.id,
                    T.target_id,
                    T.workflow_id
                FROM
                    workflow_transition T,
                    SYSTEM_USER
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_transitionpermission
                (
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    transition_id
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something',
                    'workflow_added',
                    'workflowadded',
                    (
                        SELECT
                            id
                        FROM
                            workflow_transition
                        WHERE
                            code = 'go_to_state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something_else',
                    'workflow_added',
                    'workflowadded',
                    (
                        SELECT
                            id
                        FROM
                            workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_workflowadded'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'update_workflowadded',
                    'workflow_added',
                    'workflowadded',
                    (
                        SELECT
                            id
                        FROM
                            workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                workflow_transitionpermission
            WHERE
                transition_id IN (
                    SELECT
                        T.id
                    FROM
                        workflow_transition T
                    JOIN
                        workflow_workflow W ON T.workflow_id = W.id
                    WHERE
                        W.code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicaltransitionpermission
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    transition_id
                )
                SELECT
                    T.id,
                    '2024-05-13 14:30:07',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    T.id,
                    SYSTEM_USER.id,
                    T.permission_id,
                    T.historical_permission_codename,
                    T.historical_permission_content_type_app_label,
                    T.historical_permission_content_type_model_name,
                    T.transition_id
                FROM
                    workflow_transitionpermission T,
                    SYSTEM_USER
                WHERE
                    transition_id IN (
                        SELECT
                            WT.id
                        FROM
                            workflow_transition WT
                        JOIN
                            workflow_workflow W ON WT.workflow_id = W.id
                        WHERE
                            W.code = 'added_workflow'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_transitionsource
                (
                    transition_id,
                    source_id
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            workflow_transition
                        WHERE
                            code = 'go_to_state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            workflow_state
                        WHERE
                            code = 'state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            workflow_state
                        WHERE
                            code = 'state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            workflow_state
                        WHERE
                            code = 'state_3'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                workflow_transitionsource
            WHERE
                transition_id IN (
                    SELECT
                        T.id
                    FROM
                        workflow_transition T
                    JOIN
                        workflow_workflow W ON T.workflow_id = W.id
                    WHERE
                        W.code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    workflow_historicaltransitionsource
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    source_id,
                    transition_id
                )
                SELECT
                    T.id,
                    '2024-05-13 14:30:08',
                    'Migration - 0002_create_workflow_deleted_permissions',
                    '+',
                    T.id,
                    SYSTEM_USER.id,
                    T.source_id,
                    T.transition_id
                FROM
                    workflow_transitionsource T,
                    SYSTEM_USER
                WHERE
                    transition_id IN (
                        SELECT
                            WT.id
                        FROM
                            workflow_transition WT
                        JOIN
                            workflow_workflow W ON WT.workflow_id = W.id
                        WHERE
                            W.code = 'added_workflow'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
