# Generated by Django 5.0.4 on 2024-05-13 16:05

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_added")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_added", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflow
            (
                name,
                code,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'Added Workflow',
                'added_workflow',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_added' AND
                        model = 'workflowadded'
                ),
                'workflow_added',
                'workflowadded'
            );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_workflow
            WHERE
                code = 'added_workflow';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflowpermission
                (
                    workflow_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name
                )
            VALUES
                (
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something',
                    'workflow_added',
                    'workflowadded'
                ),
                (
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something_else',
                    'workflow_added',
                    'workflowadded'
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_workflowpermission
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_state
                (
                    name,
                    code,
                    workflow_id
                )
            VALUES
                (
                    'State 1',
                    'state_1',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    )
                ),
                (
                    'State 2',
                    'state_2',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    )
                ),
                (
                    'State 3',
                    'state_3',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    )
                );""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_state
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'added_workflow'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        )
                    );""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_initialstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'added_workflow'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    vueda_workflow_statepermission
                    (
                        state_id,
                        permission_id,
                        historical_permission_codename,
                        historical_permission_content_type_app_label,
                        historical_permission_content_type_model_name,
                        group_id,
                        historical_group_name,
                        grant_or_deny
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_added'
                                        AND model = 'workflowadded'
                            )
                        ),
                        'can_do_something',
                        'workflow_added',
                        'workflowadded',
                        (
                            SELECT
                                id
                            FROM
                                auth_group
                            WHERE
                                name = 'WorkflowAddedAdmin'
                        ),
                        'WorkflowAddedAdmin',
                        FALSE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_1'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'can_do_something_else'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_added'
                                        AND model = 'workflowadded'
                            )
                        ),
                        'can_do_something_else',
                        'workflow_added',
                        'workflowadded',
                        (
                            SELECT
                                id
                            FROM
                                auth_group
                             WHERE
                                name = 'WorkflowAddedWorker'
                        ),
                        'WorkflowAddedWorker',
                        TRUE
                    ),
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'state_2'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'added_workflow'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'update_workflowadded'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'workflow_added'
                                        AND model = 'workflowadded'
                            )
                        ),
                        'update_workflowadded',
                        'workflow_added',
                        'workflowadded',
                        (
                            SELECT
                                id
                            FROM
                                auth_group
                            WHERE
                                name = 'WorkflowAddedAdmin'
                        ),
                        'WorkflowAddedAdmin',
                        TRUE
                    );""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    historical_permission_codename = 'can_do_something'
                    AND
                    historical_permission_content_type_app_label = 'workflow_added'
                    AND
                    historical_permission_content_type_model_name = 'workflowadded'
                    AND
                    historical_group_name = 'WorkflowAddedAdmin';
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    historical_permission_codename = 'can_do_something_else'
                    AND
                    historical_permission_content_type_app_label = 'workflow_added'
                    AND
                    historical_permission_content_type_model_name = 'workflowadded'
                    AND
                    historical_group_name = 'WorkflowAddedWorker';
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    historical_permission_codename = 'update_workflowadded'
                    AND
                    historical_permission_content_type_app_label = 'workflow_added'
                    AND
                    historical_permission_content_type_model_name = 'workflowadded'
                    AND
                    historical_group_name = 'WorkflowAddedAdmin';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_transition
            (
                name,
                code,
                workflow_id,
                target_id
            )
            VALUES
                (
                    'Go To State 1',
                    'go_to_state_1',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    'Go To State 2',
                    'go_to_state_2',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    'Go To State 3',
                    'go_to_state_3',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'added_workflow'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'state_3'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_transition
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_transitionpermission
                (
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    transition_id
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something',
                    'workflow_added',
                    'workflowadded',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'go_to_state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'can_do_something_else',
                    'workflow_added',
                    'workflowadded',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_workflowadded'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_added'
                                    AND model = 'workflowadded'
                        )
                    ),
                    'update_workflowadded',
                    'workflow_added',
                    'workflowadded',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_transitionpermission
            WHERE
                transition_id IN (
                    SELECT
                        T.id
                    FROM
                        vueda_workflow_transition T
                    JOIN
                        vueda_workflow_workflow W ON T.workflow_id = W.id
                    WHERE
                        W.code = 'added_workflow'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_transitionsource
                (
                    transition_id,
                    source_id,
                    ignored
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'go_to_state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    FALSE
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'state_2'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    FALSE
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'go_to_state_1'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'state_3'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'added_workflow'
                            )
                    ),
                    FALSE
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_transitionsource
            WHERE
                transition_id IN (
                    SELECT
                        T.id
                    FROM
                        vueda_workflow_transition T
                    JOIN
                        vueda_workflow_workflow W ON T.workflow_id = W.id
                    WHERE
                        W.code = 'added_workflow'
                );""",
        ),
    ]
