import { mergeClasses } from "@vueda/theme/vueda-tailwind/classMerger.js";

describe("lib/theme/vueda-tailwind/classMerger.js", () => {
    it.each([
        ["bg-secondary bg-amber-500", "bg-amber-500"],
        ["text-heading text-foreground", "text-heading text-foreground"],
        ["text-foreground text-title", "text-foreground text-title"],
        ["text-body text-display", "text-display"],
        ["text-title text-sm", "text-sm"],
        ["text-sm text-heading", "text-heading"],
        ["rounded-vueda-control rounded-lg", "rounded-lg"],
        ["rounded-lg rounded-vueda-card", "rounded-vueda-card"],
        ["h-8 h-vueda-control", "h-vueda-control"],
        ["px-vueda-control-px px-2", "px-2"],
        ["size-vueda-control size-4", "size-4"],
        ["shadow-vueda-card shadow-lg", "shadow-lg"],
        ["shadow-lg shadow-vueda-popover", "shadow-vueda-popover"],
        ["shadow-vueda-card shadow-red-500", "shadow-vueda-card shadow-red-500"],
        ["transition-colors no-transition", "no-transition"],
        ["no-transition transition-all", "transition-all"],
        ["h-hairline h-2", "h-2"],
        ["w-2 w-hairline", "w-hairline"],
        ["border-hairline border-red-500", "border-hairline border-red-500"],
        ["border-2 border-hairline", "border-hairline"],
        ["border-b-hairline border-b-4", "border-b-4"],
        ["border-x-hairline border-l-4", "border-x-hairline border-l-4"],
        ["border-l-4 border-x-hairline", "border-x-hairline"],
        ["border-y-hairline border-0", "border-0"],
        ["hairline hairline-border", "hairline hairline-border"],
        ["hairline-input hairline-destructive", "hairline-destructive"],
        ["hairline field-line", "field-line"],
        ["field-line overlay-hairline", "overlay-hairline"],
        ["overlay-hairline focus-ring-shadow", "focus-ring-shadow"],
        ["focus-ring-shadow overlay-hairline", "overlay-hairline"],
        ["overlay-hairline overlay-hairline-elevated", "overlay-hairline overlay-hairline-elevated"],
        ["hairline focus-ring-shadow", "hairline focus-ring-shadow"],
        ["focus-ring-shadow field-line", "focus-ring-shadow field-line"],
        ["field-line focus-ring-shadow hairline-warning", "field-line focus-ring-shadow hairline-warning"],
        ["hairline focus-ring-shadow shadow-none", "shadow-none"],
        ["shadow-lg hairline", "hairline"],
        ["hairline shadow-vueda-control", "shadow-vueda-control"],
        ["field-line shadow-vueda-control", "shadow-vueda-control"],
        ["focus-ring focus-ring-destructive", "focus-ring focus-ring-destructive"],
        ["focus-ring-destructive focus-ring-sidebar", "focus-ring-sidebar"],
        ["focus-ring-shadow focus-ring-shadow-destructive", "focus-ring-shadow focus-ring-shadow-destructive"],
        ["focus-ring-shadow-destructive focus-ring-sidebar", "focus-ring-sidebar"],
        ["outline-2 outline-offset-4 focus-ring", "focus-ring"],
        ["focus-ring focus-ring-shadow", "focus-ring-shadow"],
        ["focus-ring-shadow focus-ring", "focus-ring"],
        ["font-sans font-mono", "font-mono"],
        ["animate-caret-blink animate-vueda-heartbeat-pulse", "animate-vueda-heartbeat-pulse"],
        ["hover:bg-secondary hover:bg-amber-500 bg-secondary", "hover:bg-amber-500 bg-secondary"],
        [
            "data-[active]:text-heading data-[active]:text-foreground",
            "data-[active]:text-heading data-[active]:text-foreground",
        ],
        ["md:text-title md:text-body", "md:text-body"],
        ["bg-secondary! bg-amber-500!", "bg-amber-500!"],
        ["bg-secondary bg-[color:var(--custom)]", "bg-[color:var(--custom)]"],
    ])("merges %s", (classes, expected) => {
        expect(mergeClasses(classes)).toBe(expected);
    });
});
