# Generated by Django 5.0.7 on 2024-07-26 19:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoExpandableFieldsData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "No expandable field data",
                "verbose_name_plural": "No expandable fields data",
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
