# Generated by Django 5.1 on 2024-08-16 17:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoExpandableFieldsData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "No expandable field data",
                "verbose_name_plural": "No expandable fields data",
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="NoNameField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("the_name_field", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "No name field",
                "verbose_name_plural": "No name field",
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="RelatedObjectsAreMissingData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_name", models.ManyToManyField(blank=True, to="erring.nonamefield")),
            ],
            options={
                "verbose_name": "Related objects are missing data",
                "verbose_name_plural": "Related objects are missing data",
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
