# Generated by Django 5.2.11 on 2026-03-24 23:18
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
import copy
import datetime
import os

from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db.models import Count
from django.utils import timezone
from django.db import migrations


history_change_reason = "Workflow Migration - 0002_workflow_migrations_2026_03_24"
migration_app_label = "erring"
changed_data = [
    {
        "changes": {
            "code": "mosovowo",
            "content_type_id": {"app_label": "erring", "model": "mosovowo"},
            "historical_app_label": "erring",
            "historical_model": "mosovowo",
            "id": {"code": "mosovowo"},
            "name": "MoSoVoWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosovowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosovowo",
            "id": {
                "historical_permission_codename": "view_mosovowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosovowo",
                "workflow_id": {"code": "mosovowo"},
            },
            "permission_id": {
                "codename": "read_mosovowo",
                "content_type_id": {"app_label": "erring", "model": "mosovowo"},
            },
            "workflow_id": {"code": "mosovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mosovowo"}},
            "name": "Approved",
            "workflow_id": {"code": "mosovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mosovowo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mosovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mosovowo"}},
                "workflow_id": {"code": "mosovowo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mosovowo"}},
            "workflow_id": {"code": "mosovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mosovowo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mosovowo"}},
            "workflow_id": {"code": "mosovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosovowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosovowo",
            "id": {
                "historical_permission_codename": "view_mosovowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosovowo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosovowo"}},
            },
            "permission_id": {
                "codename": "read_mosovowo",
                "content_type_id": {"app_label": "erring", "model": "mosovowo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosovowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mosovowo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosovowo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mosovowo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosovowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mxsovowo",
            "content_type_id": {"app_label": "erring", "model": "mxsovowo"},
            "historical_app_label": "erring",
            "historical_model": "mxsovowo",
            "id": {"code": "mxsovowo"},
            "name": "MxSoVoWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsovowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsovowo",
            "id": {
                "historical_permission_codename": "view_mxsovowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsovowo",
                "workflow_id": {"code": "mxsovowo"},
            },
            "permission_id": {
                "codename": "read_mxsovowo",
                "content_type_id": {"app_label": "erring", "model": "mxsovowo"},
            },
            "workflow_id": {"code": "mxsovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mxsovowo"}},
            "name": "Approved",
            "workflow_id": {"code": "mxsovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mxsovowo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mxsovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsovowo"}},
                "workflow_id": {"code": "mxsovowo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsovowo"}},
            "workflow_id": {"code": "mxsovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mxsovowo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mxsovowo"}},
            "workflow_id": {"code": "mxsovowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsovowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsovowo",
            "id": {
                "historical_permission_codename": "view_mxsovowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsovowo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovowo"}},
            },
            "permission_id": {
                "codename": "read_mxsovowo",
                "content_type_id": {"app_label": "erring", "model": "mxsovowo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsovowo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovowo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsovowo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mosxvowo",
            "content_type_id": {"app_label": "erring", "model": "mosxvowo"},
            "historical_app_label": "erring",
            "historical_model": "mosxvowo",
            "id": {"code": "mosxvowo"},
            "name": "MoSxVoWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosxvowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosxvowo",
            "id": {
                "historical_permission_codename": "view_mosxvowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosxvowo",
                "workflow_id": {"code": "mosxvowo"},
            },
            "permission_id": {
                "codename": "read_mosxvowo",
                "content_type_id": {"app_label": "erring", "model": "mosxvowo"},
            },
            "workflow_id": {"code": "mosxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mosxvowo"}},
            "name": "Approved",
            "workflow_id": {"code": "mosxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mosxvowo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mosxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mosxvowo"}},
                "workflow_id": {"code": "mosxvowo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mosxvowo"}},
            "workflow_id": {"code": "mosxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mosxvowo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mosxvowo"}},
            "workflow_id": {"code": "mosxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosxvowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosxvowo",
            "id": {
                "historical_permission_codename": "view_mosxvowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosxvowo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvowo"}},
            },
            "permission_id": {
                "codename": "read_mosxvowo",
                "content_type_id": {"app_label": "erring", "model": "mosxvowo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mosxvowo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvowo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mosxvowo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mxsxvowo",
            "content_type_id": {"app_label": "erring", "model": "mxsxvowo"},
            "historical_app_label": "erring",
            "historical_model": "mxsxvowo",
            "id": {"code": "mxsxvowo"},
            "name": "MxSxVoWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsxvowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsxvowo",
            "id": {
                "historical_permission_codename": "view_mxsxvowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsxvowo",
                "workflow_id": {"code": "mxsxvowo"},
            },
            "permission_id": {
                "codename": "read_mxsxvowo",
                "content_type_id": {"app_label": "erring", "model": "mxsxvowo"},
            },
            "workflow_id": {"code": "mxsxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mxsxvowo"}},
            "name": "Approved",
            "workflow_id": {"code": "mxsxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mxsxvowo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mxsxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvowo"}},
                "workflow_id": {"code": "mxsxvowo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvowo"}},
            "workflow_id": {"code": "mxsxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mxsxvowo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mxsxvowo"}},
            "workflow_id": {"code": "mxsxvowo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsxvowo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsxvowo",
            "id": {
                "historical_permission_codename": "view_mxsxvowo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsxvowo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvowo"}},
            },
            "permission_id": {
                "codename": "read_mxsxvowo",
                "content_type_id": {"app_label": "erring", "model": "mxsxvowo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvowo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvowo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvowo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvowo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mosovxwo",
            "content_type_id": {"app_label": "erring", "model": "mosovxwo"},
            "historical_app_label": "erring",
            "historical_model": "mosovxwo",
            "id": {"code": "mosovxwo"},
            "name": "MoSoVxWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosovxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosovxwo",
            "id": {
                "historical_permission_codename": "view_mosovxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosovxwo",
                "workflow_id": {"code": "mosovxwo"},
            },
            "permission_id": {
                "codename": "read_mosovxwo",
                "content_type_id": {"app_label": "erring", "model": "mosovxwo"},
            },
            "workflow_id": {"code": "mosovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mosovxwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mosovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mosovxwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mosovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mosovxwo"}},
                "workflow_id": {"code": "mosovxwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mosovxwo"}},
            "workflow_id": {"code": "mosovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mosovxwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mosovxwo"}},
            "workflow_id": {"code": "mosovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosovxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosovxwo",
            "id": {
                "historical_permission_codename": "view_mosovxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosovxwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosovxwo"}},
            },
            "permission_id": {
                "codename": "read_mosovxwo",
                "content_type_id": {"app_label": "erring", "model": "mosovxwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosovxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mosovxwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosovxwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mosovxwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosovxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mxsovxwo",
            "content_type_id": {"app_label": "erring", "model": "mxsovxwo"},
            "historical_app_label": "erring",
            "historical_model": "mxsovxwo",
            "id": {"code": "mxsovxwo"},
            "name": "MxSoVxWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsovxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsovxwo",
            "id": {
                "historical_permission_codename": "view_mxsovxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsovxwo",
                "workflow_id": {"code": "mxsovxwo"},
            },
            "permission_id": {
                "codename": "read_mxsovxwo",
                "content_type_id": {"app_label": "erring", "model": "mxsovxwo"},
            },
            "workflow_id": {"code": "mxsovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mxsovxwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mxsovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mxsovxwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mxsovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsovxwo"}},
                "workflow_id": {"code": "mxsovxwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsovxwo"}},
            "workflow_id": {"code": "mxsovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mxsovxwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mxsovxwo"}},
            "workflow_id": {"code": "mxsovxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsovxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsovxwo",
            "id": {
                "historical_permission_codename": "view_mxsovxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsovxwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovxwo"}},
            },
            "permission_id": {
                "codename": "read_mxsovxwo",
                "content_type_id": {"app_label": "erring", "model": "mxsovxwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsovxwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovxwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsovxwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mosxvxwo",
            "content_type_id": {"app_label": "erring", "model": "mosxvxwo"},
            "historical_app_label": "erring",
            "historical_model": "mosxvxwo",
            "id": {"code": "mosxvxwo"},
            "name": "MoSxVxWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosxvxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosxvxwo",
            "id": {
                "historical_permission_codename": "view_mosxvxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosxvxwo",
                "workflow_id": {"code": "mosxvxwo"},
            },
            "permission_id": {
                "codename": "read_mosxvxwo",
                "content_type_id": {"app_label": "erring", "model": "mosxvxwo"},
            },
            "workflow_id": {"code": "mosxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mosxvxwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mosxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mosxvxwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mosxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mosxvxwo"}},
                "workflow_id": {"code": "mosxvxwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mosxvxwo"}},
            "workflow_id": {"code": "mosxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mosxvxwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mosxvxwo"}},
            "workflow_id": {"code": "mosxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosxvxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosxvxwo",
            "id": {
                "historical_permission_codename": "view_mosxvxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosxvxwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvxwo"}},
            },
            "permission_id": {
                "codename": "read_mosxvxwo",
                "content_type_id": {"app_label": "erring", "model": "mosxvxwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mosxvxwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvxwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mosxvxwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mxsxvxwo",
            "content_type_id": {"app_label": "erring", "model": "mxsxvxwo"},
            "historical_app_label": "erring",
            "historical_model": "mxsxvxwo",
            "id": {"code": "mxsxvxwo"},
            "name": "MxSxVxWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsxvxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsxvxwo",
            "id": {
                "historical_permission_codename": "view_mxsxvxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsxvxwo",
                "workflow_id": {"code": "mxsxvxwo"},
            },
            "permission_id": {
                "codename": "read_mxsxvxwo",
                "content_type_id": {"app_label": "erring", "model": "mxsxvxwo"},
            },
            "workflow_id": {"code": "mxsxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mxsxvxwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mxsxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mxsxvxwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mxsxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvxwo"}},
                "workflow_id": {"code": "mxsxvxwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvxwo"}},
            "workflow_id": {"code": "mxsxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mxsxvxwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mxsxvxwo"}},
            "workflow_id": {"code": "mxsxvxwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsxvxwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsxvxwo",
            "id": {
                "historical_permission_codename": "view_mxsxvxwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsxvxwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvxwo"}},
            },
            "permission_id": {
                "codename": "read_mxsxvxwo",
                "content_type_id": {"app_label": "erring", "model": "mxsxvxwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvxwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvxwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvxwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvxwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mosovzwo",
            "content_type_id": {"app_label": "erring", "model": "mosovzwo"},
            "historical_app_label": "erring",
            "historical_model": "mosovzwo",
            "id": {"code": "mosovzwo"},
            "name": "MoSoVzWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosovzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosovzwo",
            "id": {
                "historical_permission_codename": "view_mosovzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosovzwo",
                "workflow_id": {"code": "mosovzwo"},
            },
            "permission_id": {
                "codename": "read_mosovzwo",
                "content_type_id": {"app_label": "erring", "model": "mosovzwo"},
            },
            "workflow_id": {"code": "mosovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mosovzwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mosovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mosovzwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mosovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mosovzwo"}},
                "workflow_id": {"code": "mosovzwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mosovzwo"}},
            "workflow_id": {"code": "mosovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mosovzwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mosovzwo"}},
            "workflow_id": {"code": "mosovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosovzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosovzwo",
            "id": {
                "historical_permission_codename": "view_mosovzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosovzwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosovzwo"}},
            },
            "permission_id": {
                "codename": "read_mosovzwo",
                "content_type_id": {"app_label": "erring", "model": "mosovzwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosovzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mosovzwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosovzwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mosovzwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosovzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mxsovzwo",
            "content_type_id": {"app_label": "erring", "model": "mxsovzwo"},
            "historical_app_label": "erring",
            "historical_model": "mxsovzwo",
            "id": {"code": "mxsovzwo"},
            "name": "MxSoVzWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsovzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsovzwo",
            "id": {
                "historical_permission_codename": "view_mxsovzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsovzwo",
                "workflow_id": {"code": "mxsovzwo"},
            },
            "permission_id": {
                "codename": "read_mxsovzwo",
                "content_type_id": {"app_label": "erring", "model": "mxsovzwo"},
            },
            "workflow_id": {"code": "mxsovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mxsovzwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mxsovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mxsovzwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mxsovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsovzwo"}},
                "workflow_id": {"code": "mxsovzwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsovzwo"}},
            "workflow_id": {"code": "mxsovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mxsovzwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mxsovzwo"}},
            "workflow_id": {"code": "mxsovzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsovzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsovzwo",
            "id": {
                "historical_permission_codename": "view_mxsovzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsovzwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovzwo"}},
            },
            "permission_id": {
                "codename": "read_mxsovzwo",
                "content_type_id": {"app_label": "erring", "model": "mxsovzwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsovzwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovzwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsovzwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsovzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mosxvzwo",
            "content_type_id": {"app_label": "erring", "model": "mosxvzwo"},
            "historical_app_label": "erring",
            "historical_model": "mosxvzwo",
            "id": {"code": "mosxvzwo"},
            "name": "MoSxVzWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosxvzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosxvzwo",
            "id": {
                "historical_permission_codename": "view_mosxvzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosxvzwo",
                "workflow_id": {"code": "mosxvzwo"},
            },
            "permission_id": {
                "codename": "read_mosxvzwo",
                "content_type_id": {"app_label": "erring", "model": "mosxvzwo"},
            },
            "workflow_id": {"code": "mosxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mosxvzwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mosxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mosxvzwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mosxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mosxvzwo"}},
                "workflow_id": {"code": "mosxvzwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mosxvzwo"}},
            "workflow_id": {"code": "mosxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mosxvzwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mosxvzwo"}},
            "workflow_id": {"code": "mosxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mosxvzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mosxvzwo",
            "id": {
                "historical_permission_codename": "view_mosxvzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mosxvzwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvzwo"}},
            },
            "permission_id": {
                "codename": "read_mosxvzwo",
                "content_type_id": {"app_label": "erring", "model": "mosxvzwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mosxvzwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvzwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mosxvzwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mosxvzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "code": "mxsxvzwo",
            "content_type_id": {"app_label": "erring", "model": "mxsxvzwo"},
            "historical_app_label": "erring",
            "historical_model": "mxsxvzwo",
            "id": {"code": "mxsxvzwo"},
            "name": "MxSxVzWo",
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsxvzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsxvzwo",
            "id": {
                "historical_permission_codename": "view_mxsxvzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsxvzwo",
                "workflow_id": {"code": "mxsxvzwo"},
            },
            "permission_id": {
                "codename": "read_mxsxvzwo",
                "content_type_id": {"app_label": "erring", "model": "mxsxvzwo"},
            },
            "workflow_id": {"code": "mxsxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "approved",
            "id": {"code": "approved", "workflow_id": {"code": "mxsxvzwo"}},
            "name": "Approved",
            "workflow_id": {"code": "mxsxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unapproved",
            "id": {"code": "unapproved", "workflow_id": {"code": "mxsxvzwo"}},
            "name": "Unapproved",
            "workflow_id": {"code": "mxsxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvzwo"}},
                "workflow_id": {"code": "mxsxvzwo"},
            },
            "state_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvzwo"}},
            "workflow_id": {"code": "mxsxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "approve",
            "id": {"code": "approve", "workflow_id": {"code": "mxsxvzwo"}},
            "name": "Approve",
            "target_id": {"code": "approved", "workflow_id": {"code": "mxsxvzwo"}},
            "workflow_id": {"code": "mxsxvzwo"},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "view_mxsxvzwo",
            "historical_permission_content_type_app_label": "erring",
            "historical_permission_content_type_model_name": "mxsxvzwo",
            "id": {
                "historical_permission_codename": "view_mxsxvzwo",
                "historical_permission_content_type_app_label": "erring",
                "historical_permission_content_type_model_name": "mxsxvzwo",
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvzwo"}},
            },
            "permission_id": {
                "codename": "read_mxsxvzwo",
                "content_type_id": {"app_label": "erring", "model": "mxsxvzwo"},
            },
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvzwo"}},
                "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvzwo"}},
            },
            "source_id": {"code": "unapproved", "workflow_id": {"code": "mxsxvzwo"}},
            "transition_id": {"code": "approve", "workflow_id": {"code": "mxsxvzwo"}},
        },
        "history_date": datetime.datetime(2026, 3, 24, 17, 15, 54, 206078, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "transitionsource",
    },
]


def forwards_migrate_workflow(apps, schema_editor):
    for changed_item in copy.deepcopy(changed_data):  # Copied, so tests can migrate forwards and backwards.
        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item)

            case "state":
                handle_state(apps, changed_item)

            case "statepermission":
                handle_state_permission(apps, changed_item)

            case "initialstate":
                handle_initial_state(apps, changed_item)

            case "transition":
                handle_transition(apps, changed_item)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item)

            case "transitionsource":
                handle_transition_source(apps, changed_item)

    handle_state_objects(apps)


def backwards_migrate_workflow(apps, schema_editor):
    handle_state_objects(apps, reversing=True)

    # Make sure we go through the changed_data in reverse order, so we undo things correctly.
    for changed_item in reversed(copy.deepcopy(changed_data)):  # Copied, so tests can migrate forwards and backwards.
        match changed_item["history_type"]:
            case "added":
                changed_item["history_type"] = "deleted"

            case "deleted":
                changed_item["history_type"] = "added"

        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, reversing=True)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, reversing=True)

            case "state":
                handle_state(apps, changed_item, reversing=True)

            case "statepermission":
                handle_state_permission(apps, changed_item, reversing=True)

            case "initialstate":
                handle_initial_state(apps, changed_item, reversing=True)

            case "transition":
                handle_transition(apps, changed_item, reversing=True)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, reversing=True)

            case "transitionsource":
                handle_transition_source(apps, changed_item, reversing=True)


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config(migration_app_label)
    create_permissions(app, interactive=False)


def handle_workflow(apps, changed_item, *, reversing=False):
    historical_workflow = apps.get_model("vueda_workflow", "HistoricalWorkflow")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            del data["id"]  # This needs to be removed before we create.

            workflow = model_workflow.objects.create(**data)

            add_history_to_data(
                data,
                workflow,
                "+",
                changed_item["history_date"],
            )
            historical_workflow.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(workflow, data, reversing=reversing)
            add_history_to_data(
                data,
                workflow,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "content_type_id",
                    "historical_app_label",
                    "historical_model",
                    "name",
                ),
            )
            historical_workflow.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            workflow = model_workflow.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow, "-", changed_item["history_date"])
            historical_workflow.objects.create(**data)
            workflow.delete()


def handle_workflow_permission(apps, changed_item, *, reversing=False):
    historical_workflow_permission = apps.get_model("vueda_workflow", "HistoricalWorkflowPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")
    model_workflow_permission = apps.get_model("vueda_workflow", "WorkflowPermission")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            workflow_permission = model_workflow_permission.objects.create(**data)

            add_history_to_data(data, workflow_permission, "+", changed_item["history_date"])
            historical_workflow_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            apply_and_save_changes(workflow_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                workflow_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "workflow_id",
                ),
            )
            historical_workflow_permission.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow_permission, "-", changed_item["history_date"])
            historical_workflow_permission.objects.create(**data)
            workflow_permission.delete()


def handle_state(apps, changed_item, *, reversing=False):
    historical_state = apps.get_model("vueda_workflow", "HistoricalState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            state = model_state.objects.create(**data)

            add_history_to_data(data, state, "+", changed_item["history_date"])
            historical_state.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(state, data, reversing=reversing)
            add_history_to_data(
                data,
                state,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "name",
                    "workflow_id",
                ),
            )
            historical_state.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            state = model_state.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state, "-", changed_item["history_date"])
            historical_state.objects.create(**data)
            state.delete()


def handle_state_permission(apps, changed_item, *, reversing=False):
    historical_state_permission = apps.get_model("vueda_workflow", "HistoricalStatePermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_group = apps.get_model("auth", "Group")
    model_permission = apps.get_model("auth", "Permission")
    model_state = apps.get_model("vueda_workflow", "State")
    model_state_permission = apps.get_model("vueda_workflow", "StatePermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["group_id"])
            data["group_id"] = group.pk

            del data["id"]  # This needs to be removed before we create.

            state_permission = model_state_permission.objects.create(**data)

            add_history_to_data(data, state_permission, "+", changed_item["history_date"])
            historical_state_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            group = model_group.objects.get(**get_id_values_from_item(data["id"]["group_id"], reversing=reversing))
            data["id"]["group_id"] = group.pk
            state_permission = model_state_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["group_id"]) is tuple:
                new_group_ids = []
                for group_id in data["group_id"]:
                    group = model_group.objects.get(**group_id)
                    new_group_ids.append(group.pk)
                data["group_id"] = tuple(new_group_ids)

            apply_and_save_changes(state_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                state_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "grant_or_deny",
                    "group_id",
                    "historical_group_name",
                    "historical_permission_codename",
                    "permission_id",
                    "state_id",
                ),
            )
            historical_state_permission.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["id"]["group_id"])
            data["id"]["group_id"] = group.pk
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state_permission, "-", changed_item["history_date"])
            historical_state_permission.objects.create(**data)
            state_permission.delete()


def handle_initial_state(apps, changed_item, *, reversing=False):
    historical_initial_state = apps.get_model("vueda_workflow", "HistoricalInitialState")
    model_initial_state = apps.get_model("vueda_workflow", "InitialState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])

            data["state_id"] = state.pk
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            initial_state = model_initial_state.objects.create(**data)

            add_history_to_data(data, initial_state, "+", changed_item["history_date"])
            historical_initial_state.objects.create(**data)

        case "changed":
            data["id"]["state_id"] = get_id_values_from_item(data["id"]["state_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["state_id"]) is tuple:
                state_ids = []
                for state_data in data["state_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["state_id"] = tuple(state_ids)

            apply_and_save_changes(initial_state, data, reversing=reversing)
            add_history_to_data(
                data,
                initial_state,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "state_id",
                    "workflow_id",
                ),
            )
            historical_initial_state.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            add_history_to_data(data, initial_state, "-", changed_item["history_date"])
            historical_initial_state.objects.create(**data)
            initial_state.delete()


def handle_transition(apps, changed_item, *, reversing=False):
    historical_transition = apps.get_model("vueda_workflow", "HistoricalTransition")
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            del data["id"]  # This needs to be removed before we create.

            transition = model_transition.objects.create(**data)

            add_history_to_data(data, transition, "+", changed_item["history_date"])
            historical_transition.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["target_id"]) is tuple:
                state_ids = []
                for state_data in data["target_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["target_id"] = tuple(state_ids)

            apply_and_save_changes(transition, data, reversing=reversing)
            add_history_to_data(
                data,
                transition,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "name",
                    "target_id",
                    "workflow_id",
                ),
            )
            historical_transition.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition, "-", changed_item["history_date"])
            historical_transition.objects.create(**data)
            transition.delete()


def handle_transition_permission(apps, changed_item, *, reversing=False):
    historical_transition_permission = apps.get_model("vueda_workflow", "HistoricalTransitionPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_permission = apps.get_model("vueda_workflow", "TransitionPermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            transition_permission = model_transition_permission.objects.create(**data)

            add_history_to_data(data, transition_permission, "+", changed_item["history_date"])
            historical_transition_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    state = model_transition.objects.get(**transition_data)
                    transition_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                transition_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "transition_id",
                ),
            )
            historical_transition_permission.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_permission, "-", changed_item["history_date"])
            historical_transition_permission.objects.create(**data)
            transition_permission.delete()


def handle_transition_source(apps, changed_item, *, reversing=False):
    historical_transition_source = apps.get_model("vueda_workflow", "HistoricalTransitionSource")
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_source = apps.get_model("vueda_workflow", "TransitionSource")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["source_id"]["workflow_id"])
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["source_id"])
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            transition_source = model_transition_source.objects.create(**data)

            add_history_to_data(data, transition_source, "+", changed_item["history_date"])
            historical_transition_source.objects.create(**data)

        case "changed":
            data["id"]["source_id"] = get_id_values_from_item(data["id"]["source_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk

            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["source_id"]) is tuple:
                state_ids = []
                for state_data in data["source_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                data["source_id"] = tuple(state_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    transition = model_transition.objects.get(**transition_data)
                    transition_ids.append(transition.pk)
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_source, data, reversing=reversing)
            add_history_to_data(
                data,
                transition_source,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "source_id",
                    "transition_id",
                    "ignored",
                ),
            )
            historical_transition_source.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_source, "-", changed_item["history_date"])
            historical_transition_source.objects.create(**data)
            transition_source.delete()


def handle_state_objects(apps, *, reversing=False):
    model_historical_object_state = apps.get_model("vueda_workflow", "HistoricalObjectState")
    model_object_state = apps.get_model("vueda_workflow", "ObjectState")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    for workflow in model_workflow.objects.all():
        model_obj = apps.get_model(workflow.historical_app_label, workflow.historical_model)
        manage_state_objects(
            workflow, model_obj, model_object_state, model_historical_object_state, reversing=reversing
        )


def manage_state_objects(
    workflow, obj_class, workflow_obj_state_class, historical_workflow_obj_state_class, *, reversing=False
):
    if reversing:
        # Delete all object states
        workflow_obj_state_class.objects.filter(workflow=workflow).delete()

    else:
        initial_state = workflow.initial_state
        for obj in obj_class.objects.all():
            if not workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk).exists():
                historical_records = historical_workflow_obj_state_class.objects.filter(
                    workflow=workflow,
                    object_id=obj.pk,
                )
                original_historical_records_count = historical_records.count()
                obj_state_obj = workflow_obj_state_class.objects.create(
                    workflow=workflow,
                    object_id=obj.id,
                    state=initial_state.state,
                )
                # We are running through a migration, so we need to create history.
                if original_historical_records_count == historical_records.count():
                    historical_workflow_obj_state_class.objects.create(
                        id=obj_state_obj.pk,
                        workflow=workflow,
                        object_id=obj.pk,
                        state=initial_state.state,
                        history_date=timezone.now(),
                        history_relation=obj_state_obj,
                        history_type="+",
                    )
            else:
                # If a workflow's initial state has changed, and an object
                # hasn't been changed, then switch it to the new initial state.
                obj_state = (
                    workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk)
                    .exclude(state_id=initial_state.state_id)
                    .first()
                )
                if obj_state is not None:
                    # TODO: When this is switched to django-pghistory, we will need to add context before the
                    #   ObjectState update, so we can use that to know the object state hasn't been changed,
                    #   since it is possible for the initial state on a workflow to change multiple times.
                    history_count = historical_workflow_obj_state_class.objects.filter(
                        workflow=workflow, object_id=obj.pk
                    ).aggregate(count=Count("history_id"))
                    if history_count is not None and history_count["count"] == 1:
                        workflow_obj_state_class.objects.filter(pk=obj_state.pk).update(state_id=initial_state.state_id)
                        historical_workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk).update(
                            state_id=initial_state.state_id
                        )


def add_history_to_data(history_data, obj, history_type, history_date, fields=()):
    # For changed history
    for field_name in fields:
        history_data[field_name] = getattr(obj, field_name)

    # For all history
    history_data["history_change_reason"] = history_change_reason
    history_data["history_date"] = history_date
    history_data["history_relation_id"] = obj.pk
    history_data["history_type"] = history_type
    history_data["id"] = obj.pk


def apply_and_save_changes(obj, data, *, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    for key, values in data.items():
        if type(values) is not tuple:
            continue

        old_value, new_value = values

        if reversing:
            setattr(obj, key, old_value)

        else:
            setattr(obj, key, new_value)

    obj.save()


def get_id_values_from_item(values, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    if type(values) is tuple:
        return values[1 if reversing else 0]

    return values


def get_id_values_from_dict(id_data, reversing=False):
    results = {}
    for field_name, values in id_data.items():
        results[field_name] = get_id_values_from_item(values, reversing)

    return results


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vueda_workflow", "0006_rename_fail_with_silent_historicaltransitionsource_ignored_and_more"),
        ("erring", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow,
            reverse_code=backwards_migrate_workflow,
        ),
    ]
