# Generated by Django 6.1 on 2026-09-08 19:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erring", "0003_falseyformattednameslookupevent_mosovowoevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceResolution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("name"),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "verbose_name": "Source resolution",
                "verbose_name_plural": "Source resolution",
                "abstract": False,
                "managed": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="SourceResolutionRelated",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UnresolvableLookupExpression",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unresolvable lookup expression",
                "verbose_name_plural": "Unresolvable lookup expression",
                "abstract": False,
                "managed": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="UnresolvableLookupExpressionAtFirstSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unresolvable lookup expression at first segment",
                "verbose_name_plural": "Unresolvable lookup expression at first segment",
                "abstract": False,
                "managed": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
