# Generated by Django 6.1 on 2026-09-10 20:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("erring", "0004_sourceresolution_sourceresolutionrelated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BothFormattedNameSelectRelatedConfigured",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("the_name_field", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Both formatted name select related configured",
                "verbose_name_plural": "Both formatted name select related configured",
                "abstract": False,
                "managed": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
