# Generated by Django 6.1 on 2026-09-23 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erring", "0005_bothformattednameselectrelatedconfigured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mosovowo",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosovowx",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosovxwo",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosovxwx",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosovzwo",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosovzwx",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosxvowo",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosxvowx",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosxvxwo",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosxvxwx",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosxvzwo",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="mosxvzwx",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
    ]
