version: 2.1
orbs:
    eslint: arrai/eslint@7.10.1
    prettier: arrai/prettier@5.9.1
    npm: arrai/npm@dev:200
    github: arrai/github@3.0.0
workflows:
    test:
        jobs:
            - npm/coverage:
                  name: tests
                  context:
                      - arrai-global
                  resource_class: medium+
                  filters:
                      branches:
                          only:
                              - main
            - npm/coverage:
                  name: tests-no-badge
                  context:
                      - arrai-global
                  resource_class: medium+
                  create_badges: false
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore:
                              - main
            - npm/publish:
                  name: publish
                  context: arrai-private-package-publishing
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
            - github/create_release:
                  name: release_on_github
                  context: arrai-global
                  requires:
                      - publish
                  filters:
                      tags:
                          only: /.*/
                      branches:
                          ignore: /.*/
    lint:
        jobs:
            - eslint/eslint_fixed_ip:
                  name: eslint
                  context: arrai-global
                  files: "."
                  wd: "."
                  config:
                      - run:
                            name: NPM
                            command: npm ci
                  filters:
                      branches:
                          only:
                              - main
            - eslint/eslint:
                  name: eslint-no-badge
                  context: arrai-global
                  files: "."
                  wd: "."
                  config:
                      - run:
                            name: NPM
                            command: npm ci
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
            - prettier/code_style_fixed_ip:
                  name: prettier
                  context: arrai-global
                  filters:
                      branches:
                          only:
                              - main
            - prettier/code_style:
                  name: prettier-no-badge
                  context: arrai-global
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
    audit:
        jobs:
            - npm/audit_fixed_ip:
                  name: audit
                  context:
                      - arrai-global
                  skip_dev: false
                  filters:
                      branches:
                          only:
                              - main
            - npm/audit:
                  name: audit-no-badge
                  context:
                      - arrai-global
                  skip_dev: false
                  create_badges: false
                  filters:
                      branches:
                          ignore:
                              - main
