# Generated by Django 5.2.15 on 2026-06-29 18:51
# Modified using VUEDA makegroupmigrations command.  Please do not delete this comment.
# Never modify this migration.  It is here for verifying updating works.
import copy
import datetime
import enum

# Stray comment for testing.
from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations


changed_data = [
    {
        "change_type": "associated",
        "group_name": "Admin",
        "group_name_old": "",
        "historical_permission_codename": "read_contenttype",
        "historical_permission_content_type_app_label": "contenttypes",
        "historical_permission_content_type_model_name": "contenttype",
        "historical_permission_name": "Can read content type",
        "when": datetime.datetime(2026, 6, 29, 15, 30, 36, 252716, tzinfo=datetime.timezone.utc),
    },
    {
        "change_type": "associated",
        "group_name": "Admin",
        "group_name_old": "",
        "historical_permission_codename": "list_permission",
        "historical_permission_content_type_app_label": "auth",
        "historical_permission_content_type_model_name": "permission",
        "historical_permission_name": "Can list permissions",
        "when": datetime.datetime(2026, 6, 29, 20, 49, 37, 102038, tzinfo=datetime.timezone.utc),
    },
]

# Stray import 1 for testing.
import os  # noqa: E402, F401


def get_matching_record(change, group_change_model):
    """Return GroupChange.pk if a record matching this change exists, None otherwise."""
    # Need group_change_model since we could be running from a migration.
    obj = group_change_model.objects.filter(
        group_name=change["group_name"],
        group_name_old=change["group_name_old"],
        change_type=change["change_type"],
        when=change["when"],
        historical_permission_codename=change["historical_permission_codename"],
        historical_permission_content_type_app_label=change["historical_permission_content_type_app_label"],
        historical_permission_content_type_model_name=change["historical_permission_content_type_model_name"],
    ).order_by("when")
    if obj.exists():
        return obj.first().pk


def create_group_change(change, group_change_model):
    # Need group_change_model since we could be running from a migration.
    obj = group_change_model.objects.create(
        group_name=change["group_name"],
        group_name_old=change["group_name_old"],
        change_type=change["change_type"],
        historical_permission_codename=change["historical_permission_codename"],
        historical_permission_content_type_app_label=change["historical_permission_content_type_app_label"],
        historical_permission_content_type_model_name=change["historical_permission_content_type_model_name"],
    )
    # auto_now=True prevents setting `when` via create(), so update it directly
    # to preserve the original timestamp from the migration's changed_data.
    obj.when = change["when"]
    obj.save()
    return obj.pk


class GroupChangeTypes(enum.Enum):
    ADDED = "added"
    ASSOCIATED = "associated"
    CHANGED = "changed"
    UNASSOCIATED = "unassociated"
    DELETED = "deleted"


def migrate_step(
    content_types,
    groups,
    permissions,
    group_name,
    group_name_old,
    change_type,
    historical_permission_codename,
    historical_permission_content_type_app_label,
    historical_permission_content_type_model_name,
    historical_permission_name,
):
    group = groups.objects.filter(name=group_name).first()
    group_old = groups.objects.filter(name=group_name_old).first() if group_name_old else None
    permission = permissions.objects.filter(
        codename=historical_permission_codename,
        content_type__app_label=historical_permission_content_type_app_label,
        content_type__model=historical_permission_content_type_model_name,
    ).first()

    # Assume that migrations have been created that create/rename/delete groups and associate/unassociate
    # permissions, so we don't miss doing a step, and leave things incorrect on the machine we're migrating.
    match change_type:
        case GroupChangeTypes.ADDED.value | GroupChangeTypes.ASSOCIATED.value | GroupChangeTypes.CHANGED.value:
            if change_type == GroupChangeTypes.CHANGED.value:
                if group is None and group_old is not None:
                    group_old.name = group_name
                    group_old.save()
                    group = group_old

            elif group is None:
                group = groups.objects.create(name=group_name)

            if permission is None:
                # Hopefully this doesn't happen, but if it does, we should add the permission.
                content_type = content_types.objects.get(
                    app_label=historical_permission_content_type_app_label,
                    model=historical_permission_content_type_model_name,
                )
                permission = permissions.objects.create(
                    codename=historical_permission_codename,
                    content_type=content_type,
                    name=historical_permission_name,
                )

            permission.group_set.add(group)

        case GroupChangeTypes.UNASSOCIATED.value | GroupChangeTypes.DELETED.value:
            if permission is not None and group is not None:
                permission.group_set.remove(group)

            if change_type == GroupChangeTypes.DELETED.value and not group.permissions.exists():
                group.delete()


def forwards_migrate_groups(apps, schema_editor):
    content_types = apps.get_model("contenttypes", "ContentType")
    group_changes = apps.get_model("vueda_user", "GroupChange")
    groups = apps.get_model("auth", "Group")
    permissions = apps.get_model("auth", "Permission")

    # Copied, so tests can migrate forwards and then backwards.
    for changed_item in copy.deepcopy(changed_data):
        group_name = changed_item["group_name"]
        group_name_old = changed_item["group_name_old"]
        change_type = changed_item["change_type"]
        historical_permission_codename = changed_item["historical_permission_codename"]
        historical_permission_content_type_app_label = changed_item["historical_permission_content_type_app_label"]
        historical_permission_content_type_model_name = changed_item["historical_permission_content_type_model_name"]
        historical_permission_name = changed_item["historical_permission_name"]

        migrate_step(
            content_types,
            groups,
            permissions,
            group_name,
            group_name_old,
            change_type,
            historical_permission_codename,
            historical_permission_content_type_app_label,
            historical_permission_content_type_model_name,
            historical_permission_name,
        )

        pk = get_matching_record(changed_item, group_change_model=group_changes)
        if pk is None:
            create_group_change(changed_item, group_change_model=group_changes)


def backwards_migrate_groups(apps, schema_editor):
    content_types = apps.get_model("contenttypes", "ContentType")
    groups = apps.get_model("auth", "Group")
    permissions = apps.get_model("auth", "Permission")

    # Copied and reversed, so tests can migrate backwards and then forwards.
    for changed_item in reversed(copy.deepcopy(changed_data)):
        group_name = changed_item["group_name"]
        group_name_old = changed_item["group_name_old"]
        change_type = changed_item["change_type"]
        historical_permission_codename = changed_item["historical_permission_codename"]
        historical_permission_content_type_app_label = changed_item["historical_permission_content_type_app_label"]
        historical_permission_content_type_model_name = changed_item["historical_permission_content_type_model_name"]
        historical_permission_name = changed_item["historical_permission_name"]

        # Reverse everything
        match change_type:
            case GroupChangeTypes.ADDED.value:
                change_type = GroupChangeTypes.DELETED.value
            case GroupChangeTypes.ASSOCIATED.value:
                change_type = GroupChangeTypes.UNASSOCIATED.value
            case GroupChangeTypes.CHANGED.value:
                old_group_name = group_name_old
                group_name_old = group_name
                group_name = old_group_name
            case GroupChangeTypes.UNASSOCIATED.value:
                change_type = GroupChangeTypes.ASSOCIATED.value
            case GroupChangeTypes.DELETED.value:
                change_type = GroupChangeTypes.ADDED.value

        migrate_step(
            content_types,
            groups,
            permissions,
            group_name,
            group_name_old,
            change_type,
            historical_permission_codename,
            historical_permission_content_type_app_label,
            historical_permission_content_type_model_name,
            historical_permission_name,
        )


def make_sure_permissions_exist(apps, schema_editor):
    # We need to make sure all permissions exist, since the permissions could be for any app.
    for app in django_apps.get_app_configs():
        create_permissions(app, interactive=False)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("confirmation", "0002_gadget"),
        ("erring", "0002_workflow_migrations_2026_03_24"),
        ("group_updating", "0001_initial"),
        ("logging", "0001_initial"),
        ("store", "0008_order_item_formatted_name"),
        ("vueda_release", "0001_initial"),
        ("vueda_user", "0005_sync_group_changes"),
        ("vueda_vdq", "0006_alter_sentitem_options"),
        ("vueda_workflow", "0006_rename_fail_with_silent_historicaltransitionsource_ignored_and_more"),
        ("tests", "0001_initial"),
        ("workflow_updating", "0002_workflow_migrations_2026_06_29"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_groups,
            reverse_code=backwards_migrate_groups,
        ),
    ]


# Stray import 2 for testing.
import sys  # noqa: E402, F401
