# Generated by Django 5.1.7 on 2025-07-07 20:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowDuplicates",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
