# Generated by Django 5.1.7 on 2025-07-07 20:58

from django.db import migrations

from vueda.workflow import custom_migration_operations


SKIPPABLE_ENV_VARIABLE = "migration_skip_workflow_duplicates"


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_duplicates", "0002_workflow_migrations_2025_07_07"),
    ]

    operations = [
        custom_migration_operations.SkippableRunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                ),
                WORKFLOW AS (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'duplicates_workflow'
                )
                INSERT INTO
                    vueda_workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    DATA.id,
                    DATA.code,
                    DATA.name,
                    '2025-01-01 1:00:10',
                    'Migration - 0003_create_state_history_records',
                    '-',
                    DATA.id,
                    SYSTEM_USER.id,
                    WORKFLOW.id
                FROM
                    SYSTEM_USER,
                    WORKFLOW,
                    (
                        SELECT
                            MAX(id) AS id,
                            'delete_1' AS code,
                            'Delete 1' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_1'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'delete_2' AS code,
                            'Delete 2' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_2'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'delete_3' AS code,
                            'Delete 3' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_3'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'delete_4' AS code,
                            'Delete 4' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_4'
                    ) DATA
                ;""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_historicalstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'duplicates_workflow'
                    )
                    AND
                    history_date = '2025-01-01 1:00:10';""",
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                ),
                WORKFLOW AS (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'duplicates_workflow'
                )
                INSERT INTO
                    vueda_workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    DATA.id,
                    DATA.code,
                    DATA.name,
                    '2025-01-01 1:00:11',
                    'Migration - 0003_create_state_history_records',
                    '+',
                    DATA.id,
                    SYSTEM_USER.id,
                    WORKFLOW.id
                FROM
                    SYSTEM_USER,
                    WORKFLOW,
                    (
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'delete_2' AS code,
                            'Delete 2' AS name
                        UNION
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'delete_3' AS code,
                            'Delete 3' AS name
                        UNION
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'delete_4' AS code,
                            'Delete 4' AS name
                        UNION
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'add_1' AS code,
                            'Add 1' AS name
                        UNION
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'add_2' AS code,
                            'Add 2' AS name
                        UNION
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'add_3' AS code,
                            'Add 3' AS name
                        UNION
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'add_4' AS code,
                            'Add 4' AS name
                    ) DATA
                ;""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_historicalstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'duplicates_workflow'
                    )
                    AND
                    history_date = '2025-01-01 1:00:11';""",
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                ),
                WORKFLOW AS (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'duplicates_workflow'
                )
                INSERT INTO
                    vueda_workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    DATA.id,
                    DATA.code,
                    DATA.name,
                    '2025-01-01 1:00:12',
                    'Migration - 0003_create_state_history_records',
                    '~',
                    DATA.id,
                    SYSTEM_USER.id,
                    WORKFLOW.id
                FROM
                    SYSTEM_USER,
                    WORKFLOW,
                    (
                        SELECT
                            MAX(id) AS id,
                            'delete_3a' AS code,
                            'Delete 3A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_3'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'delete_4a' AS code,
                            'Delete 4A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_4'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'add_2a' AS code,
                            'Add 2A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'add_2'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'add_3a' AS code,
                            'Add 3A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'add_3'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'add_4a' AS code,
                            'Add 4A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'add_4'
                    ) DATA
                ;""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_historicalstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'duplicates_workflow'
                    )
                    AND
                    history_date = '2025-01-01 1:00:12';""",
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                ),
                WORKFLOW AS (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'duplicates_workflow'
                )
                INSERT INTO
                    vueda_workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    DATA.id,
                    DATA.code,
                    DATA.name,
                    '2025-01-01 1:00:13',
                    'Migration - 0003_create_state_history_records',
                    '-',
                    DATA.id,
                    SYSTEM_USER.id,
                    WORKFLOW.id
                FROM
                    SYSTEM_USER,
                    WORKFLOW,
                    (
                        SELECT
                            MAX(id) AS id,
                            'delete_4a' AS code,
                            'Delete 4A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'delete_4a'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'add_3a' AS code,
                            'Add 3A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'add_3a'
                        UNION
                        SELECT
                            MAX(id) AS id,
                            'add_4a' AS code,
                            'Add 4A' AS name
                        FROM
                            vueda_workflow_historicalstate
                        WHERE
                            code = 'add_4a'
                    ) DATA
                ;""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_historicalstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'duplicates_workflow'
                    )
                    AND
                    history_date = '2025-01-01 1:00:13';""",
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                ),
                WORKFLOW AS (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'duplicates_workflow'
                )
                INSERT INTO
                    vueda_workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    DATA.id,
                    DATA.code,
                    DATA.name,
                    '2025-01-01 1:00:14',
                    'Migration - 0003_create_state_history_records',
                    '+',
                    DATA.id,
                    SYSTEM_USER.id,
                    WORKFLOW.id
                FROM
                    SYSTEM_USER,
                    WORKFLOW,
                    (
                        SELECT
                            nextval('vueda_workflow_state_id_seq') AS id,
                            'add_4' AS code,
                            'Add 4' AS name
                    ) DATA
                ;""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_historicalstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'duplicates_workflow'
                    )
                    AND
                    history_date = '2025-01-01 1:00:14';""",
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
    ]
