# Generated by Django 5.0.6 on 2024-07-25 16:55

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0001_initial"),
        ("vueda_workflow", "__latest__"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowMulti",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("description"), output_field=models.CharField()
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("priority", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "comments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, default=list, size=None
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, choices=[("office", "office"), ("site", "onsite")], max_length=50),
                ),
                ("execution_window", django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ("age_limit", django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
