# Generated by Django 5.0.6 on 2024-07-25 16:57
from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_multi")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_multi", "0001_initial"),
        ("vueda_workflow", "0002_statepermission_historical_group_name_and_more"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflow
            (
                name,
                code,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'complete task',
                'complete_task',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_multi' AND
                        model = 'workflowmulti'
                ),
                'workflow_multi',
                'workflowmulti'
            )
            """
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflow
            (
                id,
                code,
                name,
                historical_app_label,
                historical_model,
                history_date,
                history_change_reason,
                history_type,
                content_type_id,
                history_relation_id,
                history_user_id
            )
            SELECT
                W.id,
                'complete',
                'complete',
                W.historical_app_label,
                W.historical_model,
                '2024-07-17 13:53:55.857366-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                W.content_type_id,
                W.id,
                SYSTEM_USER.id
            FROM
                vueda_workflow_workflow W,
                SYSTEM_USER
            WHERE
                W.code = 'complete_task';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflow
            (
                id,
                code,
                name,
                historical_app_label,
                historical_model,
                history_date,
                history_change_reason,
                history_type,
                content_type_id,
                history_relation_id,
                history_user_id
            )
            SELECT
                W.id,
                W.code,
                W.name,
                W.historical_app_label,
                W.historical_model,
                '2024-07-17 13:56:47.389397-06',
                'Migration - 0002_create_workflow_and_history',
                '~',
                W.content_type_id,
                W.id,
                SYSTEM_USER.id
            FROM
                vueda_workflow_workflow W,
                SYSTEM_USER
            WHERE
                W.code = 'complete_task';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_state
                (
                    name,
                    code,
                    workflow_id
                )
            VALUES
                (
                    'completed',
                    'completed',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    )
                ),
                (
                    'added',
                    'added',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalstate
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                workflow_id
            )
            SELECT
                S.id,
                'added',
                'added',
                '2024-07-17 13:54:38.071395-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                S.id,
                SYSTEM_USER.id,
                S.workflow_id
            FROM
                vueda_workflow_state S,
                SYSTEM_USER
            WHERE
                S.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                S.code = 'completed';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalstate
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                workflow_id
            )
            SELECT
                S.id,
                S.code,
                S.name,
                '2024-07-17 13:55:31.946812-06',
                'Migration - 0002_create_workflow_and_history',
                '~',
                S.id,
                SYSTEM_USER.id,
                S.workflow_id
            FROM
                vueda_workflow_state S,
                SYSTEM_USER
            WHERE
                S.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                S.code = 'completed';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalstate
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                workflow_id
            )
            SELECT
                S.id,
                S.code,
                S.name,
                '2024-07-17 13:55:46.137049-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                S.id,
                SYSTEM_USER.id,
                S.workflow_id
            FROM
                vueda_workflow_state S,
                SYSTEM_USER
            WHERE
                S.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                S.code = 'added';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'complete_task'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'added'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'complete_task'
                                )
                        )
                    );
            """
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalinitialstate
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                state_id,
                workflow_id
            )
            SELECT
                I.id,
                '2024-07-17 13:54:44.946562-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                I.id,
                SYSTEM_USER.id,
                (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'completed'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'complete_task'
                        )
                ) AS state_id,
                I.workflow_id
            FROM
                vueda_workflow_initialstate I,
                SYSTEM_USER
            WHERE
                I.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                I.state_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'added'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'complete_task'
                        )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalinitialstate
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                state_id,
                workflow_id
            )
            SELECT
                I.id,
                '2024-07-17 13:56:08.104317-06',
                'Migration - 0002_create_workflow_and_history',
                '~',
                I.id,
                SYSTEM_USER.id,
                I.state_id,
                I.workflow_id
            FROM
                vueda_workflow_initialstate I,
                SYSTEM_USER
            WHERE
                I.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                I.state_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'added'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'complete_task'
                        )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_transition
            (
                name,
                code,
                workflow_id,
                target_id
            )
            VALUES
                (
                    'complete',
                    'complete',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'completed'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'complete_task'
                            )
                    )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicaltransition
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                target_id,
                workflow_id
            )
            SELECT
                T.id,
                T.code,
                T.name,
                '2024-07-17 13:56:08.106736-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                T.id,
                SYSTEM_USER.id,
                T.target_id,
                T.workflow_id
            FROM
                vueda_workflow_transition T,
                SYSTEM_USER
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                T.code = 'complete';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflowpermission
                (
                    workflow_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_workflowmulti'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_multi'
                                    AND model = 'workflowmulti'
                        )
                    ),
                    'update_workflowmulti',
                    'workflow_multi',
                    'workflowmulti'
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'create_workflowmulti'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_multi'
                                    AND model = 'workflowmulti'
                        )
                    ),
                    'create_workflowmulti',
                    'workflow_multi',
                    'workflowmulti'
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflowpermission
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                workflow_id
            )
            SELECT
                W.id,
                '2024-07-17 13:57:44.077329-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                W.id,
                SYSTEM_USER.id,
                W.permission_id,
                W.historical_permission_codename,
                W.historical_permission_content_type_app_label,
                W.historical_permission_content_type_model_name,
                W.workflow_id
            FROM
                vueda_workflow_workflowpermission W,
                SYSTEM_USER
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                historical_permission_codename = 'update_workflowmulti';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflowpermission
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                workflow_id
            )
            SELECT
                W.id,
                '2024-07-17 13:57:44.080034-06',
                'Migration - 0002_create_workflow_and_history',
                '+',
                W.id,
                SYSTEM_USER.id,
                W.permission_id,
                W.historical_permission_codename,
                W.historical_permission_content_type_app_label,
                W.historical_permission_content_type_model_name,
                W.workflow_id
            FROM
                vueda_workflow_workflowpermission W,
                SYSTEM_USER
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'complete_task'
                )
                AND
                historical_permission_codename = 'create_workflowmulti';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
