# Generated by Django 5.0.6 on 2024-07-25 16:57
from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_multi")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_multi", "0001_initial"),
        ("vueda_workflow", "__latest__"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflow
            (
                name,
                code,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'complete task',
                'complete_task',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'workflow_multi' AND
                        model = 'workflowmulti'
                ),
                'workflow_multi',
                'workflowmulti'
            )
            """
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_state
                (
                    name,
                    code,
                    workflow_id
                )
            VALUES
                (
                    'completed',
                    'completed',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    )
                ),
                (
                    'added',
                    'added',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'complete_task'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'added'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'complete_task'
                                )
                        )
                    );
            """
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_transition
            (
                name,
                code,
                workflow_id,
                target_id
            )
            VALUES
                (
                    'complete',
                    'complete',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'completed'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'complete_task'
                            )
                    )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflowpermission
                (
                    workflow_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_workflowmulti'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_multi'
                                    AND model = 'workflowmulti'
                        )
                    ),
                    'update_workflowmulti',
                    'workflow_multi',
                    'workflowmulti'
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'complete_task'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'create_workflowmulti'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_multi'
                                    AND model = 'workflowmulti'
                        )
                    ),
                    'create_workflowmulti',
                    'workflow_multi',
                    'workflowmulti'
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
