# Generated by Django 5.1 on 2024-08-12 13:17
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.db import models


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("store")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        apps=apps,
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distributor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1024)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="OptionType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="OrderState",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="SpecialCare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("field_that_contains_the_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="TangibleType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("reserved_delivery_time", models.DateTimeField(null=True)),
                ("reserved_until", models.TimeField(null=True)),
                ("expected_delivery_time", models.DurationField(null=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.customer")),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ["customer__user__name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.DecimalField(decimal_places=0, max_digits=7)),
                ("when", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date / Time")),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        choices=[("free", "Free"), ("regular", "Regular"), ("express", "Express")],
                        max_length=255,
                    ),
                ),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.customer")),
                ("order_state", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.orderstate")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            models.F("order_number"), output_field=models.CharField()
                        ),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "permissions": [("fulfill_orders", "Can fulfill orders")],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCustomer",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="store.customer",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical customer",
                "verbose_name_plural": "historical customers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDistributor",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1024)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="store.distributor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "verbose_name": "historical distributor",
                "verbose_name_plural": "historical distributors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InventoryRecordReason",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Reason")),
                ("code", models.CharField(db_index=True, max_length=255)),
                ("is_added_reason", models.BooleanField(db_index=True)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "inventory_record_reason",
                "unique_together": {("code", "is_added_reason")},
                "verbose_name": "inventory entry reason",
                "verbose_name_plural": "inventory entry reasons",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCustomerOrder",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("order_number", models.DecimalField(decimal_places=0, max_digits=7)),
                ("when", models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name="Date / Time")),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True,
                        choices=[("free", "Free"), ("regular", "Regular"), ("express", "Express")],
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="store.customer",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="store.customerorder",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_state",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="store.orderstate",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            models.F("order_number"), output_field=models.CharField()
                        ),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "verbose_name": "historical customer order",
                "verbose_name_plural": "historical customer orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("disabled", models.BooleanField(db_default=False)),
                ("distributor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.distributor")),
                ("order_between", django.contrib.postgres.fields.ranges.IntegerRangeField()),
                (
                    "last_ten_order_betweens",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ranges.IntegerRangeField(), null=True, size=None
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("current_sale_date", django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                (
                    "future_sale_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ranges.DateRangeField(), null=True, size=None
                    ),
                ),
                (
                    "reviews",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2048), blank=True, default=list, size=None
                    ),
                ),
                (
                    "internal_comments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("last_ordered", models.DateField(null=True)),
                ("quantity", models.IntegerField(db_default=0)),
                ("special_care", models.ManyToManyField(blank=True, to="store.specialcare")),
                (
                    "tangible_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.tangibletype"),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "ordering": ["name"],
                "unique_together": {("distributor", "name")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("disabled", models.BooleanField(db_default=False)),
                ("order_between", django.contrib.postgres.fields.ranges.IntegerRangeField()),
                (
                    "last_ten_order_betweens",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ranges.IntegerRangeField(), null=True, size=None
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("current_sale_date", django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                (
                    "future_sale_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ranges.DateRangeField(), null=True, size=None
                    ),
                ),
                (
                    "reviews",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2048), blank=True, default=list, size=None
                    ),
                ),
                (
                    "internal_comments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("last_ordered", models.DateField(null=True)),
                ("quantity", models.IntegerField(db_default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="store.distributor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="store.product",
                    ),
                ),
                (
                    "tangible_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="store.tangibletype",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=255, verbose_name="SKU")),
                ("gtin", models.CharField(max_length=255, unique=True, verbose_name="GTIN")),
                ("price", models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ("disabled", models.BooleanField(db_default=False)),
                ("quantity_available", models.IntegerField(db_default=0)),
                (
                    "option_type",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="store.optiontype"),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.product")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "product_options",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.IntegerField(
                        db_default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "customer_order",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.customerorder"),
                ),
                (
                    "product_option",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.productoption"),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "order_items",
                "verbose_name": "ORDER item",
                "verbose_name_plural": "ORDER items",
            },
        ),
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("when", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date / Time")),
                (
                    "quantity",
                    models.IntegerField(db_default=0, validators=[django.core.validators.StepValueValidator(6)]),
                ),
                ("archived", models.BooleanField(db_default=False, db_index=True)),
                ("is_added", models.BooleanField(db_index=True)),
                ("cost", models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ("margin", models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                (
                    "added_inventory_record",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.inventoryrecord",
                        verbose_name="Added Inventory Entry",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.inventoryrecordreason"),
                ),
                (
                    "order_item",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="store.orderitem"),
                ),
                (
                    "product_option",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.productoption"),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "verbose_name": "inventory entry",
                "verbose_name_plural": "inventory entries",
            },
        ),
        migrations.CreateModel(
            name="HistoricalProductOption",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=255, verbose_name="SKU")),
                ("gtin", models.CharField(db_index=True, max_length=255, verbose_name="GTIN")),
                ("price", models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ("disabled", models.BooleanField(db_default=False)),
                ("quantity_available", models.IntegerField(db_default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "option_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="store.optiontype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="store.product",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="store.productoption",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product option",
                "verbose_name_plural": "historical product options",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(db_default=0)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.cart")),
                (
                    "product_option",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="store.productoption"),
                ),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "cart_items",
            },
        ),
        migrations.CreateModel(
            name="PackingBox",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("depth", models.DecimalField(decimal_places=4, max_digits=12)),
                ("height", models.DecimalField(decimal_places=4, max_digits=12)),
                ("width", models.DecimalField(decimal_places=4, max_digits=12)),
                ("carrying_weight", models.DecimalField(decimal_places=4, max_digits=12)),
                ("in_stock", models.BooleanField(db_default=False)),
                ("number_in_stock", models.IntegerField(db_default=0)),
            ],
            options={
                "verbose_name": "Packing Box",
                "verbose_name_plural": "Packing Boxes",
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("name"),
                        output_field=models.CharField(),
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("name"),
                        output_field=models.CharField(),
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_lines",
                        to="store.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="OrderCompositePK",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.DecimalField(decimal_places=0, max_digits=7)),
                ("order_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Cast(
                            models.F("order_number"), output_field=models.CharField()
                        ),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "ordering": ["order_number"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="ProductCompositePK",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("name"),
                        output_field=models.CharField(),
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="OrderItemCompositePK",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "order_id",
                        "product_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        db_default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.ordercompositepk",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.productcompositepk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Items Composite PK",
                "verbose_name_plural": "Order Items Composite PKs",
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "order_items_composite_pks",
            },
        ),
        migrations.CreateModel(
            name="OrderItemAltCompositePK",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "order_id",
                        "product_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        db_default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.ordercompositepk",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.productcompositepk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Items Alt Composite PK",
                "verbose_name_plural": "Order Items Alt Composite PKs",
                "ordering": ["order", "product", "quantity"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "order_items_alt_composite_pks",
            },
        ),
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group
                (
                    name
                )
            VALUES
                (
                    'Admin'
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group_permissions
                (
                    group_id,
                    permission_id
                )
            VALUES
                (
                    (SELECT id FROM auth_group WHERE name = 'Admin'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_orderitem'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'orderitem'
                        )
                    )
                );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
