# Generated by Django 5.0.3 on 2024-03-22 16:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "cart_items",
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
