# Generated by Django 5.1 on 2024-08-12 16:26
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
import copy
import datetime
import enum

from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.db.models import Count
from django.utils import timezone


history_change_reason = "Workflow Migration - 0002_workflow_migrations_2024_08_13"
migration_app_label = "store"
changed_data = [
    {
        "changes": {
            "code": "order_fulfillment",
            "content_type_id": {"app_label": "store", "model": "customerorder"},
            "historical_app_label": "store",
            "historical_model": "customerorder",
            "id": {"code": "order_fulfillment"},
            "name": "Order Fulfillment",
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 8, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "code": "new",
            "id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
            "name": "New",
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 9, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "packed",
            "id": {"code": "packed", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Packed",
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 10, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "returned",
            "id": {"code": "returned", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Returned",
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 11, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "shipped",
            "id": {"code": "shipped", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Shipped",
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 12, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "on_hold",
            "id": {"code": "on_hold", "workflow_id": {"code": "order_fulfillment"}},
            "name": "On Hold",
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 13, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "cancelled",
            "id": {"code": "cancelled", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Cancelled",
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 14, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
                "workflow_id": {"code": "order_fulfillment"},
            },
            "state_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 15, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "cancel_order",
            "id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Cancel Order",
            "target_id": {"code": "cancelled", "workflow_id": {"code": "order_fulfillment"}},
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 16, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "hold_order",
            "id": {"code": "hold_order", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Hold Order",
            "target_id": {"code": "on_hold", "workflow_id": {"code": "order_fulfillment"}},
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 17, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "pack_order",
            "id": {"code": "pack_order", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Pack Order",
            "target_id": {"code": "packed", "workflow_id": {"code": "order_fulfillment"}},
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 18, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "return_order",
            "id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Return Order",
            "target_id": {"code": "returned", "workflow_id": {"code": "order_fulfillment"}},
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 19, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "ship_order",
            "id": {"code": "ship_order", "workflow_id": {"code": "order_fulfillment"}},
            "name": "Ship Order",
            "target_id": {"code": "shipped", "workflow_id": {"code": "order_fulfillment"}},
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 20, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "fulfill_orders",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "fulfill_orders",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "workflow_id": {"code": "order_fulfillment"},
            },
            "permission_id": {
                "codename": "fulfill_orders",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 21, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "delete_customerorder",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "delete_customerorder",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "workflow_id": {"code": "order_fulfillment"},
            },
            "permission_id": {
                "codename": "delete_customerorder",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "workflow_id": {"code": "order_fulfillment"},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 22, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "grant_or_deny": False,
            "group_id": {"name": "Admin"},
            "historical_group_name": "Admin",
            "historical_permission_codename": "update_orderitem",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "orderitem",
            "id": {
                "group_id": {"name": "Admin"},
                "historical_group_name": "Admin",
                "historical_permission_codename": "update_orderitem",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "orderitem",
                "state_id": {"code": "shipped", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "update_orderitem",
                "content_type_id": {"app_label": "store", "model": "orderitem"},
            },
            "state_id": {"code": "shipped", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 23, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "statepermission",
    },
    {
        "changes": {
            "historical_permission_codename": "fulfill_orders",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "fulfill_orders",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "fulfill_orders",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 24, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "fulfill_orders",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "fulfill_orders",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "hold_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "fulfill_orders",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "hold_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 25, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "fulfill_orders",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "fulfill_orders",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "pack_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "fulfill_orders",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "pack_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 26, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "fulfill_orders",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "fulfill_orders",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "ship_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "fulfill_orders",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "ship_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 27, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "fulfill_orders",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "fulfill_orders",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "fulfill_orders",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 28, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "delete_customerorder",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "delete_customerorder",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "delete_customerorder",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 29, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "delete_customerorder",
            "historical_permission_content_type_app_label": "store",
            "historical_permission_content_type_model_name": "customerorder",
            "id": {
                "historical_permission_codename": "delete_customerorder",
                "historical_permission_content_type_app_label": "store",
                "historical_permission_content_type_model_name": "customerorder",
                "transition_id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "permission_id": {
                "codename": "delete_customerorder",
                "content_type_id": {"app_label": "store", "model": "customerorder"},
            },
            "transition_id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 30, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 31, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "hold_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "hold_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 32, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "pack_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "new", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "pack_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 33, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "packed", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "ship_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "packed", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "ship_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 34, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "packed", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "packed", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 35, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "on_hold", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "on_hold", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 36, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "shipped", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
            },
            "source_id": {"code": "shipped", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "return_order", "workflow_id": {"code": "order_fulfillment"}},
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 37, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "cancelled", "workflow_id": {"code": "order_fulfillment"}},
                "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
                "ignored": True,
            },
            "source_id": {"code": "cancelled", "workflow_id": {"code": "order_fulfillment"}},
            "transition_id": {"code": "cancel_order", "workflow_id": {"code": "order_fulfillment"}},
            "ignored": True,
        },
        "history_date": datetime.datetime(2024, 8, 12, 16, 25, 37, 618729, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
]


def forwards_migrate_workflow_through_imports(apps, schema_editor):  # pragma: no cover
    # Copied, so tests can migrate forwards and backwards.
    forwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def backwards_migrate_workflow_through_imports(apps, schema_editor):  # pragma: no cover
    # Copied, so tests can migrate forwards and backwards.
    backwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def make_sure_permissions_exist_through_imports(apps, schema_editor):  # pragma: no cover
    make_sure_permissions_exist(migration_app_label)


class WorkflowChangeTypes(enum.Enum):
    ADDED = "added"
    CHANGED = "changed"
    DELETED = "deleted"


def forwards_migrate_workflow(apps, changed_items, change_reason):
    for changed_item in changed_items:
        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, change_reason)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, change_reason)

            case "state":
                handle_state(apps, changed_item, change_reason)

            case "statepermission":
                handle_state_permission(apps, changed_item, change_reason)

            case "initialstate":
                handle_initial_state(apps, changed_item, change_reason)

            case "transition":
                handle_transition(apps, changed_item, change_reason)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, change_reason)

            case "transitionsource":
                handle_transition_source(apps, changed_item, change_reason)

    handle_state_objects(apps)


def backwards_migrate_workflow(apps, changed_items, change_reason):
    handle_state_objects(apps, reversing=True)

    # Make sure we go through the changed_items in reverse order, so we undo things correctly.
    for changed_item in reversed(changed_items):
        match changed_item["history_type"]:
            case WorkflowChangeTypes.ADDED.value:
                changed_item["history_type"] = WorkflowChangeTypes.DELETED.value

            case WorkflowChangeTypes.DELETED.value:
                changed_item["history_type"] = WorkflowChangeTypes.ADDED.value

        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, change_reason, reversing=True)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, change_reason, reversing=True)

            case "state":
                handle_state(apps, changed_item, change_reason, reversing=True)

            case "statepermission":
                handle_state_permission(apps, changed_item, change_reason, reversing=True)

            case "initialstate":
                handle_initial_state(apps, changed_item, change_reason, reversing=True)

            case "transition":
                handle_transition(apps, changed_item, change_reason, reversing=True)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, change_reason, reversing=True)

            case "transitionsource":
                handle_transition_source(apps, changed_item, change_reason, reversing=True)


def make_sure_permissions_exist(app_label):
    app = django_apps.get_app_config(app_label)
    create_permissions(app, interactive=False)


def handle_workflow(apps, changed_item, change_reason, *, reversing=False):
    historical_workflow = apps.get_model("vueda_workflow", "HistoricalWorkflow")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            del data["id"]  # This needs to be removed before we create.

            workflow = model_workflow.objects.create(**data)

            add_history_to_data(
                data,
                workflow,
                "+",
                changed_item["history_date"],
                change_reason,
            )
            historical_workflow.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(workflow, data, reversing=reversing)
            add_history_to_data(
                data,
                workflow,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "code",
                    "content_type_id",
                    "historical_app_label",
                    "historical_model",
                    "name",
                ),
            )
            historical_workflow.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            workflow = model_workflow.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow, "-", changed_item["history_date"], change_reason)
            historical_workflow.objects.create(**data)
            workflow.delete()


def handle_workflow_permission(apps, changed_item, change_reason, *, reversing=False):
    historical_workflow_permission = apps.get_model("vueda_workflow", "HistoricalWorkflowPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")
    model_workflow_permission = apps.get_model("vueda_workflow", "WorkflowPermission")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            workflow_permission = model_workflow_permission.objects.create(**data)

            add_history_to_data(data, workflow_permission, "+", changed_item["history_date"], change_reason)
            historical_workflow_permission.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            apply_and_save_changes(workflow_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                workflow_permission,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "workflow_id",
                ),
            )
            historical_workflow_permission.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow_permission, "-", changed_item["history_date"], change_reason)
            historical_workflow_permission.objects.create(**data)
            workflow_permission.delete()


def handle_state(apps, changed_item, change_reason, *, reversing=False):
    historical_state = apps.get_model("vueda_workflow", "HistoricalState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            state = model_state.objects.create(**data)

            add_history_to_data(data, state, "+", changed_item["history_date"], change_reason)
            historical_state.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(state, data, reversing=reversing)
            add_history_to_data(
                data,
                state,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "code",
                    "name",
                    "workflow_id",
                ),
            )
            historical_state.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            state = model_state.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state, "-", changed_item["history_date"], change_reason)
            historical_state.objects.create(**data)
            state.delete()


def handle_state_permission(apps, changed_item, change_reason, *, reversing=False):
    historical_state_permission = apps.get_model("vueda_workflow", "HistoricalStatePermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_group = apps.get_model("auth", "Group")
    model_permission = apps.get_model("auth", "Permission")
    model_state = apps.get_model("vueda_workflow", "State")
    model_state_permission = apps.get_model("vueda_workflow", "StatePermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["group_id"])
            data["group_id"] = group.pk

            del data["id"]  # This needs to be removed before we create.

            state_permission = model_state_permission.objects.create(**data)

            add_history_to_data(data, state_permission, "+", changed_item["history_date"], change_reason)
            historical_state_permission.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            group = model_group.objects.get(**get_id_values_from_item(data["id"]["group_id"], reversing=reversing))
            data["id"]["group_id"] = group.pk
            state_permission = model_state_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["group_id"]) is tuple:
                new_group_ids = []
                for group_id in data["group_id"]:
                    group = model_group.objects.get(**group_id)
                    new_group_ids.append(group.pk)
                data["group_id"] = tuple(new_group_ids)

            apply_and_save_changes(state_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                state_permission,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "grant_or_deny",
                    "group_id",
                    "historical_group_name",
                    "historical_permission_codename",
                    "permission_id",
                    "state_id",
                ),
            )
            historical_state_permission.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["id"]["group_id"])
            data["id"]["group_id"] = group.pk
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state_permission, "-", changed_item["history_date"], change_reason)
            historical_state_permission.objects.create(**data)
            state_permission.delete()


def handle_initial_state(apps, changed_item, change_reason, *, reversing=False):
    historical_initial_state = apps.get_model("vueda_workflow", "HistoricalInitialState")
    model_initial_state = apps.get_model("vueda_workflow", "InitialState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])

            data["state_id"] = state.pk
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            initial_state = model_initial_state.objects.create(**data)

            add_history_to_data(data, initial_state, "+", changed_item["history_date"], change_reason)
            historical_initial_state.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            data["id"]["state_id"] = get_id_values_from_item(data["id"]["state_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["state_id"]) is tuple:
                state_ids = []
                for state_data in data["state_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["state_id"] = tuple(state_ids)

            apply_and_save_changes(initial_state, data, reversing=reversing)
            add_history_to_data(
                data,
                initial_state,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "state_id",
                    "workflow_id",
                ),
            )
            historical_initial_state.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            add_history_to_data(data, initial_state, "-", changed_item["history_date"], change_reason)
            historical_initial_state.objects.create(**data)
            initial_state.delete()


def handle_transition(apps, changed_item, change_reason, *, reversing=False):
    historical_transition = apps.get_model("vueda_workflow", "HistoricalTransition")
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            del data["id"]  # This needs to be removed before we create.

            transition = model_transition.objects.create(**data)

            add_history_to_data(data, transition, "+", changed_item["history_date"], change_reason)
            historical_transition.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["target_id"]) is tuple:
                state_ids = []
                for state_data in data["target_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["target_id"] = tuple(state_ids)

            apply_and_save_changes(transition, data, reversing=reversing)
            add_history_to_data(
                data,
                transition,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "code",
                    "name",
                    "target_id",
                    "workflow_id",
                ),
            )
            historical_transition.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition, "-", changed_item["history_date"], change_reason)
            historical_transition.objects.create(**data)
            transition.delete()


def handle_transition_permission(apps, changed_item, change_reason, *, reversing=False):
    historical_transition_permission = apps.get_model("vueda_workflow", "HistoricalTransitionPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_permission = apps.get_model("vueda_workflow", "TransitionPermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            transition_permission = model_transition_permission.objects.create(**data)

            add_history_to_data(data, transition_permission, "+", changed_item["history_date"], change_reason)
            historical_transition_permission.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    state = model_transition.objects.get(**transition_data)
                    transition_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                transition_permission,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "transition_id",
                ),
            )
            historical_transition_permission.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_permission, "-", changed_item["history_date"], change_reason)
            historical_transition_permission.objects.create(**data)
            transition_permission.delete()


def handle_transition_source(apps, changed_item, change_reason, *, reversing=False):
    historical_transition_source = apps.get_model("vueda_workflow", "HistoricalTransitionSource")
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_source = apps.get_model("vueda_workflow", "TransitionSource")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["source_id"]["workflow_id"])
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["source_id"])
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            transition_source = model_transition_source.objects.create(**data)

            add_history_to_data(data, transition_source, "+", changed_item["history_date"], change_reason)
            historical_transition_source.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            data["id"]["source_id"] = get_id_values_from_item(data["id"]["source_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk

            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["source_id"]) is tuple:
                state_ids = []
                for state_data in data["source_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                data["source_id"] = tuple(state_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    transition = model_transition.objects.get(**transition_data)
                    transition_ids.append(transition.pk)
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_source, data, reversing=reversing)
            add_history_to_data(
                data,
                transition_source,
                "~",
                changed_item["history_date"],
                change_reason,
                fields=(
                    "id",
                    "source_id",
                    "transition_id",
                    "ignored",
                ),
            )
            historical_transition_source.objects.create(**data)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_source, "-", changed_item["history_date"], change_reason)
            historical_transition_source.objects.create(**data)
            transition_source.delete()


def handle_state_objects(apps, *, reversing=False):
    model_historical_object_state = apps.get_model("vueda_workflow", "HistoricalObjectState")
    model_object_state = apps.get_model("vueda_workflow", "ObjectState")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    for workflow in model_workflow.objects.all():
        model_obj = apps.get_model(workflow.historical_app_label, workflow.historical_model)
        manage_state_objects(
            workflow, model_obj, model_object_state, model_historical_object_state, reversing=reversing
        )


def manage_state_objects(
    workflow, obj_class, workflow_obj_state_class, historical_workflow_obj_state_class, *, reversing=False
):
    if reversing:
        # Delete all object states
        workflow_obj_state_class.objects.filter(workflow=workflow).delete()

    else:
        initial_state = workflow.initial_state
        for obj in obj_class.objects.all():
            if not workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk).exists():
                historical_records = historical_workflow_obj_state_class.objects.filter(
                    workflow=workflow,
                    object_id=obj.pk,
                )
                original_historical_records_count = historical_records.count()
                obj_state_obj = workflow_obj_state_class.objects.create(
                    workflow=workflow,
                    object_id=obj.id,
                    state=initial_state.state,
                )
                # We are running through a migration, so we need to create history.
                if original_historical_records_count == historical_records.count():
                    historical_workflow_obj_state_class.objects.create(
                        id=obj_state_obj.pk,
                        workflow=workflow,
                        object_id=obj.pk,
                        state=initial_state.state,
                        history_date=timezone.now(),
                        history_relation=obj_state_obj,
                        history_type="+",
                    )
            else:
                # If a workflow's initial state has changed, and an object
                # hasn't been changed, then switch it to the new initial state.
                obj_state = (
                    workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk)
                    .exclude(state_id=initial_state.state_id)
                    .first()
                )
                if obj_state is not None:
                    # TODO: When this is switched to django-pghistory, we will need to add context before the
                    #   ObjectState update, so we can use that to know the object state hasn't been changed,
                    #   since it is possible for the initial state on a workflow to change multiple times.
                    history_count = historical_workflow_obj_state_class.objects.filter(
                        workflow=workflow, object_id=obj.pk
                    ).aggregate(count=Count("history_id"))
                    if history_count is not None and history_count["count"] == 1:
                        workflow_obj_state_class.objects.filter(pk=obj_state.pk).update(state_id=initial_state.state_id)
                        historical_workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk).update(
                            state_id=initial_state.state_id
                        )


def add_history_to_data(history_data, obj, history_type, history_date, change_reason, fields=()):
    # For changed history
    for field_name in fields:
        history_data[field_name] = getattr(obj, field_name)

    # For all history
    history_data["history_change_reason"] = change_reason
    history_data["history_date"] = history_date
    history_data["history_relation_id"] = obj.pk
    history_data["history_type"] = history_type
    history_data["id"] = obj.pk


def apply_and_save_changes(obj, data, *, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    for key, values in data.items():
        if type(values) is not tuple:
            continue

        old_value, new_value = values

        if reversing:
            setattr(obj, key, old_value)

        else:
            setattr(obj, key, new_value)

    obj.save()


def get_id_values_from_item(values, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    if type(values) is tuple:
        return values[1 if reversing else 0]

    return values


def get_id_values_from_dict(id_data, reversing=False):
    results = {}
    for field_name, values in id_data.items():
        results[field_name] = get_id_values_from_item(values, reversing)

    return results


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vueda_user", "0002_initial"),
        ("vueda_workflow", "__latest__"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist_through_imports,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow_through_imports,
            reverse_code=backwards_migrate_workflow_through_imports,
        ),
    ]
