# Generated by Django 5.0.3 on 2024-03-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_cartitem_options_cart_last_modified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoption",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "product_options",
            },
        ),
    ]
