# Generated by Django 5.1 on 2024-08-13 17:18

from django.db import migrations


def create_distributors(apps, schema_editor):
    Distributor = apps.get_model("store", "Distributor")

    for data in (
        {"name": "T-Shirt Corp.", "description": "Shirts For The World. From The Vibrant T-Shirt To The Hoodie."},
        {
            "name": "Tasty Treats Assoc.",
            "description": "Treat Yourself To Glorious Sugar. Tasty Treats Will Sprinkle Your Mind With Sugar.",
        },
        {
            "name": "Vibrant Looks Inc.",
            "description": "A Sprinkle Of Vibrant Colour In Your Life. Expect The Best Vibrant Looks Available.",
        },
        {"name": "Treat King LLC.", "description": "Treat Yourself And Get Some Sugary Goodness."},
    ):
        Distributor.objects.create(**data)


def create_inventory_record_reasons(apps, schema_editor):
    InventoryRecordReason = apps.get_model("store", "InventoryRecordReason")

    for data in (
        {
            "name": "Damaged Inventory",
            "code": "damaged_inventory",
            "is_added_reason": False,
        },
        {
            "name": "Order Fulfillment",
            "code": "order_fulfillment",
            "is_added_reason": False,
        },
        {
            "name": "Received Inventory",
            "code": "received_inventory",
            "is_added_reason": True,
        },
        {
            "name": "Returned Inventory",
            "code": "returned_inventory",
            "is_added_reason": True,
        },
    ):
        InventoryRecordReason.objects.create(**data)


def create_option_types(apps, schema_editor):
    OptionType = apps.get_model("store", "OptionType")

    for data in (
        {
            "name": "Size",
            "code": "size",
        },
        {
            "name": "Colour",
            "code": "colour",
        },
        {
            "name": "Flavour",
            "code": "flavour",
        },
    ):
        OptionType.objects.create(**data)


def create_order_states(apps, schema_editor):
    OrderState = apps.get_model("store", "OrderState")

    for data in (
        {
            "name": "New",
            "code": "new",
        },
        {
            "name": "Packed",
            "code": "packed",
        },
        {
            "name": "Returned",
            "code": "returned",
        },
        {
            "name": "Shipped",
            "code": "shipped",
        },
    ):
        OrderState.objects.create(**data)


def create_special_care(apps, schema_editor):
    SpecialCare = apps.get_model("store", "SpecialCare")

    for data in (
        {
            "code": "alcohol",
            "field_that_contains_the_name": "Alcohol",
        },
        {
            "code": "dangerous",
            "field_that_contains_the_name": "Dangerous",
        },
        {
            "code": "fragile",
            "field_that_contains_the_name": "Fragile",
        },
        {
            "code": "oversized",
            "field_that_contains_the_name": "Oversized",
        },
        {
            "code": "perishable",
            "field_that_contains_the_name": "Perishable",
        },
        {
            "code": "temperature_controlled",
            "field_that_contains_the_name": "Temperature Controlled",
        },
    ):
        SpecialCare.objects.create(**data)


def create_tangible_types(apps, schema_editor):
    TangibleType = apps.get_model("store", "TangibleType")

    for data in (
        {
            "code": "digital",
            "name": "Digital",
        },
        {
            "code": "physical",
            "name": "Physical",
        },
    ):
        TangibleType.objects.create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_workflow_migrations_2024_08_13"),
    ]

    operations = [
        migrations.RunPython(
            code=create_distributors,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_inventory_record_reasons,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_option_types,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_order_states,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_special_care,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=create_tangible_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
