# Generated by Django 5.0.3 on 2024-04-08 2:00
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("store")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_productoption_options"),
        ("vueda_workflow", "0004_historicalstatepermission_historical_permission_codename_and_more"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflow
            (
                name,
                code,
                content_type_id,
                historical_app_label,
                historical_model
            )
            VALUES
            (
                'Order Fulfillment',
                'order_fulfillment',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'store' AND
                        model = 'customerorder'
                ),
                'store',
                'customerorder'
            );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_workflow
            WHERE
                code = 'order_fulfillment';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group
                (
                    name
                )
            VALUES
                (
                    'Admin'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group
            WHERE
                name = 'Admin';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group_permissions
                (
                    group_id,
                    permission_id
                )
            VALUES
                (
                    (SELECT id FROM auth_group WHERE name = 'Admin'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_orderitem'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'orderitem'
                        )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group_permissions
            WHERE
                group_id IN (
                    SELECT
                        id
                    FROM
                        auth_group
                    WHERE
                        name = 'Admin'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflowpermission
                (
                    workflow_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name
                )
            VALUES
                (
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'fulfill_orders'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'fulfill_orders',
                    'store',
                    'customerorder'
                ),
                (
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'delete_customerorder'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'delete_customerorder',
                    'store',
                    'customerorder'
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_workflowpermission
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'order_fulfillment'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_state
                (
                    name,
                    code,
                    workflow_id
                )
            VALUES
                (
                    'New',
                    'new',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment')
                ),
                (
                    'Packed',
                    'packed',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment')
                ),
                (
                    'Returned',
                    'returned',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment')
                ),
                (
                    'Shipped',
                    'shipped',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment')
                ),
                (
                    'On Hold',
                    'on_hold',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment')
                ),
                (
                    'Cancelled',
                    'cancelled',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment')
                );""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_state
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'order_fulfillment'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    vueda_workflow_initialstate
                    (
                        workflow_id,
                        state_id
                    )
                VALUES
                    (
                        (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'new'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'order_fulfillment'
                                )
                        )
                    );""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_initialstate
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'order_fulfillment'
                    );""",
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO
                    vueda_workflow_statepermission
                    (
                        state_id,
                        permission_id,
                        historical_permission_codename,
                        historical_permission_content_type_app_label,
                        historical_permission_content_type_model_name,
                        group_id,
                        historical_group_name,
                        grant_or_deny
                    )
                VALUES
                    (
                        (
                            SELECT
                                id
                            FROM
                                vueda_workflow_state
                            WHERE
                                code = 'shipped'
                                AND workflow_id = (
                                    SELECT
                                        id
                                    FROM
                                        vueda_workflow_workflow
                                    WHERE
                                        code = 'order_fulfillment'
                                )
                        ),
                        (
                            SELECT
                                id
                            FROM
                                auth_permission
                            WHERE
                                codename = 'update_orderitem'
                                AND content_type_id = (
                                    SELECT
                                        id
                                    FROM
                                        django_content_type
                                    WHERE
                                        app_label = 'store'
                                        AND model = 'orderitem'
                            )
                        ),
                        'update_orderitem',
                        'store',
                        'orderitem',
                        (SELECT id FROM auth_group WHERE name = 'Admin'),
                        'Admin',
                        FALSE
                    );""",
            reverse_sql="""
                DELETE FROM
                    vueda_workflow_statepermission
                WHERE
                    state_id IN (
                        SELECT
                            S.id
                        FROM
                            vueda_workflow_state S
                        JOIN
                            vueda_workflow_workflow W ON S.workflow_id = W.id
                        WHERE
                            W.code = 'order_fulfillment'
                    )
                    AND
                    historical_permission_codename = 'update_orderitem'
                    AND
                    historical_permission_content_type_app_label = 'store',
                    AND
                    historical_permission_content_type_model_name = 'orderitem'
                    AND
                    historical_group_name = 'Admin';""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO vueda_workflow_transition (name, code, workflow_id, target_id)
            VALUES
                (
                    'Cancel Order',
                    'cancel_order',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'cancelled'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    'Hold Order',
                    'hold_order',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'on_hold'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    'Pack Order',
                    'pack_order',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'packed'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    'Return Order',
                    'return_order',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'returned'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    'Ship Order',
                    'ship_order',
                    (SELECT id FROM vueda_workflow_workflow WHERE code = 'order_fulfillment'),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'shipped'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_transition
            WHERE
                workflow_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'order_fulfillment'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_transitionpermission
                (
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    transition_id
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'fulfill_orders'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'fulfill_orders',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'cancel_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'fulfill_orders'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'fulfill_orders',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'hold_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'fulfill_orders'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'fulfill_orders',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'pack_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'fulfill_orders'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'fulfill_orders',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'ship_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'fulfill_orders'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'fulfill_orders',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'return_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'delete_customerorder'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'delete_customerorder',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'cancel_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'delete_customerorder'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'store'
                                    AND model = 'customerorder'
                        )
                    ),
                    'delete_customerorder',
                    'store',
                    'customerorder',
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'return_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_transitionpermission
            WHERE
                transition_id IN (
                    SELECT
                        T.id
                    FROM
                        workflow_transition T
                    JOIN
                        vueda_workflow_workflow W ON T.workflow_id = W.id
                    WHERE
                        W.code = 'order_fulfillment'
                );""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_transitionsource
                (
                    transition_id,
                    source_id
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'cancel_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'new'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'hold_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'new'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'pack_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'new'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'ship_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'packed'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'cancel_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'packed'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'cancel_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'on_hold'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                ),
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_transition
                        WHERE
                            code = 'return_order'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    ),
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_state
                        WHERE
                            code = 'shipped'
                            AND workflow_id = (
                                SELECT
                                    id
                                FROM
                                    vueda_workflow_workflow
                                WHERE
                                    code = 'order_fulfillment'
                            )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                vueda_workflow_transitionsource
            WHERE
                transition_id IN (
                    SELECT
                        T.id
                    FROM
                        vueda_workflow_transition T
                    JOIN
                        vueda_workflow_workflow W ON T.workflow_id = W.id
                    WHERE
                        W.code = 'order_fulfillment'
                );""",
        ),
    ]
