# Generated by Django 5.0.3 on 2024-03-26 17:13
from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_content_types_exist_and_permissions(apps, schema_editor):
    app = django_apps.get_app_config("store")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_productoption_options"),
    ]

    operations = [
        migrations.RunPython(make_sure_content_types_exist_and_permissions, reverse_code=migrations.RunPython.noop),
    ]
