# Generated by Django 5.1 on 2024-09-20 20:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_setup_lookup_test_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "cart_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CartItemData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "cart_item_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "customer_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryRecordData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "inventory_record_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItemData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "order_item_data",
                "managed": False,
            },
        ),
    ]
