# Generated by Django 5.0.4 on 2024-05-01 22:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_create_order_fulfillment_workflow"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicalinitialstate
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    state_id,
                    workflow_id
                )
                SELECT
                    I.id,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    I.id,
                    SYSTEM_USER.id,
                    I.state_id,
                    I.workflow_id
                FROM
                    vueda_workflow_initialstate I,
                    SYSTEM_USER
                WHERE
                    I.workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'order_fulfillment'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicalstate
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    workflow_id
                )
                SELECT
                    S.id,
                    S.code,
                    S.name,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    S.id,
                    SYSTEM_USER.id,
                    S.workflow_id
                FROM
                    vueda_workflow_state S,
                    SYSTEM_USER
                WHERE
                    S.workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'order_fulfillment'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicalstatepermission
                (
                    id,
                    grant_or_deny,
                    history_date,
                    history_change_reason,
                    history_type,
                    group_id,
                    history_relation_id,
                    history_user_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    historical_group_name,
                    state_id
                )
                SELECT
                    S.id,
                    S.grant_or_deny,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    S.group_id,
                    S.id,
                    SYSTEM_USER.id,
                    S.permission_id,
                    S.historical_permission_codename,
                    S.historical_permission_content_type_app_label,
                    S.historical_permission_content_type_model_name,
                    S.historical_group_name,
                    S.state_id
                FROM
                    vueda_workflow_statepermission S,
                    SYSTEM_USER
                WHERE
                    S.state_id IN (
                        SELECT
                            WS.id
                        FROM
                            vueda_workflow_state WS
                        JOIN
                            vueda_workflow_workflow W ON WS.workflow_id = W.id
                        WHERE
                            W.code = 'order_fulfillment'
                    )
                    AND
                    S.permission_id in (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'update_orderitem'
                    );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicaltransition
                (
                    id,
                    code,
                    name,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    target_id,
                    workflow_id
                )
                SELECT
                    T.id,
                    T.code,
                    T.name,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    T.id,
                    SYSTEM_USER.id,
                    T.target_id,
                    T.workflow_id
                FROM
                    vueda_workflow_transition T,
                    SYSTEM_USER
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'order_fulfillment'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicaltransitionpermission
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    transition_id
                )
                SELECT
                    T.id,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    T.id,
                    SYSTEM_USER.id,
                    T.permission_id,
                    T.historical_permission_codename,
                    T.historical_permission_content_type_app_label,
                    T.historical_permission_content_type_model_name,
                    T.transition_id
                FROM
                    vueda_workflow_transitionpermission T,
                    SYSTEM_USER
                WHERE
                    transition_id IN (
                        SELECT
                            WT.id
                        FROM
                            vueda_workflow_transition WT
                        JOIN
                            vueda_workflow_workflow W ON WT.workflow_id = W.id
                        WHERE
                            W.code = 'order_fulfillment'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicaltransitionsource
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    source_id,
                    transition_id
                )
                SELECT
                    T.id,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    T.id,
                    SYSTEM_USER.id,
                    T.source_id,
                    T.transition_id
                FROM
                    vueda_workflow_transitionsource T,
                    SYSTEM_USER
                WHERE
                    transition_id IN (
                        SELECT
                            WT.id
                        FROM
                            vueda_workflow_transition WT
                        JOIN
                            vueda_workflow_workflow W ON WT.workflow_id = W.id
                        WHERE
                            W.code = 'order_fulfillment'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicalworkflow
                (
                    id,
                    code,
                    name,
                    historical_app_label,
                    historical_model,
                    history_date,
                    history_change_reason,
                    history_type,
                    content_type_id,
                    history_relation_id,
                    history_user_id
                )
                SELECT
                    W.id,
                    W.code,
                    W.name,
                    'store',
                    'customerorder',
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    W.content_type_id,
                    W.id,
                    SYSTEM_USER.id
                FROM
                    vueda_workflow_workflow W,
                    SYSTEM_USER
                WHERE
                    W.code = 'order_fulfillment';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                WITH SYSTEM_USER AS (
                    SELECT
                        id
                    FROM
                        tests_user
                    WHERE
                        is_system = TRUE
                )
                INSERT INTO
                    vueda_workflow_historicalworkflowpermission
                (
                    id,
                    history_date,
                    history_change_reason,
                    history_type,
                    history_relation_id,
                    history_user_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name,
                    workflow_id
                )
                SELECT
                    W.id,
                    now(),
                    'Migration - 0005_add_history_to_workflow',
                    '+',
                    W.id,
                    SYSTEM_USER.id,
                    W.permission_id,
                    W.historical_permission_codename,
                    W.historical_permission_content_type_app_label,
                    W.historical_permission_content_type_model_name,
                    W.workflow_id
                FROM
                    vueda_workflow_workflowpermission W,
                    SYSTEM_USER
                WHERE
                    workflow_id IN (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'order_fulfillment'
                    );""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
