# Generated by Django 5.0.3 on 2024-03-26 19:08

from django.db import migrations


"""
Workflow
    name            Order Fulfillment
    code            order_fulfillment
    content_type    store.CustomerOrder


WorkflowPermission
    workflow

    permission      fulfill_orders


State
    workflow

    name            New
    code            new

    name            Packed
    code            packed

    name            Returned
    code            returned

    name            Shipped
    code            shipped

    name            On Hold
    code            on_hold

    name            Cancelled
    code            cancelled


StatePermission


InitialState
    workflow
    state           new


Transition
    workflow

    name            Cancel Order
    code            cancel_order
    target          cancelled

    name            Hold Order
    code            hold_order
    target          on_hold

    name            Hold Order
    code            hold_order
    target          on_hold

    name            Pack Order
    code            pack_order
    target          packed

    name            Return Order
    code            return_order
    target          returned

    name            Ship Order
    code            ship_order
    target          shipped


TransitionPermission
    transition      cancel_order
    permission      fulfill_orders

    transition      hold_order
    permission      fulfill_orders

    transition      pack_order
    permission      fulfill_orders

    transition      ship_order
    permission      fulfill_orders


TransitionSource
    source          new
    transition      cancel_order

    source          new
    transition      hold_order

    source          new
    transition      pack_order

    source          packed
    transition      ship_order

    source          shipped
    transition      return_order
"""


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_make_sure_content_types_exist"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            INSERT INTO
                workflow_workflow
            (
                name,
                code,
                content_type_id
            )
            VALUES
            (
                'Order Fulfillment',
                'order_fulfillment',
                (
                    SELECT
                        id
                    FROM
                        django_content_type
                    WHERE
                        app_label = 'store' AND
                        model = 'customerorder'
                )
            )
            ;""",
            reverse_sql="DELETE FROM workflow_workflow WHERE code = 'order_fulfillment';",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_permission
                (
                    name,
                    content_type_id,
                    codename
                )
            VALUES
                (
                    'Can Fulfill Orders',
                    (
                        SELECT
                            id
                        FROM
                            django_content_type
                        WHERE
                            app_label = 'store'
                            AND model = 'customerorder'
                    ),
                    'fulfill_orders'
                );
            """,
            reverse_sql="DELETE FROM auth_permission WHERE codename = 'fulfill_orders';",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO workflow_state (name, code, workflow_id)
            VALUES
                ('New', 'new', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment')),
                ('Packed', 'packed', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment')),
                ('Returned', 'returned', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment')),
                ('Shipped', 'shipped', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment')),
                ('On Hold', 'on_hold', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment')),
                ('Cancelled', 'cancelled', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'));
            """,
            reverse_sql="DELETE FROM workflow_state WHERE code IN ('new', 'packed', 'returned', 'shipped', 'on_hold', 'cancelled');",
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO workflow_initialstate (workflow_id, state_id)
                VALUES
                    ((SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'), (SELECT id FROM workflow_state WHERE code = 'new'));
                """,
            reverse_sql="""
                DELETE FROM workflow_initialstate WHERE
                    workflow_id IN (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment');
                """,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO workflow_transition (name, code, workflow_id, target_id)
            VALUES
                ('Cancel Order', 'cancel_order', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'), (SELECT id FROM workflow_state WHERE code = 'cancelled')),
                ('Hold Order', 'hold_order', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'), (SELECT id FROM workflow_state WHERE code = 'on_hold')),
                ('Pack Order', 'pack_order', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'), (SELECT id FROM workflow_state WHERE code = 'packed')),
                ('Return Order', 'return_order', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'), (SELECT id FROM workflow_state WHERE code = 'returned')),
                ('Ship Order', 'ship_order', (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment'), (SELECT id FROM workflow_state WHERE code = 'shipped'));
            """,
            reverse_sql="""
                            DELETE FROM workflow_initialstate WHERE
                                workflow_id IN (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment');
                        """,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO workflow_transitionpermission (permission_id, transition_id)
            VALUES
                ((SELECT id FROM auth_permission WHERE codename = 'fulfill_orders'), (SELECT id FROM workflow_transition WHERE code = 'cancel_order')),
                ((SELECT id FROM auth_permission WHERE codename = 'fulfill_orders'), (SELECT id FROM workflow_transition WHERE code = 'hold_order')),
                ((SELECT id FROM auth_permission WHERE codename = 'fulfill_orders'), (SELECT id FROM workflow_transition WHERE code = 'pack_order')),
                ((SELECT id FROM auth_permission WHERE codename = 'fulfill_orders'), (SELECT id FROM workflow_transition WHERE code = 'ship_order'));
            """,
            reverse_sql="""
            DELETE FROM workflow_transitionpermission WHERE
                permission_id IN (SELECT id FROM auth_permission WHERE codename IN ('fulfill_orders'));
            """,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO workflow_transitionsource (transition_id, source_id)
            VALUES
                ((SELECT id FROM workflow_transition WHERE code = 'cancel_order'), (SELECT id FROM workflow_state WHERE code = 'new')),
                ((SELECT id FROM workflow_transition WHERE code = 'hold_order'), (SELECT id FROM workflow_state WHERE code = 'new')),
                ((SELECT id FROM workflow_transition WHERE code = 'pack_order'), (SELECT id FROM workflow_state WHERE code = 'new')),
                ((SELECT id FROM workflow_transition WHERE code = 'ship_order'), (SELECT id FROM workflow_state WHERE code = 'packed')),
                ((SELECT id FROM workflow_transition WHERE code = 'return_order'), (SELECT id FROM workflow_state WHERE code = 'shipped'));
            """,
            reverse_sql="""
            DELETE
                FROM workflow_transitionsource ts
                join workflow_transition t
                on t.id = ts.transition_id
                WHERE t.workflow_id IN (SELECT id FROM workflow_workflow WHERE code = 'order_fulfillment');
            """,
        ),
    ]
