# Generated by Django 5.1 on 2024-09-20 20:49
# Modified using django-view-manager 1.0.4.  Please do not delete this comment.
import os

from django.db import migrations


sql_path = "tests/store/sql"
forward_sql_filename = "view-cart_data-latest.sql"

with open(os.path.join(sql_path, forward_sql_filename), mode="r") as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_cartdata_cartitemdata_customerdata_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS cart_data;",
        ),
    ]
