# Generated by Django 5.0.3 on 2024-03-26 19:08

from django.db import migrations


"""
Workflow
    name            Order Fulfillment
    code            order_fulfillment
    content_type    store.CustomerOrder


WorkflowPermission
    workflow

    permission      fulfill_orders


State
    workflow

    name            New
    code            new

    name            Packed
    code            packed

    name            Returned
    code            returned

    name            Shipped
    code            shipped

    name            On Hold
    code            on_hold

    name            Cancelled
    code            cancelled


StatePermission


InitialState
    workflow
    state           new


Transition
    workflow

    name            Cancel Order
    code            cancel_order
    target          cancelled

    name            Hold Order
    code            hold_order
    target          on_hold

    name            Hold Order
    code            hold_order
    target          on_hold

    name            Pack Order
    code            pack_order
    target          packed

    name            Return Order
    code            return_order
    target          returned

    name            Ship Order
    code            ship_order
    target          shipped


TransitionPermission
    transition      cancel_order
    permission      fulfill_orders

    transition      hold_order
    permission      fulfill_orders

    transition      pack_order
    permission      fulfill_orders

    transition      ship_order
    permission      fulfill_orders


TransitionSource
    source          new
    transition      cancel_order

    source          new
    transition      hold_order

    source          new
    transition      pack_order

    source          packed
    transition      ship_order

    source          shipped
    transition      return_order
"""


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_create_order_fulfillment_workflow"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            SELECT
                'Order Fulfillment' AS name,
                'order_fulfillment' AS code,
                content_type
            INTO
                workflows_workflow
            FROM
                django_content_type
            WHERE
                app_label = 'store' AND
                model = 'customerorder';""",
            reverse_sql="DELETE FROM workflows_workflow WHERE code = 'order_fulfillment';",
        ),
    ]
