# Generated by Django 5.0.6 on 2024-07-09 21:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_add_history_to_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="tangible",
            field=models.CharField(
                choices=[("digital", "Digital"), ("physical", "Physical")], default="digital", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="tangible",
            field=models.CharField(
                choices=[("digital", "Digital"), ("physical", "Physical")], default="digital", max_length=255
            ),
            preserve_default=False,
        ),
    ]
