# Generated by Django 5.0.3 on 2024-06-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_create_order_fulfillment_workflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryrecord",
            options={"default_permissions": ("create", "read", "update", "delete", "list")},
        ),
        migrations.AlterModelOptions(
            name="inventoryrecordreason",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "inventory_record_reason",
            },
        ),
        # clean up add, change and view permissions,
        # since they are not used in the app.
        # remove the rows from auth_permission cascading to auth_group_permissions
        migrations.RunSQL(
            """
            DELETE FROM auth_group_permissions
            WHERE permission_id IN (
                SELECT id FROM auth_permission
                WHERE content_type_id IN (
                    SELECT id FROM django_content_type
                    WHERE app_label = 'store'
                    AND model = 'inventoryrecordreason'
                ) AND codename IN ('add_inventoryrecordreason', 'change_inventoryrecordreason', 'view_inventoryrecordreason')
            );
            DELETE FROM auth_permission
            WHERE content_type_id IN (
                SELECT id FROM django_content_type
                WHERE app_label = 'store'
                AND model = 'inventoryrecordreason'
            ) AND codename IN ('add_inventoryrecordreason', 'change_inventoryrecordreason', 'view_inventoryrecordreason');
        """
        ),
        migrations.RunSQL(
            """
            DELETE FROM auth_group_permissions
            WHERE permission_id IN (
                SELECT id FROM auth_permission
                WHERE content_type_id IN (
                    SELECT id FROM django_content_type
                    WHERE app_label = 'store'
                    AND model = 'inventoryrecord'
                ) AND codename IN ('add_inventoryrecord', 'change_inventoryrecord', 'view_inventoryrecord')
            );
            DELETE FROM auth_permission
            WHERE content_type_id IN (
                SELECT id FROM django_content_type
                WHERE app_label = 'store'
                AND model = 'inventoryrecord'
            ) AND codename IN ('add_inventoryrecord', 'change_inventoryrecord', 'view_inventoryrecord');
            """
        ),
    ]
