# Generated by Django 5.1 on 2024-09-20 20:51
# Modified using django-view-manager 1.0.4.  Please do not delete this comment.
import os

from django.db import migrations


sql_path = "tests/store/sql"
forward_sql_filename = "view-inventory_record_data-latest.sql"

with open(os.path.join(sql_path, forward_sql_filename)) as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_customer_formatted_name"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS inventory_record_data;",
        ),
    ]
