# Generated by Django 5.0.6 on 2024-07-10 17:48

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_historicalproduct_tangible_product_tangible"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="last_ten_order_betweens",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ranges.IntegerRangeField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="order_between",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(1, 20)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="last_ten_order_betweens",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ranges.IntegerRangeField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="order_between",
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(1, 20)),
            preserve_default=False,
        ),
    ]
