# Generated by Django 5.0.3 on 2024-06-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_inventoryrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerorder",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "permissions": [("fulfill_orders", "Can fulfill orders")],
            },
        ),
    ]
