# Generated by Django 5.0.7 on 2024-07-29 17:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_historicalproduct_last_ten_order_betweens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
