# Generated by Django 6.1 on 2026-09-08 16:43

from django.db import migrations


DELETED_MODELS = (
    "historicalcustomer",
    "historicalcustomerorder",
    "historicaldistributor",
    "historicalinvoiceline",
    "historicalproduct",
    "historicalproductoption",
)


def remove_stale_content_types(apps, schema_editor):
    """Drop the content types 0001 created for the historical models, and their permissions.

    ``0001_initial`` calls ``create_permissions`` against its own migration state, so it wrote a
    content type and five permissions for each historical model. Deleting the model leaves those
    rows behind, and the workflow permission picker then offers a permission on a table that is
    gone.
    """
    content_type = apps.get_model("contenttypes", "ContentType")
    content_type.objects.filter(app_label="store", model__in=DELETED_MODELS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "__first__"),
        ("store", "0009_cartevent_cartitemevent_customerevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcustomerorder",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="historicalcustomerorder",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalcustomerorder",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalcustomerorder",
            name="order_state",
        ),
        migrations.RemoveField(
            model_name="historicaldistributor",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicaldistributor",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalinvoiceline",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalinvoiceline",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalinvoiceline",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="distributor",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="tangible_type",
        ),
        migrations.RemoveField(
            model_name="historicalproductoption",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalproductoption",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalproductoption",
            name="option_type",
        ),
        migrations.RemoveField(
            model_name="historicalproductoption",
            name="product",
        ),
        migrations.DeleteModel(
            name="HistoricalCustomer",
        ),
        migrations.DeleteModel(
            name="HistoricalCustomerOrder",
        ),
        migrations.DeleteModel(
            name="HistoricalDistributor",
        ),
        migrations.DeleteModel(
            name="HistoricalInvoiceLine",
        ),
        migrations.DeleteModel(
            name="HistoricalProduct",
        ),
        migrations.DeleteModel(
            name="HistoricalProductOption",
        ),
        migrations.RunPython(remove_stale_content_types, reverse_code=migrations.RunPython.noop),
    ]
