# Generated by Django 5.1 on 2024-09-23 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_order_item_formatted_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="formatted_name",
        ),
        migrations.RemoveField(
            model_name="inventoryrecord",
            name="formatted_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="formatted_name",
        ),
    ]
