# Generated by Django 5.0.7 on 2024-07-30 20:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="current_sale_date",
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="future_sale_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ranges.DateRangeField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="current_sale_date",
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="future_sale_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ranges.DateRangeField(), null=True, size=None
            ),
        ),
    ]
