# Generated by Django 5.1.2 on 2024-10-24 17:11
# Modified using django-view-manager 1.0.4.  Please do not delete this comment.
import os

from django.db import migrations


sql_path = "tests/store/sql"
forward_sql_filename = "view-cart_data-latest.sql"
reverse_sql_filename = "view-cart_data-0005.sql"

with open(os.path.join(sql_path, forward_sql_filename), mode="r") as f:
    forwards_sql = f.read()

with open(os.path.join(sql_path, reverse_sql_filename), mode="r") as f:
    reverse_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_remove_cartitem_formatted_name_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql=reverse_sql,
        ),
    ]
