# Generated by Django 5.0.7 on 2024-07-31 15:24

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_historicalproduct_current_sale_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="reviews",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2048), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2048), blank=True, default=list, size=None
            ),
        ),
    ]
