# Generated by Django 5.1.2 on 2024-10-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_switch_cart_formatted_name_to_a_function"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartData",
        ),
        migrations.RemoveField(
            model_name="specialcare",
            name="formatted_name",
        ),
    ]
