# Generated by Django 5.0.7 on 2024-07-31 17:27

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_historicalproduct_reviews_product_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="internal_comments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="internal_comments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
    ]
