# Generated by Django 5.1.2 on 2024-10-25 19:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_delete_cartdata_remove_specialcare_formatted_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingBox",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("depth", models.DecimalField(decimal_places=4, max_digits=12)),
                ("height", models.DecimalField(decimal_places=4, max_digits=12)),
                ("width", models.DecimalField(decimal_places=4, max_digits=12)),
                ("carrying_weight", models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                "verbose_name": "Packing Box",
                "verbose_name_plural": "Packing Boxes",
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
    ]
