# Generated by Django 5.0.7 on 2024-08-08 17:42

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_historicalproduct_internal_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="expected_delivery_time",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="reserved_delivery_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="reserved_until",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="customerorder",
            name="shipping_method",
            field=models.CharField(
                blank=True, choices=[("free", "Free"), ("regular", "Regular"), ("express", "Express")], max_length=255
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomerorder",
            name="shipping_method",
            field=models.CharField(
                blank=True, choices=[("free", "Free"), ("regular", "Regular"), ("express", "Express")], max_length=255
            ),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="last_ordered",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="quantity",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="special_care",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alcohol", "Alcohol"),
                    ("dangerous", "Dangerous"),
                    ("fragile", "Fragile"),
                    ("oversized", "Oversized"),
                    ("perishable", "Perishable"),
                    ("temperature_controlled", "Temperature Controlled"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalproductoption",
            name="quantity_available",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="last_ordered",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="special_care",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alcohol", "Alcohol"),
                    ("dangerous", "Dangerous"),
                    ("fragile", "Fragile"),
                    ("oversized", "Oversized"),
                    ("perishable", "Perishable"),
                    ("temperature_controlled", "Temperature Controlled"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="quantity_available",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="inventoryrecord",
            name="quantity",
            field=models.IntegerField(db_default=0, validators=[django.core.validators.StepValueValidator(6)]),
        ),
    ]
