# Generated by Django 5.1.2 on 2024-10-31 16:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_packingbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingbox",
            name="in_stock",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="number_in_stock",
            field=models.IntegerField(db_default=0),
        ),
    ]
