# Generated by Django 6.1 on 2026-09-08 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_employeeevent_userevent_employee_insert_insert_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalEmployee",
        ),
    ]
