"""Utilities for group migration management commands."""

__all__ = (
    "call_management_command",
    "create_group_change",
    "get_matching_record",
    "get_migration_names_from_show_migrations",
    "get_migrations_path",
    "has_direct_runpython_import",
    "locate_empty_migration_slots",
    "parse_date_from_django_comment",
    "parse_migrations_from_show_migrations",
)

import ast
import contextlib
import datetime
import importlib
import io
import sys

from django.conf import settings
from django.core.management import call_command as django_call_command
from django.db.migrations.loader import MIGRATIONS_MODULE_NAME


# The read path already normalizes everything to \n.
# The write path already auto-translates \n → the platform's native ending exactly once.
# So, there's no reason to pre-translate with os.linesep
NEWLINE = "\n"  # no longer os.linesep


def get_matching_record(change, group_change_model):
    """Return GroupChange.pk if a record matching this change exists, None otherwise."""
    # Need group_change_model since we could be running from a migration.
    obj = group_change_model.objects.filter(
        group_name=change["group_name"],
        group_name_old=change["group_name_old"],
        change_type=change["change_type"],
        when=change["when"],
        historical_permission_codename=change["historical_permission_codename"],
        historical_permission_content_type_app_label=change["historical_permission_content_type_app_label"],
        historical_permission_content_type_model_name=change["historical_permission_content_type_model_name"],
    ).order_by("when")
    if obj.exists():
        return obj.first().pk


def create_group_change(change, group_change_model):
    # Need group_change_model since we could be running from a migration.
    obj = group_change_model.objects.create(
        group_name=change["group_name"],
        group_name_old=change["group_name_old"],
        change_type=change["change_type"],
        historical_permission_codename=change["historical_permission_codename"],
        historical_permission_content_type_app_label=change["historical_permission_content_type_app_label"],
        historical_permission_content_type_model_name=change["historical_permission_content_type_model_name"],
    )
    # auto_now=True prevents setting `when` via create(), so update it directly
    # to preserve the original timestamp from the migration's changed_data.
    obj.when = change["when"]
    obj.save()
    return obj.pk


def has_direct_runpython_import(lines):
    """Return True if ``lines`` imports RunPython directly, e.g. ``from django.db.migrations import RunPython``,
    rather than only accessing it via ``migrations.RunPython``.

    ``lines`` is a list of strings, as returned by ``readlines()``. Only module-level ``from ... import``
    statements are considered, so a RunPython import nested inside a copied function source is never matched.
    """
    tree = ast.parse("".join(lines))
    return any(
        isinstance(node, ast.ImportFrom)
        and node.module == "django.db.migrations"
        and any(alias.name == "RunPython" for alias in node.names)
        for node in tree.body
    )


def call_management_command(command, *args):
    """Run ``args`` through Django's ``call_command``, capturing its output.

    ``command`` is the ``BaseCommand`` instance invoking this (needs ``.dry_run``, ``.style``, ``.stdout``).
    A trailing ``--dry-run`` is appended automatically when ``command.dry_run`` is set and the command
    being run is ``makemigrations``. Exits the process with status 2 if the command wrote to stderr.
    """
    err = io.StringIO()
    out = io.StringIO()

    if command.dry_run and args[0] == "makemigrations":
        args = args + ("--dry-run",)

    # If we don't do this, sometimes we can't import a newly created migration.
    # Do it here, so we don't need to know which calls require it, and which don't.
    importlib.invalidate_caches()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        try:
            django_call_command(*args)
        except SystemExit:
            pass

    # Did an error occur?
    if err.tell():
        err.seek(0)
        command.stdout.write(command.style.ERROR(err.read()))
        sys.exit(2)

    # Return the results.
    out.seek(0)
    return out.readlines()


def parse_migrations_from_show_migrations(lines):
    migrations = []

    for line in lines:
        line = line.strip()
        if line.startswith("["):
            line = line.replace("[ ]", "").replace("[X]", "").strip()
            migrations.append(line)

    return migrations


def parse_date_from_django_comment(django_comment):
    # Generated by Django 5.0.3 on 2024-03-26 19:08
    date_string = django_comment.split(" on ")[-1].strip()
    # The date in the migration is in UTC.  Make sure it acquires the UTC timezone.
    created_date = datetime.datetime.strptime(f"{date_string}:00 +0000", "%Y-%m-%d %H:%M:%S %z")
    return created_date.astimezone()


def get_migration_names_from_show_migrations(command, app_label):
    show_migration_results = call_management_command(command, "showmigrations", app_label)
    if not show_migration_results:  # Erred.  The reason will be printed to the console via the command.
        return None

    return parse_migrations_from_show_migrations(show_migration_results)


def get_migrations_path(app_config):
    app_label = app_config.label
    if app_label in settings.MIGRATION_MODULES:
        module_name = settings.MIGRATION_MODULES[app_label]
    else:
        module_name = f"{app_config.name}.{MIGRATIONS_MODULE_NAME}"

    if module_name is None:
        return None

    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError:
        return None

    # An app can ship migrations as a single module rather than a package, which has no __path__ and
    # therefore no directory for a generated migration to live in. pgtrigger is one such app.
    paths = getattr(module, "__path__", None)
    return paths[0] if paths else None


def locate_empty_migration_slots(lines):
    """Locate the line numbers of the key components of a freshly generated, empty migration.

    ``lines`` is a list of strings, as returned by ``readlines()``, for a migration file created while
    ``migrations.Migration.operations`` was forced to a known, findable shape (two ``RunPython`` calls
    using ``dict``/``type`` and ``str``/``int`` as placeholder ``code``/``reverse_code`` values). Returns a
    dict of 0-based line numbers: ``class_index`` (the ``class Migration`` line), ``dependencies_index``
    (the ``dependencies = [...]`` assignment), ``import_start``/``import_end`` (the import block), and the
    four placeholder keyword-value locations (``p_forwards_index``, ``p_reverse_index``, ``forwards_index``,
    ``reverse_index``). Raises ``RuntimeError`` if any of them can't be found, e.g. because Django changed
    the shape of the empty-migration template it emits.
    """
    tree = ast.parse("".join(lines))
    class_index = dependencies_index = None
    p_forwards_index = p_reverse_index = forwards_index = reverse_index = None
    import_start = import_end = None
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "Migration":
            class_index = node.lineno - 1

        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "dependencies":
                    dependencies_index = node.lineno - 1

        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            # This is a freshly generated, empty migration, so its imports are a single
            # contiguous block at the top of the file, never a direct RunPython import.
            if import_start is None:
                import_start = node.lineno - 1
            import_end = node.end_lineno - 1

        elif isinstance(node, ast.Call):
            func = node.func
            is_run_python = (isinstance(func, ast.Attribute) and func.attr == "RunPython") or (
                isinstance(func, ast.Name) and func.id == "RunPython"
            )
            if not is_run_python:
                continue

            # Separate tests, so code=dict/reverse_code=type and code=str/reverse_code=int are
            # fine whether or not they are on the same line as each other.
            for keyword in node.keywords:
                value = keyword.value
                if not isinstance(value, ast.Name):
                    continue

                if keyword.arg == "code" and value.id == "dict":
                    p_forwards_index = value.lineno - 1
                elif keyword.arg == "reverse_code" and value.id == "type":
                    p_reverse_index = value.lineno - 1
                elif keyword.arg == "code" and value.id == "str":
                    forwards_index = value.lineno - 1
                elif keyword.arg == "reverse_code" and value.id == "int":
                    reverse_index = value.lineno - 1

    slots = {
        "class_index": class_index,
        "dependencies_index": dependencies_index,
        "p_forwards_index": p_forwards_index,
        "p_reverse_index": p_reverse_index,
        "forwards_index": forwards_index,
        "reverse_index": reverse_index,
        "import_start": import_start,
        "import_end": import_end,
    }
    if any(value is None for value in slots.values()):
        raise RuntimeError("Unable to determine the line numbers of key components in the created migration.")
    return slots


def find_class_migration_line(lines):
    """Return the 1-based line number of ``class Migration(...)``, or None if not found."""
    for index, line in enumerate(lines, start=1):
        if line.startswith("class Migration("):
            return index
    return None


class NoRenamesError(Exception):
    pass


def update_operation_function_names(class_migration_block, operation_function_renames):
    tree = ast.parse(class_migration_block)

    # Collect (lineno, col_offset, old_name) for Name nodes inside RunPython calls only,
    # so string literals in dependencies are never touched.
    renames = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func

        is_attribute_call = isinstance(func, ast.Attribute) and func.attr == "RunPython"
        is_direct_call = isinstance(func, ast.Name) and func.id == "RunPython"
        if not (is_attribute_call or is_direct_call):
            continue

        # Find RunPython that uses positional arguments.
        # Migrations are generated with keyword arguments, but one migration has been modified for this.
        for arg in node.args:
            if isinstance(arg, ast.Name) and arg.id in operation_function_renames:
                renames.append((arg.lineno, arg.col_offset, arg.id))

        # Find RunPython that uses keyword arguments.
        for kw in node.keywords:
            if (
                kw.arg in ("code", "reverse_code")
                and isinstance(kw.value, ast.Name)
                and kw.value.id in operation_function_renames
            ):
                renames.append((kw.value.lineno, kw.value.col_offset, kw.value.id))

    if not renames:
        raise NoRenamesError()

    lines = class_migration_block.splitlines(keepends=True)
    for lineno, col_offset, old_name in sorted(renames, reverse=True):
        new_name = operation_function_renames[old_name]
        line = lines[lineno - 1]
        lines[lineno - 1] = line[:col_offset] + new_name + line[col_offset + len(old_name) :]
    return "".join(lines)


def get_top_level_defs(source):
    """Return (name, start_lineno, end_lineno) for every top-level function/class def in ``source``."""
    tree = ast.parse(source)
    defs = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            defs.append((node.name, node.lineno, node.end_lineno))
    return defs


def get_top_level_imports(source):
    """Return (name, start_lineno, end_lineno) for every top-level import statement in ``source``.

    Each import is expected to bind exactly one name, per this project's force-single-line isort
    convention (``import a``, never ``import a, b``). ``name`` is the alias if one is given, otherwise
    the imported name (or the top-level package, for a dotted ``import a.b.c``).
    """
    tree = ast.parse(source)
    imports = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            alias = node.names[0]
            name = alias.asname or alias.name.split(".")[0]
            imports.append((name, node.lineno, node.end_lineno))
    return imports


def resolve_replacements(existing_segment, entry_map, get_entries):
    """Match ``entry_map`` entries against what ``get_entries`` finds in ``existing_segment``.

    Returns a list of ``{"source": ..., "range": (start, end) or None, "anchor": ..., "anchor_side": ...}``
    dicts, one per ``entry_map`` entry, in ``entry_map`` order. ``range`` is set when a matching name is
    found in ``existing_segment``. Unmatched entries get an ``anchor`` line number and ``anchor_side``
    ("after" or "before") pointing at the nearest matched neighbour, so callers can insert them in the
    right place; both are ``None`` when there is no matched entry to anchor against at all.
    """
    available_by_name = {}
    for name, start, end in get_entries(existing_segment):
        available_by_name.setdefault(name, []).append((start, end))

    # Match in passes by alias position, not by entry_map order: every entry's own current (first-listed)
    # name gets first claim on its match before any entry falls back to a shared legacy alias. Otherwise a
    # migration that predates a later rename (e.g. a `_through_imports` wrapper split out of a function
    # that used to do both jobs) could have its still-current, unrenamed function stolen by another
    # entry's alias tuple, which only knows that same name as one of several historical fallbacks.
    claimed_names = set()
    entries = list(entry_map.items())
    resolved = [{"source": source, "range": None} for _names, source in entries]
    max_names = max((len(names) for names, _source in entries), default=0)
    for name_index in range(max_names):
        for index, (names, _source) in enumerate(entries):
            if resolved[index]["range"] is not None or name_index >= len(names):
                continue
            name = names[name_index]
            occurrences = available_by_name.get(name)
            if occurrences and name not in claimed_names:
                resolved[index]["range"] = occurrences.pop(0)
                claimed_names.add(name)

    for index, item in enumerate(resolved):
        if item["range"] is not None:
            continue

        anchor = anchor_side = None
        for previous in reversed(resolved[:index]):
            if previous["range"] is not None:
                anchor = previous["range"][1]
                anchor_side = "after"
                break

        if anchor is None:
            for following in resolved[index + 1 :]:
                if following["range"] is not None:
                    anchor = following["range"][0]
                    anchor_side = "before"
                    break

        item["anchor"] = anchor
        item["anchor_side"] = anchor_side

    return resolved


def merge_migration_sources(existing_segment, source_map):
    """Replace known functions/classes in ``existing_segment`` with their current implementation.

    ``source_map`` is an ordered mapping (as returned by ``get_group_migration_sources(as_mapping=True)``
    / ``get_migration_sources(as_mapping=True)``) of alternate-name tuples to fresh source text. Every name
    in a tuple identifies the same logical function/class across versions of the generating command, so a
    function that was renamed (e.g. as part of introducing a ``_through_imports`` wrapper) is still matched
    against its old name and replaced in place.

    Anything in ``existing_segment`` that isn't a recognized top-level def (hand-added imports, comments,
    blank lines) is left untouched, in its original position. Entries in ``source_map`` with no matching
    name in ``existing_segment`` (newly introduced functions/classes) are inserted immediately after the
    nearest preceding entry that *was* matched, or immediately before the nearest following matched entry,
    following the order of ``source_map``.
    """
    lines = existing_segment.splitlines(keepends=True)
    resolved = resolve_replacements(existing_segment, source_map, get_top_level_defs)

    # An entry only ends up with no anchor at all when nothing else in `resolved` matched either before or
    # after it -- i.e. nothing in `source_map` matched the file. Land those just before `class Migration`
    # instead of at the very end, so a freshly inserted function is still defined before the
    # `operations = [...]` list in the class body can reference it.
    fallback_anchor = find_class_migration_line(lines)

    replace_at = {}
    insert_after = {}
    insert_before = {}
    trailing = []
    for item in resolved:
        if item["range"] is not None:
            start, end = item["range"]
            replace_at[start] = (end, item["source"])
        elif item["anchor_side"] == "after":
            insert_after.setdefault(item["anchor"], []).append(item["source"])
        elif item["anchor_side"] == "before":
            insert_before.setdefault(item["anchor"], []).append(item["source"])
        elif fallback_anchor is not None:
            insert_before.setdefault(fallback_anchor, []).append(item["source"])
        else:
            trailing.append(item["source"])

    output = []
    line_no = 1
    total_lines = len(lines)
    while line_no <= total_lines:
        for source in insert_before.get(line_no, ()):
            output.append(f"{NEWLINE}{NEWLINE}{source}")

        if line_no in replace_at:
            end, source = replace_at[line_no]
            output.append(source)
            for after_source in insert_after.get(end, ()):
                output.append(f"{NEWLINE}{NEWLINE}{after_source}")
            line_no = end + 1
            continue

        output.append(lines[line_no - 1])
        for after_source in insert_after.get(line_no, ()):
            output.append(f"{NEWLINE}{NEWLINE}{after_source}")
        line_no += 1

    for source in trailing:
        output.append(f"{NEWLINE}{NEWLINE}{source}")

    return "".join(output)


def merge_migration_imports(existing_segment, import_map):
    """Update or insert known import statements in ``existing_segment``, preserving everything else.

    ``import_map`` is an ordered mapping (as returned by ``get_group_migration_imports(as_mapping=True)``
    / ``get_migration_imports(as_mapping=True)``) of single-name tuples to the current import line. Each
    value already ends in its own newline and, where it opens a new isort group, is prefixed with a blank
    line.

    An import already present in ``existing_segment`` is rewritten in place (so a changed import path is
    picked up) without disturbing whatever blank line already precedes it. An import that isn't present
    yet is inserted next to the nearest recognized neighbour, following the order of ``import_map``, using
    its own prefixed blank line where relevant. Anything else in ``existing_segment`` (hand-added imports,
    comments, blank lines) is left untouched, in its original position.
    """
    lines = existing_segment.splitlines(keepends=True)
    resolved = resolve_replacements(existing_segment, import_map, get_top_level_imports)

    # An entry only ends up with no anchor at all when nothing else in `resolved` matched either before or
    # after it -- i.e. nothing in `import_map` matched the file. Land those just before `class Migration`
    # instead of at the very end, so a freshly inserted import still precedes the code that uses it.
    fallback_anchor = find_class_migration_line(lines)

    replace_at = {}
    insert_after = {}
    insert_before = {}
    trailing = []
    for item in resolved:
        if item["range"] is not None:
            start, end = item["range"]
            # Already here, so drop any leading group-separator blank line baked into the fresh text --
            # whatever blank line belongs before it, if any, is already there, untouched.
            replace_at[start] = (end, item["source"].lstrip(NEWLINE))
        elif item["anchor_side"] == "after":
            insert_after.setdefault(item["anchor"], []).append(item["source"])
        elif item["anchor_side"] == "before":
            insert_before.setdefault(item["anchor"], []).append(item["source"])
        elif fallback_anchor is not None:
            insert_before.setdefault(fallback_anchor, []).append(item["source"])
        else:
            trailing.append(item["source"])

    output = []
    line_no = 1
    total_lines = len(lines)
    while line_no <= total_lines:
        output.extend(insert_before.get(line_no, ()))

        if line_no in replace_at:
            end, source = replace_at[line_no]
            output.append(source)
            output.extend(insert_after.get(end, ()))
            line_no = end + 1
            continue

        output.append(lines[line_no - 1])
        output.extend(insert_after.get(line_no, ()))
        line_no += 1

    output.extend(trailing)

    return "".join(output)
