# Generated by Django 5.2.16 on 2026-07-28 20:37

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employee.employee")),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_supervisors",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["period_start", "employee__employee_number"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheets",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTimesheet",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employee.employee",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employee.employee",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="timesheet.timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical timesheet",
                "verbose_name_plural": "historical timesheets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                                output_field=models.CharField(),
                            ),
                            models.Value(" - "),
                            django.db.models.functions.comparison.Cast(
                                models.F("hours"), output_field=models.CharField()
                            ),
                            models.Value(" hours"),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="timesheet.timesheet")),
            ],
            options={
                "ordering": ["date"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheet_entries",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTimesheetEntry",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                                output_field=models.CharField(),
                            ),
                            models.Value(" - "),
                            django.db.models.functions.comparison.Cast(
                                models.F("hours"), output_field=models.CharField()
                            ),
                            models.Value(" hours"),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="timesheet.timesheet",
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_records",
                        to="timesheet.timesheetentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical timesheet entry",
                "verbose_name_plural": "historical timesheet entrys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TimesheetData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "timesheet_data",
                "managed": False,
            },
        ),
    ]
