# Generated by Django 5.2.16 on 2026-07-28 20:37

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import django.db.models.functions.text
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0001_initial"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employee.employee")),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_supervisors",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["period_start", "employee__employee_number"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheets",
            },
        ),
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                                output_field=models.CharField(),
                            ),
                            models.Value(" - "),
                            django.db.models.functions.comparison.Cast(
                                models.F("hours"), output_field=models.CharField()
                            ),
                            models.Value(" hours"),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="timesheet.timesheet")),
            ],
            options={
                "ordering": ["date"],
                "abstract": False,
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "timesheet_entries",
            },
        ),
        migrations.CreateModel(
            name="TimesheetData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("formatted_name", models.CharField()),
            ],
            options={
                "db_table": "timesheet_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TimesheetEntryEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "year"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "month"),
                                output_field=models.CharField(),
                            ),
                            models.Value("/"),
                            django.db.models.functions.comparison.Cast(
                                django.db.models.functions.datetime.Extract(models.F("date"), "day"),
                                output_field=models.CharField(),
                            ),
                            models.Value(" - "),
                            django.db.models.functions.comparison.Cast(
                                models.F("hours"), output_field=models.CharField()
                            ),
                            models.Value(" hours"),
                        ),
                        output_field=models.CharField(),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimesheetEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="timesheetentryevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentryevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="timesheet.timesheetentry",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentryevent",
            name="timesheet",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="timesheet.timesheet",
            ),
        ),
        migrations.AddField(
            model_name="timesheetevent",
            name="employee",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="timesheetevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="timesheetevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="timesheet.timesheet",
            ),
        ),
        migrations.AddField(
            model_name="timesheetevent",
            name="supervisor",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="employee.employee",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheet",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "timesheet_timesheetevent" ("employee_id", "id", "period_end", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supervisor_id") VALUES (NEW."employee_id", NEW."id", NEW."period_end", NEW."period_start", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."supervisor_id"); RETURN NULL;',
                    hash="20d05125067551b3ecb159d195b00763ad429d9a",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_cafc5",
                    table="timesheet_timesheet",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheet",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "timesheet_timesheetevent" ("employee_id", "id", "period_end", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supervisor_id") VALUES (NEW."employee_id", NEW."id", NEW."period_end", NEW."period_start", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."supervisor_id"); RETURN NULL;',
                    hash="e54969091e463ff3e4647c51030e4a52a229ce66",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_cefc1",
                    table="timesheet_timesheet",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheet",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "timesheet_timesheetevent" ("employee_id", "id", "period_end", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "supervisor_id") VALUES (OLD."employee_id", OLD."id", OLD."period_end", OLD."period_start", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."supervisor_id"); RETURN NULL;',
                    hash="dcb16e6db7d888b2a46486e5ac0d6271b21d1d75",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_1ed36",
                    table="timesheet_timesheet",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheetentry",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "timesheet_timesheetentryevent" ("date", "hours", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "timesheet_id") VALUES (NEW."date", NEW."hours", NEW."id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."timesheet_id"); RETURN NULL;',
                    hash="09f45e75923c76ffc331f567144394876d0c36ff",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_5133e",
                    table="timesheet_timesheetentry",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheetentry",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "timesheet_timesheetentryevent" ("date", "hours", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "timesheet_id") VALUES (NEW."date", NEW."hours", NEW."id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."timesheet_id"); RETURN NULL;',
                    hash="b06cc305cc7d1587585123a1f8c7421c71829697",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_f51b8",
                    table="timesheet_timesheetentry",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheetentry",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "timesheet_timesheetentryevent" ("date", "hours", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "timesheet_id") VALUES (OLD."date", OLD."hours", OLD."id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."timesheet_id"); RETURN NULL;',
                    hash="38a5b48fa54a2785450e7fc6d500aa14411e5e6a",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_7d5e8",
                    table="timesheet_timesheetentry",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheetentryevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="1f27452a4ed6001dafdf8a802c58a5cbcc70cc1b",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_06519",
                    table="timesheet_timesheetentryevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timesheetevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="870a8f5f51a3c0ff77f1b080a9b08fa30491bf4e",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ff51f",
                    table="timesheet_timesheetevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
