# Generated by Django 5.2.16 on 2026-07-29 17:13
# Modified using django-view-manager 2.0.0.  Please do not delete this comment.
import os

from django.db import migrations


sql_path = "tests/timesheet/sql"
forward_sql_filename = "view-timesheet_data-latest.sql"

with open(os.path.join(sql_path, forward_sql_filename)) as f:
    forwards_sql = f.read()


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forwards_sql,
            reverse_sql="DROP VIEW IF EXISTS timesheet_data;",
        ),
    ]
