# Generated by Django 6.1 on 2026-09-08 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timesheet", "0003_timesheetentryevent_timesheetevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltimesheetentry",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicaltimesheetentry",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltimesheetentry",
            name="timesheet",
        ),
        migrations.DeleteModel(
            name="HistoricalTimesheet",
        ),
        migrations.DeleteModel(
            name="HistoricalTimesheetEntry",
        ),
    ]
