# Generated by Django 5.2.6 on 2025-09-22 22:50

import datetime

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations
from django.db import models

import vueda.vdq.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("name"),
                        output_field=models.CharField(),
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "cell",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "VUEDA_VDQ_RECEIVER_MODEL",
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.F("name"),
                        output_field=models.CharField(),
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "cell",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "VUEDA_VDQ_SENDER_MODEL",
                "default_permissions": ("create", "read", "update", "delete", "list"),
            },
        ),
        migrations.CreateModel(
            name="AnyMailQueueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.TextField()),
                ("text", models.TextField()),
                ("html", models.TextField(blank=True, default="")),
                (
                    "message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "anymail_queue_items",
            },
        ),
        migrations.CreateModel(
            name="AnyMailQueueItemAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(upload_to="email_queue_item_attachments"),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "mimetype",
                    models.CharField(max_length=100, validators=[vueda.vdq.models.validate_mimetype]),
                ),
                ("file_size", models.PositiveIntegerField(null=True)),
                ("content_disposition_is_inline", models.BooleanField(default=False)),
                ("content_id_string", models.CharField(max_length=100)),
                (
                    "anymail_queue_items",
                    models.ManyToManyField(related_name="attachments", to="vueda_vdq.anymailqueueitem"),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "anymail_attachments",
            },
        ),
        migrations.CreateModel(
            name="AnyMailQueueItemReceiverCc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anymail_queue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vueda_vdq.anymailqueueitem",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.VUEDA_VDQ_RECEIVER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "anymail_queue_item_receiver_ccs",
            },
        ),
        migrations.AddField(
            model_name="anymailqueueitem",
            name="cc",
            field=models.ManyToManyField(
                related_name="anymail_queue_items_cc",
                through="vueda_vdq.AnyMailQueueItemReceiverCc",
                through_fields=("anymail_queue_item", "receiver"),
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AnyMailQueueItemReceiverReplyTo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anymail_queue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vueda_vdq.anymailqueueitem",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.VUEDA_VDQ_RECEIVER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "anymail_queue_item_receiver_reply_tos",
            },
        ),
        migrations.AddField(
            model_name="anymailqueueitem",
            name="reply_to",
            field=models.ManyToManyField(
                related_name="anymail_queue_items_reply_to",
                through="vueda_vdq.AnyMailQueueItemReceiverReplyTo",
                through_fields=("anymail_queue_item", "receiver"),
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AnyMailQueueItemReceiverTo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anymail_queue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vueda_vdq.anymailqueueitem",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.VUEDA_VDQ_RECEIVER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "anymail_queue_item_receiver_tos",
            },
        ),
        migrations.AddField(
            model_name="anymailqueueitem",
            name="to",
            field=models.ManyToManyField(
                related_name="anymail_queue_items_to",
                through="vueda_vdq.AnyMailQueueItemReceiverTo",
                through_fields=("anymail_queue_item", "receiver"),
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="QueueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "method",
                    models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=255),
                ),
                ("result", models.TextField(default="")),
                ("retry_delay", models.IntegerField(default=0, help_text="seconds")),
                ("queued", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("done_since", models.DateTimeField(default=datetime.datetime.now)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.VUEDA_VDQ_RECEIVER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.VUEDA_VDQ_SENDER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-queued", "-last_updated"),
                "permissions": [
                    ("can_resend", "Can resend the item"),
                    ("can_cancel", "Can cancel the item"),
                    ("can_retry", "Can retry the item"),
                ],
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "default_related_name": "queue_items",
            },
        ),
        migrations.AddField(
            model_name="anymailqueueitem",
            name="queue_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anymail",
                to="vueda_vdq.queueitem",
            ),
        ),
        migrations.CreateModel(
            name="SentItem",
            fields=[],
            options={
                "verbose_name": "Sent Item",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vueda_vdq.queueitem",),
        ),
        migrations.CreateModel(
            name="SMSQueueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=1600)),
                ("media_url", models.JSONField(null=True)),
                ("message_sid", models.CharField(max_length=34)),
                (
                    "queue_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms",
                        to="vueda_vdq.queueitem",
                    ),
                ),
            ],
            options={
                "default_related_name": "sms_queue_items",
                "indexes": [models.Index(fields=["message_sid"], name="vueda_vdq_s_message_ef2306_idx")],
            },
        ),
    ]
