# Generated by Django 5.2.6 on 2025-09-22 20:34
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
import copy
import datetime
import os

from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations


history_change_reason = "Workflow Migration - 0002_workflow_migrations_2025_09_22"
migration_app_label = "vueda_vdq"
changed_data = [
    {
        "changes": {
            "code": "queueitem",
            "content_type_id": {"app_label": "vueda_vdq", "model": "queueitem"},
            "historical_app_label": "vueda_vdq",
            "historical_model": "queueitem",
            "id": {"code": "queueitem"},
            "name": "QueueItem",
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 3, 56, 493209, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "code": "awaiting",
            "id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
            "name": "Awaiting",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 503426, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "cancelled",
            "id": {"code": "cancelled", "workflow_id": {"code": "queueitem"}},
            "name": "Cancelled",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 508189, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "delayed",
            "id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
            "name": "Delayed",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 510984, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "errored",
            "id": {"code": "errored", "workflow_id": {"code": "queueitem"}},
            "name": "Errored",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 513716, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "queued",
            "id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
            "name": "Queued",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 515619, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "sending",
            "id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
            "name": "Sending",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 518025, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "succeeded",
            "id": {"code": "succeeded", "workflow_id": {"code": "queueitem"}},
            "name": "Succeeded",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 520100, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "unconfirmed",
            "id": {"code": "unconfirmed", "workflow_id": {"code": "queueitem"}},
            "name": "Unconfirmed",
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 5, 38, 522288, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
                "workflow_id": {"code": "queueitem"},
            },
            "state_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 6, 11, 217880, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "await",
            "id": {"code": "await", "workflow_id": {"code": "queueitem"}},
            "name": "Await",
            "target_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 538152, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "cancel",
            "id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
            "name": "Cancel",
            "target_id": {"code": "cancelled", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 550470, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "delay",
            "id": {"code": "delay", "workflow_id": {"code": "queueitem"}},
            "name": "Delay",
            "target_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 552497, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "error",
            "id": {"code": "error", "workflow_id": {"code": "queueitem"}},
            "name": "Error",
            "target_id": {"code": "errored", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 554005, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "retry",
            "id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
            "name": "Retry",
            "target_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 555471, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "send",
            "id": {"code": "send", "workflow_id": {"code": "queueitem"}},
            "name": "Send",
            "target_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 556886, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "succeed",
            "id": {"code": "succeed", "workflow_id": {"code": "queueitem"}},
            "name": "Succeed",
            "target_id": {"code": "succeeded", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 558273, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "timeout",
            "id": {"code": "timeout", "workflow_id": {"code": "queueitem"}},
            "name": "Timeout",
            "target_id": {"code": "unconfirmed", "workflow_id": {"code": "queueitem"}},
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 6, 561215, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "list_queueitem",
            "historical_permission_content_type_app_label": "vueda_vdq",
            "historical_permission_content_type_model_name": "queueitem",
            "id": {
                "historical_permission_codename": "list_queueitem",
                "historical_permission_content_type_app_label": "vueda_vdq",
                "historical_permission_content_type_model_name": "queueitem",
                "workflow_id": {"code": "queueitem"},
            },
            "permission_id": {
                "codename": "list_queueitem",
                "content_type_id": {"app_label": "vueda_vdq", "model": "queueitem"},
            },
            "workflow_id": {"code": "queueitem"},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 8, 45, 381055, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "await", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "await", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 9, 20, 623407, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 9, 42, 285515, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 9, 42, 285515, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "errored", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "errored", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 9, 42, 289281, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "historical_permission_codename": "can_cancel",
            "historical_permission_content_type_app_label": "vueda_vdq",
            "historical_permission_content_type_model_name": "queueitem",
            "id": {
                "historical_permission_codename": "can_cancel",
                "historical_permission_content_type_app_label": "vueda_vdq",
                "historical_permission_content_type_model_name": "queueitem",
                "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
            },
            "permission_id": {
                "codename": "can_cancel",
                "content_type_id": {"app_label": "vueda_vdq", "model": "queueitem"},
            },
            "transition_id": {"code": "cancel", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 10, 3, 570134, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "delay", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "delay", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 10, 21, 816652, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "delay", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "delay", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 10, 21, 816652, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 11, 2, 681572, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 11, 2, 685368, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 11, 2, 687567, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "error", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 11, 2, 687567, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 11, 31, 716803, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "errored", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "errored", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 11, 31, 719559, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "send", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "delayed", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "send", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 16, 26, 154811, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "send", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "queued", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "send", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 16, 26, 157940, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "historical_permission_codename": "can_retry",
            "historical_permission_content_type_app_label": "vueda_vdq",
            "historical_permission_content_type_model_name": "queueitem",
            "id": {
                "historical_permission_codename": "can_retry",
                "historical_permission_content_type_app_label": "vueda_vdq",
                "historical_permission_content_type_model_name": "queueitem",
                "transition_id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
            },
            "permission_id": {
                "codename": "can_retry",
                "content_type_id": {"app_label": "vueda_vdq", "model": "queueitem"},
            },
            "transition_id": {"code": "retry", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 16, 55, 373727, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "succeed", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "succeed", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 17, 18, 831906, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "succeed", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "sending", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "succeed", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 17, 18, 835129, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
                "transition_id": {"code": "timeout", "workflow_id": {"code": "queueitem"}},
            },
            "source_id": {"code": "awaiting", "workflow_id": {"code": "queueitem"}},
            "transition_id": {"code": "timeout", "workflow_id": {"code": "queueitem"}},
        },
        "history_date": datetime.datetime(2025, 9, 19, 17, 17, 29, 698411, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
]


def forwards_migrate_workflow(apps, schema_editor):
    for changed_item in copy.deepcopy(changed_data):  # Copied, so tests can migrate forwards and backwards.
        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item)

            case "state":
                handle_state(apps, changed_item)

            case "statepermission":
                handle_state_permission(apps, changed_item)

            case "initialstate":
                handle_initial_state(apps, changed_item)

            case "transition":
                handle_transition(apps, changed_item)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item)

            case "transitionsource":
                handle_transition_source(apps, changed_item)


def backwards_migrate_workflow(apps, schema_editor):
    # Make sure we go through the changed_data in reverse order, so we undo things correctly.
    for changed_item in reversed(copy.deepcopy(changed_data)):  # Copied, so tests can migrate forwards and backwards.
        match changed_item["history_type"]:
            case "added":
                changed_item["history_type"] = "deleted"

            case "deleted":
                changed_item["history_type"] = "added"

        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, reversing=True)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, reversing=True)

            case "state":
                handle_state(apps, changed_item, reversing=True)

            case "statepermission":
                handle_state_permission(apps, changed_item, reversing=True)

            case "initialstate":
                handle_initial_state(apps, changed_item, reversing=True)

            case "transition":
                handle_transition(apps, changed_item, reversing=True)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, reversing=True)

            case "transitionsource":
                handle_transition_source(apps, changed_item, reversing=True)


class SkippableRunSQL(migrations.RunSQL):
    def __init__(
        self,
        *args,
        skippable=False,
        skippable_env_variable="migration_skip",
        skip_all_env_variable="skip_migration_when_setting_up_db",
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.skippable = skippable
        self.skippable_env_variable = skippable_env_variable
        self.skip_all_env_variable = skip_all_env_variable

    def _run_sql(self, *args, **kwargs):
        skip_all = os.environ.get(self.skip_all_env_variable, "").lower() == "true"
        skip = self.skippable and os.environ.get(self.skippable_env_variable, "").lower() == "true"

        if skip_all:
            return

        if not skip:
            super()._run_sql(*args, **kwargs)


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config(migration_app_label)
    create_permissions(app, interactive=False)


def handle_workflow(apps, changed_item, *, reversing=False):
    historical_workflow = apps.get_model("vueda_workflow", "HistoricalWorkflow")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            del data["id"]  # This needs to be removed before we create.

            workflow = model_workflow.objects.create(**data)

            add_history_to_data(
                data,
                workflow,
                "+",
                changed_item["history_date"],
            )
            historical_workflow.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(workflow, data, reversing=reversing)
            add_history_to_data(
                data,
                workflow,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "content_type_id",
                    "historical_app_label",
                    "historical_model",
                    "name",
                ),
            )
            historical_workflow.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            workflow = model_workflow.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow, "-", changed_item["history_date"])
            historical_workflow.objects.create(**data)
            workflow.delete()


def handle_workflow_permission(apps, changed_item, *, reversing=False):
    historical_workflow_permission = apps.get_model("vueda_workflow", "HistoricalWorkflowPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")
    model_workflow_permission = apps.get_model("vueda_workflow", "WorkflowPermission")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            workflow_permission = model_workflow_permission.objects.create(**data)

            add_history_to_data(data, workflow_permission, "+", changed_item["history_date"])
            historical_workflow_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            apply_and_save_changes(workflow_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                workflow_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "workflow_id",
                ),
            )
            historical_workflow_permission.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow_permission, "-", changed_item["history_date"])
            historical_workflow_permission.objects.create(**data)
            workflow_permission.delete()


def handle_state(apps, changed_item, *, reversing=False):
    historical_state = apps.get_model("vueda_workflow", "HistoricalState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            state = model_state.objects.create(**data)

            add_history_to_data(data, state, "+", changed_item["history_date"])
            historical_state.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(state, data, reversing=reversing)
            add_history_to_data(
                data,
                state,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "name",
                    "workflow_id",
                ),
            )
            historical_state.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            state = model_state.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state, "-", changed_item["history_date"])
            historical_state.objects.create(**data)
            state.delete()


def handle_state_permission(apps, changed_item, *, reversing=False):
    historical_state_permission = apps.get_model("vueda_workflow", "HistoricalStatePermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_group = apps.get_model("auth", "Group")
    model_permission = apps.get_model("auth", "Permission")
    model_state = apps.get_model("vueda_workflow", "State")
    model_state_permission = apps.get_model("vueda_workflow", "StatePermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["group_id"])
            data["group_id"] = group.pk

            del data["id"]  # This needs to be removed before we create.

            state_permission = model_state_permission.objects.create(**data)

            add_history_to_data(data, state_permission, "+", changed_item["history_date"])
            historical_state_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            group = model_group.objects.get(**get_id_values_from_item(data["id"]["group_id"], reversing=reversing))
            data["id"]["group_id"] = group.pk
            state_permission = model_state_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["group_id"]) is tuple:
                new_group_ids = []
                for group_id in data["group_id"]:
                    group = model_group.objects.get(**group_id)
                    new_group_ids.append(group.pk)
                data["group_id"] = tuple(new_group_ids)

            apply_and_save_changes(state_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                state_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "grant_or_deny",
                    "group_id",
                    "historical_group_name",
                    "historical_permission_codename",
                    "permission_id",
                    "state_id",
                ),
            )
            historical_state_permission.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["id"]["group_id"])
            data["id"]["group_id"] = group.pk
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state_permission, "-", changed_item["history_date"])
            historical_state_permission.objects.create(**data)
            state_permission.delete()


def handle_initial_state(apps, changed_item, *, reversing=False):
    historical_initial_state = apps.get_model("vueda_workflow", "HistoricalInitialState")
    model_initial_state = apps.get_model("vueda_workflow", "InitialState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])

            data["state_id"] = state.pk
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            initial_state = model_initial_state.objects.create(**data)

            add_history_to_data(data, initial_state, "+", changed_item["history_date"])
            historical_initial_state.objects.create(**data)

        case "changed":
            data["id"]["state_id"] = get_id_values_from_item(data["id"]["state_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["state_id"]) is tuple:
                state_ids = []
                for state_data in data["state_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["state_id"] = tuple(state_ids)

            apply_and_save_changes(initial_state, data, reversing=reversing)
            add_history_to_data(
                data,
                initial_state,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "state_id",
                    "workflow_id",
                ),
            )
            historical_initial_state.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            add_history_to_data(data, initial_state, "-", changed_item["history_date"])
            historical_initial_state.objects.create(**data)
            initial_state.delete()


def handle_transition(apps, changed_item, *, reversing=False):
    historical_transition = apps.get_model("vueda_workflow", "HistoricalTransition")
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            del data["id"]  # This needs to be removed before we create.

            transition = model_transition.objects.create(**data)

            add_history_to_data(data, transition, "+", changed_item["history_date"])
            historical_transition.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["target_id"]) is tuple:
                state_ids = []
                for state_data in data["target_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["target_id"] = tuple(state_ids)

            apply_and_save_changes(transition, data, reversing=reversing)
            add_history_to_data(
                data,
                transition,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "name",
                    "target_id",
                    "workflow_id",
                ),
            )
            historical_transition.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition, "-", changed_item["history_date"])
            historical_transition.objects.create(**data)
            transition.delete()


def handle_transition_permission(apps, changed_item, *, reversing=False):
    historical_transition_permission = apps.get_model("vueda_workflow", "HistoricalTransitionPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_permission = apps.get_model("vueda_workflow", "TransitionPermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            transition_permission = model_transition_permission.objects.create(**data)

            add_history_to_data(data, transition_permission, "+", changed_item["history_date"])
            historical_transition_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    state = model_transition.objects.get(**transition_data)
                    transition_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_permission, data, reversing=reversing)
            add_history_to_data(
                data,
                transition_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "transition_id",
                ),
            )
            historical_transition_permission.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_permission, "-", changed_item["history_date"])
            historical_transition_permission.objects.create(**data)
            transition_permission.delete()


def handle_transition_source(apps, changed_item, *, reversing=False):
    historical_transition_source = apps.get_model("vueda_workflow", "HistoricalTransitionSource")
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_source = apps.get_model("vueda_workflow", "TransitionSource")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["source_id"]["workflow_id"])
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["source_id"])
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            transition_source = model_transition_source.objects.create(**data)

            add_history_to_data(data, transition_source, "+", changed_item["history_date"])
            historical_transition_source.objects.create(**data)

        case "changed":
            data["id"]["source_id"] = get_id_values_from_item(data["id"]["source_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk

            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["source_id"]) is tuple:
                state_ids = []
                for state_data in data["source_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                data["source_id"] = tuple(state_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    transition = model_transition.objects.get(**transition_data)
                    transition_ids.append(transition.pk)
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_source, data, reversing=reversing)
            add_history_to_data(
                data,
                transition_source,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "source_id",
                    "transition_id",
                ),
            )
            historical_transition_source.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_source, "-", changed_item["history_date"])
            historical_transition_source.objects.create(**data)
            transition_source.delete()


def add_history_to_data(history_data, obj, history_type, history_date, fields=()):
    # For changed history
    for field_name in fields:
        history_data[field_name] = getattr(obj, field_name)

    # For all history
    history_data["history_change_reason"] = history_change_reason
    history_data["history_date"] = history_date
    history_data["history_relation_id"] = obj.pk
    history_data["history_type"] = history_type
    history_data["id"] = obj.pk


def apply_and_save_changes(obj, data, *, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    for key, values in data.items():
        if type(values) is not tuple:
            continue

        old_value, new_value = values

        if reversing:
            setattr(obj, key, old_value)

        else:
            setattr(obj, key, new_value)

    obj.save()


def get_id_values_from_item(values, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    if type(values) is tuple:
        return values[1 if reversing else 0]

    return values


def get_id_values_from_dict(id_data, reversing=False):
    results = {}
    for field_name, values in id_data.items():
        results[field_name] = get_id_values_from_item(values, reversing)

    return results


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vueda_workflow", "0004_alter_statepermission_options_and_more"),
        ("vueda_vdq", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow,
            reverse_code=backwards_migrate_workflow,
        ),
    ]
