# Generated by Django 5.2.6 on 2025-09-22 23:17

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vueda_vdq", "0002_workflow_migrations_2025_09_22"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueitem",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
