# Generated by Django 5.2.6 on 2025-09-26 22:11

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_vdq", "0003_alter_queueitem_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueitem",
            name="done_since",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="object_id",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
