# Generated by Django 5.2.8 on 2025-12-03 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vueda_vdq", "0005_workflow_migrations_2025_11_21"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentitem",
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "verbose_name": "Sent Item",
            },
        ),
    ]
