# Generated by Django 6.1 on 2026-09-02 19:36

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("vueda_vdq", "0006_alter_sentitem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueItemEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("object_id", models.PositiveSmallIntegerField(null=True)),
                ("method", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=255)),
                ("result", models.TextField(default="")),
                ("retry_delay", models.IntegerField(default=0, help_text="seconds")),
                ("queued", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("done_since", models.DateTimeField(default=django.utils.timezone.now)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReceiverEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("cell", phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SenderEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("cell", phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitem",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_queueitemevent" ("content_type_id", "done_since", "id", "last_updated", "method", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "queued", "receiver_id", "result", "retry_delay", "sender_id", "task_id") VALUES (NEW."content_type_id", NEW."done_since", NEW."id", NEW."last_updated", NEW."method", NEW."object_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."queued", NEW."receiver_id", NEW."result", NEW."retry_delay", NEW."sender_id", NEW."task_id"); RETURN NULL;',
                    hash="c3d21d086fd609f65e77d93a9bb25441c31b11cd",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_c9480",
                    table="vueda_vdq_queueitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitem",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_vdq_queueitemevent" ("content_type_id", "done_since", "id", "last_updated", "method", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "queued", "receiver_id", "result", "retry_delay", "sender_id", "task_id") VALUES (NEW."content_type_id", NEW."done_since", NEW."id", NEW."last_updated", NEW."method", NEW."object_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."queued", NEW."receiver_id", NEW."result", NEW."retry_delay", NEW."sender_id", NEW."task_id"); RETURN NULL;',
                    hash="f67d8e5d4845bf35fa4a697ec26e5727e3e60c3c",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d3583",
                    table="vueda_vdq_queueitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitem",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_queueitemevent" ("content_type_id", "done_since", "id", "last_updated", "method", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "queued", "receiver_id", "result", "retry_delay", "sender_id", "task_id") VALUES (OLD."content_type_id", OLD."done_since", OLD."id", OLD."last_updated", OLD."method", OLD."object_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."queued", OLD."receiver_id", OLD."result", OLD."retry_delay", OLD."sender_id", OLD."task_id"); RETURN NULL;',
                    hash="d6b0f50174f35fb2b0083cb1046ebbb14a055a80",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ac9cf",
                    table="vueda_vdq_queueitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiver",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_receiverevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="48cf92d53a5661e1a56f45204f0a920ef299dc7b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_475a0",
                    table="vueda_vdq_receiver",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiver",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_vdq_receiverevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="dc4bed1e1d48cac852d73b048b003ce73ac4c6f1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3ba56",
                    table="vueda_vdq_receiver",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiver",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_receiverevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cell", OLD."email", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="696422030146ff400e7593156fbf0b887830678d",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ede81",
                    table="vueda_vdq_receiver",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sender",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_senderevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="d6e0362db1f86ea95bd45fdfa6d2eb8b9b499253",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e1aa8",
                    table="vueda_vdq_sender",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sender",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_vdq_senderevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;',
                    hash="b812c0b216f857fda2c9dc0e744e8fa8d0a1232d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_7b565",
                    table="vueda_vdq_sender",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sender",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_senderevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cell", OLD."email", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="11dc61cfe2e250b781dbbf84500adc1d24bc4fd9",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_27b1f",
                    table="vueda_vdq_sender",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="content_type",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_vdq.queueitem",
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="receiver",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="sender",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.VUEDA_VDQ_SENDER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receiverevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="receiverevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="senderevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="senderevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to=settings.VUEDA_VDQ_SENDER_MODEL,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitemevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="9aff5d0198c847415c7a0dde89a72f6febd695fb",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ab8af",
                    table="vueda_vdq_queueitemevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiverevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2e816567864d690d7df1cbe1904fa52946287f30",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_7e3ca",
                    table="vueda_vdq_receiverevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="senderevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="59c5732ce72717457230b2d529a04b55091efdc6",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_9b27b",
                    table="vueda_vdq_senderevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
