# Generated by Django 6.1 on 2026-09-03 16:30

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("vueda_vdq", "0006_alter_sentitem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueItemEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("object_id", models.PositiveSmallIntegerField(null=True)),
                ("method", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=255)),
                ("result", models.TextField(default="")),
                ("retry_delay", models.IntegerField(default=0, help_text="seconds")),
                ("queued", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("done_since", models.DateTimeField(default=django.utils.timezone.now)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReceiverEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("cell", phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SenderEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("cell", phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitem",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_queueitemevent" ("content_type_id", "done_since", "id", "last_updated", "method", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "queued", "receiver_id", "result", "retry_delay", "sender_id", "task_id") VALUES (NEW."content_type_id", NEW."done_since", NEW."id", NEW."last_updated", NEW."method", NEW."object_id", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id", NEW."queued", NEW."receiver_id", NEW."result", NEW."retry_delay", NEW."sender_id", NEW."task_id"); RETURN NULL;',
                    hash="31b6b637cddac10b18fa023f39ba386ec96acafb",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_c9480",
                    table="vueda_vdq_queueitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitem",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_vdq_queueitemevent" ("content_type_id", "done_since", "id", "last_updated", "method", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "queued", "receiver_id", "result", "retry_delay", "sender_id", "task_id") VALUES (NEW."content_type_id", NEW."done_since", NEW."id", NEW."last_updated", NEW."method", NEW."object_id", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id", NEW."queued", NEW."receiver_id", NEW."result", NEW."retry_delay", NEW."sender_id", NEW."task_id"); RETURN NULL;',
                    hash="b2a229f6013077aaae7dc8ce16be2224669eb9ec",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d3583",
                    table="vueda_vdq_queueitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitem",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_queueitemevent" ("content_type_id", "done_since", "id", "last_updated", "method", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "queued", "receiver_id", "result", "retry_delay", "sender_id", "task_id") VALUES (OLD."content_type_id", OLD."done_since", OLD."id", OLD."last_updated", OLD."method", OLD."object_id", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id", OLD."queued", OLD."receiver_id", OLD."result", OLD."retry_delay", OLD."sender_id", OLD."task_id"); RETURN NULL;',
                    hash="d937a7b039828070b6db49fc78401898de65ddfa",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ac9cf",
                    table="vueda_vdq_queueitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiver",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_receiverevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="72e649e8dc16d40f8ffb3416559aa5a3a8551824",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_475a0",
                    table="vueda_vdq_receiver",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiver",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_vdq_receiverevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id"); RETURN NULL;',
                    hash="97931d4216da5c7832074355e9a8c08e139080d0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3ba56",
                    table="vueda_vdq_receiver",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiver",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_receiverevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cell", OLD."email", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="96edd804ed617cff51eb8faf856105cc17f5e80b",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_ede81",
                    table="vueda_vdq_receiver",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sender",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_senderevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'insert\', NEW."id"); RETURN NULL;',
                    hash="0999fa8972a96f0e8550b66f7fcc6d628050a322",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e1aa8",
                    table="vueda_vdq_sender",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sender",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "vueda_vdq_senderevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."cell", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), clock_timestamp(), \'update\', NEW."id"); RETURN NULL;',
                    hash="58e0baf0c5bba1f83fd66ebc8b83d89341aff333",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_7b565",
                    table="vueda_vdq_sender",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sender",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "vueda_vdq_senderevent" ("cell", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."cell", OLD."email", OLD."id", OLD."name", _pgh_attach_context(), clock_timestamp(), \'delete\', OLD."id"); RETURN NULL;',
                    hash="96b858899b3c41d39e2b36f801564892bbe46bbf",
                    operation="DELETE",
                    pgid="pgtrigger_delete_delete_27b1f",
                    table="vueda_vdq_sender",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="content_type",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="vueda_vdq.queueitem",
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="receiver",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queueitemevent",
            name="sender",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.VUEDA_VDQ_SENDER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receiverevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="receiverevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to=settings.VUEDA_VDQ_RECEIVER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="senderevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="senderevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to=settings.VUEDA_VDQ_SENDER_MODEL,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="queueitemevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="9aff5d0198c847415c7a0dde89a72f6febd695fb",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ab8af",
                    table="vueda_vdq_queueitemevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="receiverevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2e816567864d690d7df1cbe1904fa52946287f30",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_7e3ca",
                    table="vueda_vdq_receiverevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="senderevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="59c5732ce72717457230b2d529a04b55091efdc6",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_9b27b",
                    table="vueda_vdq_senderevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
