# Generated by Django 5.0.4 on 2024-05-13 22:20

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0001_initial"),
        ("vueda_workflow", "__latest__"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowChanged",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "formatted_name",
                    models.GeneratedField(
                        db_persist=True, expression=models.F("name"), output_field=models.CharField()
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "default_permissions": ("create", "read", "update", "delete", "list"),
                "permissions": (
                    ("can_do_something", "Can do something"),
                    ("can_do_something_else", "Can do something else"),
                    ("can_do_another_thing", "Can do another thing"),
                ),
            },
        ),
    ]
