# Generated by Django 5.0.4 on 2024-05-13 16:05

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import DEFAULT_DB_ALIAS
from django.db import migrations


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config("workflow_changed")
    create_permissions(
        app,
        verbosity=2,
        interactive=False,
        using=DEFAULT_DB_ALIAS,
        apps=apps,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_changed", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_sure_permissions_exist, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group
                (
                    name
                )
            VALUES
                (
                    'WorkflowChangedAdmin'
                ),
                (
                    'WorkflowChangedWorker'
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group
            WHERE
                name IN ('WorkflowChangedAdmin', 'WorkflowChangedWorker');""",
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO
                auth_group_permissions
                (
                    group_id,
                    permission_id
                )
            VALUES
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowChangedAdmin'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_changed'
                                    AND model = 'workflowchanged'
                        )
                    )
                ),
                (
                    (SELECT id FROM auth_group WHERE name = 'WorkflowChangedWorker'),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_something_else'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_changed'
                                    AND model = 'workflowchanged'
                        )
                    )
                );""",
            reverse_sql="""
            DELETE FROM
                auth_group_permissions
            WHERE
                group_id IN (
                    SELECT
                        id
                    FROM
                        auth_group
                    WHERE
                        name IN ('WorkflowChangedAdmin', 'WorkflowChangedWorker')
                );""",
        ),
    ]
