# Generated by Django 5.0.4 on 2024-05-14 15:39
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
import copy
import datetime
import enum

from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations

from vueda.core.audit import audited_action


history_change_reason = "Workflow Migration - 0003_workflow_migrations_2024_05_14"
migration_app_label = "workflow_changed"
changed_data = [
    {
        "changes": {
            "code": "changed_workflow",
            "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            "historical_app_label": "workflow_changed",
            "historical_model": "workflowchanged",
            "id": {"code": "changed_workflow"},
            "name": "Changed Workflow",
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 51, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "can_do_something",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": "can_do_something",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "workflow_id": {"code": "changed_workflow"},
            },
            "permission_id": {
                "codename": "can_do_something",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 52, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "can_do_something_else",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": "can_do_something_else",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "workflow_id": {"code": "changed_workflow"},
            },
            "permission_id": {
                "codename": "can_do_something_else",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 53, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "code": "state_1",
            "id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
            "name": "State 1",
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 54, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "state_2",
            "id": {"code": "state_2", "workflow_id": {"code": "changed_workflow"}},
            "name": "State 2",
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 55, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "state_3",
            "id": {"code": "state_3", "workflow_id": {"code": "changed_workflow"}},
            "name": "State 3",
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 56, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "grant_or_deny": False,
            "group_id": {"name": "WorkflowChangedAdmin"},
            "historical_group_name": "WorkflowChangedAdmin",
            "historical_permission_codename": "can_do_something",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "group_id": {"name": "WorkflowChangedAdmin"},
                "historical_group_name": "WorkflowChangedAdmin",
                "historical_permission_codename": "can_do_something",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "state_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
            },
            "permission_id": {
                "codename": "can_do_something",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "state_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 57, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "statepermission",
    },
    {
        "changes": {
            "grant_or_deny": True,
            "group_id": {"name": "WorkflowChangedWorker"},
            "historical_group_name": "WorkflowChangedWorker",
            "historical_permission_codename": "can_do_something_else",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "group_id": {"name": "WorkflowChangedWorker"},
                "historical_group_name": "WorkflowChangedWorker",
                "historical_permission_codename": "can_do_something_else",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "state_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
            },
            "permission_id": {
                "codename": "can_do_something_else",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "state_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 58, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "statepermission",
    },
    {
        "changes": {
            "grant_or_deny": True,
            "group_id": {"name": "WorkflowChangedAdmin"},
            "historical_group_name": "WorkflowChangedAdmin",
            "historical_permission_codename": "update_workflowchanged",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "group_id": {"name": "WorkflowChangedAdmin"},
                "historical_group_name": "WorkflowChangedAdmin",
                "historical_permission_codename": "update_workflowchanged",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "state_id": {"code": "state_2", "workflow_id": {"code": "changed_workflow"}},
            },
            "permission_id": {
                "codename": "update_workflowchanged",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "state_id": {"code": "state_2", "workflow_id": {"code": "changed_workflow"}},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 22, 59, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "statepermission",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
                "workflow_id": {"code": "changed_workflow"},
            },
            "state_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "go_to_state_1",
            "id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            "name": "Go To State 1",
            "target_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 1, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "go_to_state_2",
            "id": {"code": "go_to_state_2", "workflow_id": {"code": "changed_workflow"}},
            "name": "Go To State 2",
            "target_id": {"code": "state_2", "workflow_id": {"code": "changed_workflow"}},
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 2, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "code": "go_to_state_3",
            "id": {"code": "go_to_state_3", "workflow_id": {"code": "changed_workflow"}},
            "name": "Go To State 3",
            "target_id": {"code": "state_3", "workflow_id": {"code": "changed_workflow"}},
            "workflow_id": {"code": "changed_workflow"},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 3, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": "can_do_something",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": "can_do_something",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "transition_id": {"code": "go_to_state_2", "workflow_id": {"code": "changed_workflow"}},
            },
            "permission_id": {
                "codename": "can_do_something",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "transition_id": {"code": "go_to_state_2", "workflow_id": {"code": "changed_workflow"}},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 4, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "can_do_something_else",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": "can_do_something_else",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            },
            "permission_id": {
                "codename": "can_do_something_else",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 5, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "update_workflowchanged",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": "update_workflowchanged",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            },
            "permission_id": {
                "codename": "update_workflowchanged",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 6, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
                "transition_id": {"code": "go_to_state_2", "workflow_id": {"code": "changed_workflow"}},
            },
            "source_id": {"code": "state_1", "workflow_id": {"code": "changed_workflow"}},
            "transition_id": {"code": "go_to_state_2", "workflow_id": {"code": "changed_workflow"}},
            "ignored": False,
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 7, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "state_2", "workflow_id": {"code": "changed_workflow"}},
                "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            },
            "source_id": {"code": "state_2", "workflow_id": {"code": "changed_workflow"}},
            "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            "ignored": False,
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 8, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
    {
        "changes": {
            "id": {
                "source_id": {"code": "state_3", "workflow_id": {"code": "changed_workflow"}},
                "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            },
            "source_id": {"code": "state_3", "workflow_id": {"code": "changed_workflow"}},
            "transition_id": {"code": "go_to_state_1", "workflow_id": {"code": "changed_workflow"}},
            "ignored": False,
        },
        "history_date": datetime.datetime(2024, 5, 14, 21, 23, 9, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "transitionsource",
    },
]


def forwards_migrate_workflow_through_imports(apps, schema_editor):  # pragma: no cover
    # Copied changed_data, so tests can migrate forwards and backwards.
    forwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def backwards_migrate_workflow_through_imports(apps, schema_editor):  # pragma: no cover
    # Copied changed_data, so tests can migrate forwards and backwards.
    backwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def make_sure_permissions_exist_through_imports(apps, schema_editor):  # pragma: no cover
    make_sure_permissions_exist(migration_app_label)


class WorkflowChangeTypes(enum.Enum):
    ADDED = "added"
    CHANGED = "changed"
    DELETED = "deleted"


def workflow_migration_action(apps, change_reason):
    """Group every write a generated workflow migration makes under one action.

    The events a migration writes are attributed to the system user and labelled with the migration
    that wrote them, so reading history back separates a migration's writes from a person's edit.
    Nothing else in the migration needs to know about it: the triggers record whatever the block
    writes, under whatever context is open.

    The user model is read through the migration's own registry, because a migration must not depend
    on the shape the live model has now.
    """
    user_model = apps.get_model(settings.AUTH_USER_MODEL)
    system_user = user_model.objects.filter(is_system=True).first()
    # The kind is written out rather than named, because this function's source is copied into a
    # generated migration and a module constant would not go with it. It matches MIGRATION_ACTION_KIND.
    return audited_action(change_reason, kind="migration", user=system_user and system_user.pk)


def forwards_migrate_workflow(apps, changed_items, change_reason):
    with workflow_migration_action(apps, change_reason):
        _forwards_migrate_workflow(apps, changed_items, change_reason)


def _forwards_migrate_workflow(apps, changed_items, change_reason):
    for changed_item in changed_items:
        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, change_reason)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, change_reason)

            case "state":
                handle_state(apps, changed_item, change_reason)

            case "statepermission":
                handle_state_permission(apps, changed_item, change_reason)

            case "initialstate":
                handle_initial_state(apps, changed_item, change_reason)

            case "transition":
                handle_transition(apps, changed_item, change_reason)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, change_reason)

            case "transitionsource":
                handle_transition_source(apps, changed_item, change_reason)

    handle_state_objects(apps)


def backwards_migrate_workflow(apps, changed_items, change_reason):
    with workflow_migration_action(apps, change_reason):
        _backwards_migrate_workflow(apps, changed_items, change_reason)


def _backwards_migrate_workflow(apps, changed_items, change_reason):
    handle_state_objects(apps, reversing=True)

    # Make sure we go through the changed_items in reverse order, so we undo things correctly.
    for changed_item in reversed(changed_items):
        match changed_item["history_type"]:
            case WorkflowChangeTypes.ADDED.value:
                changed_item["history_type"] = WorkflowChangeTypes.DELETED.value

            case WorkflowChangeTypes.DELETED.value:
                changed_item["history_type"] = WorkflowChangeTypes.ADDED.value

        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, change_reason, reversing=True)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, change_reason, reversing=True)

            case "state":
                handle_state(apps, changed_item, change_reason, reversing=True)

            case "statepermission":
                handle_state_permission(apps, changed_item, change_reason, reversing=True)

            case "initialstate":
                handle_initial_state(apps, changed_item, change_reason, reversing=True)

            case "transition":
                handle_transition(apps, changed_item, change_reason, reversing=True)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, change_reason, reversing=True)

            case "transitionsource":
                handle_transition_source(apps, changed_item, change_reason, reversing=True)


def make_sure_permissions_exist(app_label):
    app = django_apps.get_app_config(app_label)
    create_permissions(app, interactive=False)


def handle_workflow(apps, changed_item, change_reason, *, reversing=False):
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            del data["id"]  # This needs to be removed before we create.

            model_workflow.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(workflow, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"])

            workflow.delete()


def handle_workflow_permission(apps, changed_item, change_reason, *, reversing=False):
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")
    model_workflow_permission = apps.get_model("vueda_workflow", "WorkflowPermission")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            model_workflow_permission.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            apply_and_save_changes(workflow_permission, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(**data["id"])

            workflow_permission.delete()


def handle_state(apps, changed_item, change_reason, *, reversing=False):
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            model_state.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            apply_and_save_changes(state, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            state = model_state.objects.get(**data["id"])

            state.delete()


def handle_state_permission(apps, changed_item, change_reason, *, reversing=False):
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_group = apps.get_model("auth", "Group")
    model_permission = apps.get_model("auth", "Permission")
    model_state = apps.get_model("vueda_workflow", "State")
    model_state_permission = apps.get_model("vueda_workflow", "StatePermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["group_id"])
            data["group_id"] = group.pk

            del data["id"]  # This needs to be removed before we create.

            model_state_permission.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            group = model_group.objects.get(**get_id_values_from_item(data["id"]["group_id"], reversing=reversing))
            data["id"]["group_id"] = group.pk
            state_permission = model_state_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["group_id"]) is tuple:
                new_group_ids = []
                for group_id in data["group_id"]:
                    group = model_group.objects.get(**group_id)
                    new_group_ids.append(group.pk)
                data["group_id"] = tuple(new_group_ids)

            apply_and_save_changes(state_permission, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            group = model_group.objects.get(**data["id"]["group_id"])
            data["id"]["group_id"] = group.pk

            state_permission = model_state_permission.objects.get(**data["id"])

            state_permission.delete()


def handle_initial_state(apps, changed_item, change_reason, *, reversing=False):
    model_initial_state = apps.get_model("vueda_workflow", "InitialState")
    model_state = apps.get_model("vueda_workflow", "State")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])

            data["state_id"] = state.pk
            data["workflow_id"] = workflow.pk

            del data["id"]  # This needs to be removed before we create.

            model_initial_state.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            data["id"]["state_id"] = get_id_values_from_item(data["id"]["state_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["state_id"]) is tuple:
                state_ids = []
                for state_data in data["state_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["state_id"] = tuple(state_ids)

            apply_and_save_changes(initial_state, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            initial_state.delete()


def handle_transition(apps, changed_item, change_reason, *, reversing=False):
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            del data["id"]  # This needs to be removed before we create.

            model_transition.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["target_id"]) is tuple:
                state_ids = []
                for state_data in data["target_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["target_id"] = tuple(state_ids)

            apply_and_save_changes(transition, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**data["id"])

            transition.delete()


def handle_transition_permission(apps, changed_item, change_reason, *, reversing=False):
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_permission = apps.get_model("vueda_workflow", "TransitionPermission")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            model_transition_permission.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["permission_id"]) is tuple:
                new_permission_ids = []
                for permission_id in data["permission_id"]:
                    content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                    permission_id["content_type_id"] = content_type.pk
                    permission = model_permission.objects.get(**permission_id)
                    new_permission_ids.append(permission.pk)
                data["permission_id"] = tuple(new_permission_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    state = model_transition.objects.get(**transition_data)
                    transition_ids.append(state.pk)
                    data["workflow_id"] = workflow.pk
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_permission, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(**data["id"])

            transition_permission.delete()


def handle_transition_source(apps, changed_item, change_reason, *, reversing=False):
    model_state = apps.get_model("vueda_workflow", "State")
    model_transition = apps.get_model("vueda_workflow", "Transition")
    model_transition_source = apps.get_model("vueda_workflow", "TransitionSource")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case WorkflowChangeTypes.ADDED.value:
            workflow = model_workflow.objects.get(**data["source_id"]["workflow_id"])
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["source_id"])
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            del data["id"]  # This needs to be removed before we create.

            model_transition_source.objects.create(**data)

        case WorkflowChangeTypes.CHANGED.value:
            data["id"]["source_id"] = get_id_values_from_item(data["id"]["source_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk

            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["source_id"]) is tuple:
                state_ids = []
                for state_data in data["source_id"]:
                    workflow = model_workflow.objects.get(**state_data["workflow_id"])
                    state_data["workflow_id"] = workflow.pk
                    state = model_state.objects.get(**state_data)
                    state_ids.append(state.pk)
                data["source_id"] = tuple(state_ids)

            # If the value is changed, it is a tuple.  We need to get the ids for each item.
            if type(data["transition_id"]) is tuple:
                transition_ids = []
                for transition_data in data["transition_id"]:
                    workflow = model_workflow.objects.get(**transition_data["workflow_id"])
                    transition_data["workflow_id"] = workflow.pk
                    transition = model_transition.objects.get(**transition_data)
                    transition_ids.append(transition.pk)
                data["transition_id"] = tuple(transition_ids)

            apply_and_save_changes(transition_source, data, reversing=reversing)

        case WorkflowChangeTypes.DELETED.value:
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(**data["id"])

            transition_source.delete()


def handle_state_objects(apps, *, reversing=False):
    model_object_state_event = apps.get_model("vueda_workflow", "ObjectStateEvent")
    model_object_state = apps.get_model("vueda_workflow", "ObjectState")
    model_workflow = apps.get_model("vueda_workflow", "Workflow")

    for workflow in model_workflow.objects.all():
        model_obj = apps.get_model(workflow.historical_app_label, workflow.historical_model)
        manage_state_objects(workflow, model_obj, model_object_state, model_object_state_event, reversing=reversing)


def manage_state_objects(workflow, obj_class, workflow_obj_state_class, object_state_event_class, *, reversing=False):
    """Give every object of a workflow its initial state, and move one nothing has changed since.

    An object state with only its creation recorded against it is still wherever it was put, so a
    changed initial state moves it. One that carries any later event was moved by someone, and the
    state they moved it to is theirs to keep.

    TODO: An earlier run of this counts as someone, because its update is an event like any other.
      A workflow whose initial state changes twice therefore moves its objects only the first time.
      Telling the two apart needs the sync's own writes to be identifiable, which the action context
      cannot currently do here: pghistory sets its context as a transaction-local, so an action
      opened around these writes is still attributed to everything else written in the same
      transaction.
    """
    if reversing:
        # Delete all object states
        workflow_obj_state_class.objects.filter(workflow=workflow).delete()
        return

    initial_state = getattr(workflow, "initial_state", None)
    if initial_state is None:
        # A workflow part-way through its own migration has no initial state to give anything.
        return

    for obj in obj_class.objects.all():
        obj_state = workflow_obj_state_class.objects.filter(workflow=workflow, object_id=obj.pk).first()

        if obj_state is None:
            workflow_obj_state_class.objects.create(
                workflow=workflow,
                object_id=obj.id,
                state=initial_state.state,
            )
            continue

        if obj_state.state_id == initial_state.state_id:
            continue

        changed_since_created = (
            object_state_event_class.objects.filter(pgh_obj_id=obj_state.pk).exclude(pgh_label="insert").exists()
        )
        if not changed_since_created:
            workflow_obj_state_class.objects.filter(pk=obj_state.pk).update(state_id=initial_state.state_id)


def add_history_to_data(history_data, obj, history_type, history_date, change_reason, fields=()):
    # For changed history
    for field_name in fields:
        history_data[field_name] = getattr(obj, field_name)

    # For all history
    history_data["history_change_reason"] = change_reason
    history_data["history_date"] = history_date
    history_data["history_relation_id"] = obj.pk
    history_data["history_type"] = history_type
    history_data["id"] = obj.pk


def apply_and_save_changes(obj, data, *, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    for key, values in data.items():
        if type(values) is not tuple:
            continue

        old_value, new_value = values

        if reversing:
            setattr(obj, key, old_value)

        else:
            setattr(obj, key, new_value)

    obj.save()


def get_id_values_from_item(values, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary
    # with 2 keys, or a 2 character string.  A single value can't be a tuple.
    if type(values) is tuple:
        return values[1 if reversing else 0]

    return values


def get_id_values_from_dict(id_data, reversing=False):
    results = {}
    for field_name, values in id_data.items():
        results[field_name] = get_id_values_from_item(values, reversing)

    return results


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("vueda_release", "0001_initial"),
        ("vueda_user", "0001_initial"),
        ("vueda_workflow", "__latest__"),
        ("workflow_changed", "0002_create_workflow_changed_permissions"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist_through_imports,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow_through_imports,
            reverse_code=backwards_migrate_workflow_through_imports,
        ),
    ]
