# Generated by Django 5.0.4 on 2024-05-24 18:56

from django.db import migrations

from vueda.workflow import custom_migration_operations


SKIPPABLE_ENV_VARIABLE = "migration_skip_workflow_changed"


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_changed", "0003_workflow_migrations_2024_05_14"),
    ]

    operations = [
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_workflow
            SET
                name = 'Changed Workflow 2',
                code = 'changed_workflow_2'
            WHERE
                code = 'changed_workflow';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflow
            (
                id,
                code,
                name,
                historical_app_label,
                historical_model,
                history_date,
                history_change_reason,
                history_type,
                content_type_id,
                history_relation_id,
                history_user_id
            )
            SELECT
                W.id,
                W.code,
                W.name,
                W.historical_app_label,
                W.historical_model,
                '2024-05-24 18:56:01',
                'Migration - 0004_change_workflow',
                '~',
                W.content_type_id,
                W.id,
                SYSTEM_USER.id
            FROM
                vueda_workflow_workflow W,
                SYSTEM_USER
            WHERE
                W.code = 'changed_workflow_2';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflowpermission
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                workflow_id
            )
            SELECT
                W.id,
                '2024-05-24 18:56:02',
                'Migration - 0004_change_workflow',
                '-',
                W.id,
                SYSTEM_USER.id,
                W.permission_id,
                W.historical_permission_codename,
                W.historical_permission_content_type_app_label,
                W.historical_permission_content_type_model_name,
                W.workflow_id
            FROM
                vueda_workflow_workflowpermission W,
                SYSTEM_USER
            WHERE
                workflow_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                historical_permission_codename = 'can_do_something';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            DELETE FROM
                vueda_workflow_workflowpermission
            WHERE
                workflow_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                historical_permission_codename = 'can_do_something';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_workflowpermission
            SET
                permission_id = (
                    SELECT
                        id
                    FROM
                        auth_permission
                    WHERE
                        codename = 'can_do_something'
                        AND content_type_id = (
                            SELECT
                                id
                            FROM
                                django_content_type
                            WHERE
                                app_label = 'workflow_changed'
                                AND model = 'workflowchanged'
                    )
                ),
                historical_permission_codename = 'can_do_something'
            WHERE
                workflow_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                permission_id = (
                    SELECT
                        id
                    FROM
                        auth_permission
                    WHERE
                        codename = 'can_do_something_else'
                        AND
                        content_type_id = (
                            SELECT
                                id
                            FROM
                                django_content_type
                            WHERE
                                app_label = 'workflow_changed'
                                AND model = 'workflowchanged'
                        )
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflowpermission
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                workflow_id
            )
            SELECT
                W.id,
                '2024-05-24 18:56:03',
                'Migration - 0004_change_workflow',
                '~',
                W.id,
                SYSTEM_USER.id,
                W.permission_id,
                W.historical_permission_codename,
                W.historical_permission_content_type_app_label,
                W.historical_permission_content_type_model_name,
                W.workflow_id
            FROM
                vueda_workflow_workflowpermission W,
                SYSTEM_USER
            WHERE
                workflow_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                historical_permission_codename = 'can_do_something';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            INSERT INTO
                vueda_workflow_workflowpermission
                (
                    workflow_id,
                    permission_id,
                    historical_permission_codename,
                    historical_permission_content_type_app_label,
                    historical_permission_content_type_model_name
                )
            VALUES
                (
                    (
                        SELECT
                            id
                        FROM
                            vueda_workflow_workflow
                        WHERE
                            code = 'changed_workflow_2'
                    ),
                    (
                        SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_another_thing'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_changed'
                                    AND model = 'workflowchanged'
                        )
                    ),
                    'can_do_another_thing',
                    'workflow_changed',
                    'workflowchanged'
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalworkflowpermission
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                workflow_id
            )
            SELECT
                W.id,
                '2024-05-24 18:56:04',
                'Migration - 0004_change_workflow',
                '+',
                W.id,
                SYSTEM_USER.id,
                W.permission_id,
                W.historical_permission_codename,
                W.historical_permission_content_type_app_label,
                W.historical_permission_content_type_model_name,
                W.workflow_id
            FROM
                vueda_workflow_workflowpermission W,
                SYSTEM_USER
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                       vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                historical_permission_codename = 'can_do_another_thing';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_initialstate
            SET
                state_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_2'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalinitialstate
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                state_id,
                workflow_id
            )
            SELECT
                I.id,
                '2024-05-24 18:56:05',
                'Migration - 0004_change_workflow',
                '~',
                I.id,
                SYSTEM_USER.id,
                I.state_id,
                I.workflow_id
            FROM
                vueda_workflow_initialstate I,
                SYSTEM_USER
            WHERE
                I.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                I.state_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_2'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_state
            SET
                name = 'State 1 A',
                code = 'state_1_a'
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                code = 'state_1';""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalstate
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                workflow_id
            )
            SELECT
                S.id,
                S.code,
                S.name,
                '2024-05-24 18:56:06',
                'Migration - 0004_change_workflow',
                '~',
                S.id,
                SYSTEM_USER.id,
                S.workflow_id
            FROM
                vueda_workflow_state S,
                SYSTEM_USER
            WHERE
                S.workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_statepermission
            SET
                permission_id = (
                    SELECT
                            id
                        FROM
                            auth_permission
                        WHERE
                            codename = 'can_do_another_thing'
                            AND content_type_id = (
                                SELECT
                                    id
                                FROM
                                    django_content_type
                                WHERE
                                    app_label = 'workflow_changed'
                                    AND model = 'workflowchanged'
                        )
                ),
                historical_permission_codename = 'can_do_another_thing',
                group_id = (
                    SELECT id FROM auth_group WHERE name = 'WorkflowChangedWorker'
                ),
                historical_group_name = 'WorkflowChangedWorker',
                grant_or_deny = TRUE
            WHERE
                state_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
                AND
                historical_permission_codename = 'can_do_something'
                AND
                historical_group_name = 'WorkflowChangedAdmin';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicalstatepermission
            (
                id,
                grant_or_deny,
                history_date,
                history_change_reason,
                history_type,
                group_id,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                historical_group_name,
                state_id
            )
            SELECT
                S.id,
                S.grant_or_deny,
                '2024-05-24 18:56:07',
                'Migration - 0004_change_workflow',
                '~',
                S.group_id,
                S.id,
                SYSTEM_USER.id,
                S.permission_id,
                S.historical_permission_codename,
                S.historical_permission_content_type_app_label,
                S.historical_permission_content_type_model_name,
                S.historical_group_name,
                S.state_id
            FROM
                vueda_workflow_statepermission S,
                SYSTEM_USER
            WHERE
                S.state_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
                AND
                S.historical_permission_codename = 'can_do_another_thing'
                AND
                S.historical_group_name = 'WorkflowChangedWorker';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_transition
            SET
                name = 'Go To State 1 A',
                code = 'go_to_state_1_a',
                target_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                code = 'go_to_state_2';
                ;""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicaltransition
            (
                id,
                code,
                name,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                target_id,
                workflow_id
            )
            SELECT
                T.id,
                T.code,
                T.name,
                '2024-05-24 18:56:08',
                'Migration - 0004_change_workflow',
                '~',
                T.id,
                SYSTEM_USER.id,
                T.target_id,
                T.workflow_id
            FROM
                vueda_workflow_transition T,
                SYSTEM_USER
            WHERE
                workflow_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_workflow
                    WHERE
                        code = 'changed_workflow_2'
                )
                AND
                code = 'go_to_state_1_a';
                ;""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_transitionpermission
            SET
                permission_id = (
                    SELECT
                        id
                    FROM
                        auth_permission
                    WHERE
                        codename = 'can_do_another_thing'
                        AND content_type_id = (
                            SELECT
                                id
                            FROM
                                django_content_type
                            WHERE
                                app_label = 'workflow_changed'
                                AND model = 'workflowchanged'
                    )
                ),
                historical_permission_codename = 'can_do_another_thing'
            WHERE
                transition_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_transition
                    WHERE
                        code = 'go_to_state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
                AND
                historical_permission_codename = 'can_do_something';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicaltransitionpermission
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                permission_id,
                historical_permission_codename,
                historical_permission_content_type_app_label,
                historical_permission_content_type_model_name,
                transition_id
            )
            SELECT
                T.id,
                '2024-05-24 18:56:09',
                'Migration - 0004_change_workflow',
                '~',
                T.id,
                SYSTEM_USER.id,
                T.permission_id,
                T.historical_permission_codename,
                T.historical_permission_content_type_app_label,
                T.historical_permission_content_type_model_name,
                T.transition_id
            FROM
                vueda_workflow_transitionpermission T,
                SYSTEM_USER
            WHERE
                T.transition_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_transition
                    WHERE
                        code = 'go_to_state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
                AND
                T.historical_permission_codename = 'can_do_another_thing';""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            UPDATE
                vueda_workflow_transitionsource
            SET
                source_id = (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_2'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
            WHERE
                transition_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_transition
                    WHERE
                        code = 'go_to_state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
                AND
                source_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
        custom_migration_operations.SkippableRunSQL(
            sql="""
            WITH SYSTEM_USER AS (
                SELECT
                    id
                FROM
                    tests_user
                WHERE
                    is_system = TRUE
            )
            INSERT INTO
                vueda_workflow_historicaltransitionsource
            (
                id,
                history_date,
                history_change_reason,
                history_type,
                history_relation_id,
                history_user_id,
                source_id,
                transition_id
            )
            SELECT
                T.id,
                '2024-05-24 18:56:10',
                'Migration - 0004_change_workflow',
                '~',
                T.id,
                SYSTEM_USER.id,
                T.source_id,
                T.transition_id
            FROM
                vueda_workflow_transitionsource T,
                SYSTEM_USER
            WHERE
                T.transition_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_transition
                    WHERE
                        code = 'go_to_state_1_a'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                )
                AND
                T.source_id IN (
                    SELECT
                        id
                    FROM
                        vueda_workflow_state
                    WHERE
                        code = 'state_2'
                        AND workflow_id = (
                            SELECT
                                id
                            FROM
                                vueda_workflow_workflow
                            WHERE
                                code = 'changed_workflow_2'
                        )
                );""",
            reverse_sql=migrations.RunSQL.noop,
            skippable=True,
            skippable_env_variable=SKIPPABLE_ENV_VARIABLE,
        ),
    ]
