# Generated by Django 5.0.4 on 2024-05-31 22:05
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
import datetime

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.utils import timezone


history_change_reason = "Workflow Migration - 0005_workflow_migrations_2024_05_31"
keep_history_date = False
migration_app_label = "workflow_changed"
changed_data = [
    {
        "changes": {
            "code": ("changed_workflow", "changed_workflow_2"),
            "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            "historical_app_label": "workflow_changed",
            "historical_model": "workflowchanged",
            "id": {"code": "changed_workflow"},
            "name": ("Changed Workflow", "Changed Workflow 2"),
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 1, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "workflow",
    },
    {
        "changes": {
            "historical_permission_codename": "can_do_something",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": "can_do_something",
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "workflow_id": {"code": "changed_workflow_2"},
            },
            "permission_id": {
                "codename": "can_do_something",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "workflow_id": {"code": "changed_workflow_2"},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 2, tzinfo=datetime.timezone.utc),
        "history_type": "deleted",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "historical_permission_codename": ("can_do_something_else", "can_do_something"),
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": ("can_do_something_else", "can_do_something"),
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "workflow_id": {"code": "changed_workflow_2"},
            },
            "permission_id": (
                {
                    "codename": "can_do_something_else",
                    "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
                },
                {
                    "codename": "can_do_something",
                    "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
                },
            ),
            "workflow_id": {"code": "changed_workflow_2"},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 3, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "historical_permission_codename": "can_do_another_thing",
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "permission_id": {
                "codename": "can_do_another_thing",
                "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
            },
            "workflow_id": {"code": "changed_workflow_2"},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 4, tzinfo=datetime.timezone.utc),
        "history_type": "added",
        "model_name": "workflowpermission",
    },
    {
        "changes": {
            "id": {
                "state_id": (
                    {"code": "state_1", "workflow_id": {"code": "changed_workflow_2"}},
                    {"code": "state_2", "workflow_id": {"code": "changed_workflow_2"}},
                ),
                "workflow_id": {"code": "changed_workflow_2"},
            },
            "state_id": (
                {"code": "state_1", "workflow_id": {"code": "changed_workflow_2"}},
                {"code": "state_2", "workflow_id": {"code": "changed_workflow_2"}},
            ),
            "workflow_id": {"code": "changed_workflow_2"},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 5, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": ("state_1", "state_1_a"),
            "id": {"code": ("state_1", "state_1_a"), "workflow_id": {"code": "changed_workflow_2"}},
            "name": ("State 1", "State 1 A"),
            "workflow_id": {"code": "changed_workflow_2"},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 6, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "state",
    },
    {
        "changes": {
            "grant_or_deny": (False, True),
            "group_id": ({"name": "WorkflowChangedAdmin"}, {"name": "WorkflowChangedWorker"}),
            "historical_group_name": ("WorkflowChangedAdmin", "WorkflowChangedWorker"),
            "historical_permission_codename": ("can_do_something", "can_do_another_thing"),
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "group_id": ({"name": "WorkflowChangedAdmin"}, {"name": "WorkflowChangedWorker"}),
                "historical_group_name": ("WorkflowChangedAdmin", "WorkflowChangedWorker"),
                "historical_permission_codename": ("can_do_something", "can_do_another_thing"),
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "state_id": {"code": "state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
            },
            "permission_id": (
                {
                    "codename": "can_do_something",
                    "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
                },
                {
                    "codename": "can_do_another_thing",
                    "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
                },
            ),
            "state_id": {"code": "state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 7, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "statepermission",
    },
    {
        "changes": {
            "code": ("go_to_state_2", "go_to_state_1_a"),
            "id": {"code": ("go_to_state_2", "go_to_state_1_a"), "workflow_id": {"code": "changed_workflow_2"}},
            "name": ("Go To State 2", "Go To State 1 A"),
            "target_id": (
                {"code": "state_2", "workflow_id": {"code": "changed_workflow_2"}},
                {"code": "state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
            ),
            "workflow_id": {"code": "changed_workflow_2"},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 8, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "transition",
    },
    {
        "changes": {
            "historical_permission_codename": ("can_do_something", "can_do_another_thing"),
            "historical_permission_content_type_app_label": "workflow_changed",
            "historical_permission_content_type_model_name": "workflowchanged",
            "id": {
                "historical_permission_codename": ("can_do_something", "can_do_another_thing"),
                "historical_permission_content_type_app_label": "workflow_changed",
                "historical_permission_content_type_model_name": "workflowchanged",
                "transition_id": {"code": "go_to_state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
            },
            "permission_id": (
                {
                    "codename": "can_do_something",
                    "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
                },
                {
                    "codename": "can_do_another_thing",
                    "content_type_id": {"app_label": "workflow_changed", "model": "workflowchanged"},
                },
            ),
            "transition_id": {"code": "go_to_state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 9, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "transitionpermission",
    },
    {
        "changes": {
            "id": {
                "source_id": (
                    {"code": "state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
                    {"code": "state_2", "workflow_id": {"code": "changed_workflow_2"}},
                ),
                "transition_id": {"code": "go_to_state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
            },
            "source_id": (
                {"code": "state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
                {"code": "state_2", "workflow_id": {"code": "changed_workflow_2"}},
            ),
            "transition_id": {"code": "go_to_state_1_a", "workflow_id": {"code": "changed_workflow_2"}},
        },
        "history_date": datetime.datetime(2024, 5, 24, 18, 56, 10, tzinfo=datetime.timezone.utc),
        "history_type": "changed",
        "model_name": "transitionsource",
    },
]


def forwards_migrate_workflow(apps, schema_editor):
    for changed_item in changed_data:
        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item)

            case "state":
                handle_state(apps, changed_item)

            case "statepermission":
                handle_state_permission(apps, changed_item)

            case "initialstate":
                handle_initial_state(apps, changed_item)

            case "transition":
                handle_transition(apps, changed_item)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item)

            case "transitionsource":
                handle_transition_source(apps, changed_item)


def backwards_migrate_workflow(apps, schema_editor):
    for changed_item in reversed(changed_data):
        match changed_item["model_name"]:
            case "workflow":
                handle_workflow(apps, changed_item, reversing=True)

            case "workflowpermission":
                handle_workflow_permission(apps, changed_item, reversing=True)

            case "state":
                handle_state(apps, changed_item, reversing=True)

            case "statepermission":
                handle_state_permission(apps, changed_item, reversing=True)

            case "initialstate":
                handle_initial_state(apps, changed_item, reversing=True)

            case "transition":
                handle_transition(apps, changed_item, reversing=True)

            case "transitionpermission":
                handle_transition_permission(apps, changed_item, reversing=True)

            case "transitionsource":
                handle_transition_source(apps, changed_item, reversing=True)


def handle_workflow(apps, changed_item, *, reversing=False):
    historical_workflow = apps.get_model("workflow", "HistoricalWorkflow")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            workflow = model_workflow.objects.create(**data)

            add_history_to_data(
                data,
                workflow,
                "+",
                changed_item["history_date"],
            )
            historical_workflow.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"])

            del data["id"]

            # The changed workflow fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(workflow, key, old_value)

                else:
                    setattr(workflow, key, new_value)

            workflow.save()

            add_history_to_data(
                data,
                workflow,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "content_type_id",
                    "historical_app_label",
                    "historical_model",
                    "name",
                ),
            )
            historical_workflow.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["content_type_id"])
            data["content_type_id"] = content_type.pk

            workflow = model_workflow.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow, "-", changed_item["history_date"])
            historical_workflow.objects.create(**data)
            workflow.delete()


def handle_workflow_permission(apps, changed_item, *, reversing=False):
    historical_workflow_permission = apps.get_model("workflow", "HistoricalWorkflowPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_workflow = apps.get_model("workflow", "Workflow")
    model_workflow_permission = apps.get_model("workflow", "WorkflowPermission")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.create(**data)

            add_history_to_data(data, workflow_permission, "+", changed_item["history_date"])
            historical_workflow_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            new_permission_ids = []
            for permission_id in data["permission_id"]:
                content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                permission_id["content_type_id"] = content_type.pk
                permission = model_permission.objects.get(**permission_id)
                new_permission_ids.append(permission.pk)
            data["permission_id"] = tuple(new_permission_ids)

            # The changed historical permission fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(workflow_permission, key, old_value)

                else:
                    setattr(workflow_permission, key, new_value)

            workflow_permission.save()

            add_history_to_data(
                data,
                workflow_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "workflow_id",
                ),
            )
            historical_workflow_permission.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            workflow_permission = model_workflow_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, workflow_permission, "-", changed_item["history_date"])
            historical_workflow_permission.objects.create(**data)
            workflow_permission.delete()


def handle_state(apps, changed_item, *, reversing=False):
    historical_state = apps.get_model("workflow", "HistoricalState")
    model_state = apps.get_model("workflow", "State")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk

            state = model_state.objects.create(**data)

            add_history_to_data(data, state, "+", changed_item["history_date"])
            historical_state.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # The changed fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(state, key, old_value)

                else:
                    setattr(state, key, new_value)

            state.save()

            add_history_to_data(
                data,
                state,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "name",
                    "workflow_id",
                ),
            )
            historical_state.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            state = model_state.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state, "-", changed_item["history_date"])
            historical_state.objects.create(**data)
            state.delete()


def handle_state_permission(apps, changed_item, *, reversing=False):
    historical_state_permission = apps.get_model("workflow", "HistoricalStatePermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_group = apps.get_model("auth", "Group")
    model_permission = apps.get_model("auth", "Permission")
    model_state = apps.get_model("workflow", "State")
    model_state_permission = apps.get_model("workflow", "StatePermission")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["group_id"])
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.create(**data)

            add_history_to_data(data, state_permission, "+", changed_item["history_date"])
            historical_state_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            group = model_group.objects.get(**get_id_values_from_item(data["id"]["group_id"], reversing=reversing))
            data["id"]["group_id"] = group.pk
            state_permission = model_state_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            new_permission_ids = []
            for permission_id in data["permission_id"]:
                content_type = model_content_type.objects.get(**permission_id["content_type_id"])
                permission_id["content_type_id"] = content_type.pk
                permission = model_permission.objects.get(**permission_id)
                new_permission_ids.append(permission.pk)
            data["permission_id"] = tuple(new_permission_ids)

            new_group_ids = []
            for group_id in data["group_id"]:
                group = model_group.objects.get(**group_id)
                new_group_ids.append(group.pk)
            data["group_id"] = tuple(new_group_ids)

            # The changed fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(state_permission, key, old_value)

                else:
                    setattr(state_permission, key, new_value)

            state_permission.save()

            add_history_to_data(
                data,
                state_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "grant_or_deny",
                    "group_id",
                    "historical_group_name",
                    "historical_permission_codename",
                    "permission_id",
                    "state_id",
                ),
            )
            historical_state_permission.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            group = model_group.objects.get(**data["id"]["group_id"])
            data["id"]["group_id"] = group.pk
            data["group_id"] = group.pk

            state_permission = model_state_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, state_permission, "-", changed_item["history_date"])
            historical_state_permission.objects.create(**data)
            state_permission.delete()


def handle_initial_state(apps, changed_item, *, reversing=False):
    historical_initial_state = apps.get_model("workflow", "HistoricalInitialState")
    model_initial_state = apps.get_model("workflow", "InitialState")
    model_state = apps.get_model("workflow", "State")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["state_id"]["workflow_id"])
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["state_id"])

            data["state_id"] = state.pk
            data["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.create(**data)

            add_history_to_data(data, initial_state, "+", changed_item["history_date"])
            historical_initial_state.objects.create(**data)

        case "changed":
            data["id"]["state_id"] = get_id_values_from_item(data["id"]["state_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            # The state is the only thing that can change, so we
            # can use what exists above, since it is the same data.
            initial_state.state_id = state.pk
            initial_state.save()

            add_history_to_data(
                data,
                initial_state,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "state_id",
                    "workflow_id",
                ),
            )
            historical_initial_state.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["state_id"]["workflow_id"])
            data["id"]["state_id"]["workflow_id"] = workflow.pk
            data["state_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["state_id"])
            data["id"]["state_id"] = state.pk
            data["state_id"] = state.pk
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk

            initial_state = model_initial_state.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            add_history_to_data(data, initial_state, "-", changed_item["history_date"])
            historical_initial_state.objects.create(**data)
            initial_state.delete()


def handle_transition(apps, changed_item, *, reversing=False):
    historical_transition = apps.get_model("workflow", "HistoricalTransition")
    model_state = apps.get_model("workflow", "State")
    model_transition = apps.get_model("workflow", "Transition")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.create(**data)

            add_history_to_data(data, transition, "+", changed_item["history_date"])
            historical_transition.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**get_id_values_from_dict(data["id"], reversing=reversing))

            del data["id"]

            workflow = model_workflow.objects.get(**data["workflow_id"])
            data["workflow_id"] = workflow.pk
            data["target_id"] = get_id_values_from_item(data["target_id"], reversing=reversing)
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            # The changed fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(transition, key, old_value)

                else:
                    setattr(transition, key, new_value)

            transition.save()

            add_history_to_data(
                data,
                transition,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "code",
                    "name",
                    "target_id",
                    "workflow_id",
                ),
            )
            historical_transition.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["workflow_id"])
            data["id"]["workflow_id"] = workflow.pk
            data["workflow_id"] = workflow.pk
            data["target_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["target_id"])
            data["target_id"] = state.pk

            transition = model_transition.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition, "-", changed_item["history_date"])
            historical_transition.objects.create(**data)
            transition.delete()


def handle_transition_permission(apps, changed_item, *, reversing=False):
    historical_transition_permission = apps.get_model("workflow", "HistoricalTransitionPermission")
    model_content_type = apps.get_model("contenttypes", "ContentType")
    model_permission = apps.get_model("auth", "Permission")
    model_transition = apps.get_model("workflow", "Transition")
    model_transition_permission = apps.get_model("workflow", "TransitionPermission")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.create(**data)

            add_history_to_data(data, transition_permission, "+", changed_item["history_date"])
            historical_transition_permission.objects.create(**data)

        case "changed":
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk

            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk
            data["permission_id"] = get_id_values_from_item(data["permission_id"], reversing=reversing)
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk

            # The changed historical permission fields have a tuple with 2 values, the other fields do not.
            # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
            for key, values in data.items():
                if type(values) is not tuple:
                    continue

                old_value, new_value = values

                if reversing:
                    setattr(transition, key, old_value)

                else:
                    setattr(transition, key, new_value)

            transition_permission.save()

            add_history_to_data(
                data,
                transition_permission,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "historical_permission_codename",
                    "historical_permission_content_type_app_label",
                    "historical_permission_content_type_model_name",
                    "permission_id",
                    "transition_id",
                ),
            )
            historical_transition_permission.objects.create(**data)

        case "deleted":
            content_type = model_content_type.objects.get(**data["permission_id"]["content_type_id"])
            data["permission_id"]["content_type_id"] = content_type.pk
            permission = model_permission.objects.get(**data["permission_id"])
            data["permission_id"] = permission.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_permission = model_transition_permission.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_permission, "-", changed_item["history_date"])
            historical_transition_permission.objects.create(**data)
            transition_permission.delete()


def handle_transition_source(apps, changed_item, *, reversing=False):
    historical_transition_source = apps.get_model("workflow", "HistoricalTransitionSource")
    model_state = apps.get_model("workflow", "State")
    model_transition = apps.get_model("workflow", "Transition")
    model_transition_source = apps.get_model("workflow", "TransitionSource")
    model_workflow = apps.get_model("workflow", "Workflow")

    data = changed_item["changes"]

    match changed_item["history_type"]:
        case "added":
            workflow = model_workflow.objects.get(**data["source_id"]["workflow_id"])
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["source_id"])
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["transition_id"]["workflow_id"])
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["transition_id"])
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.create(**data)

            add_history_to_data(data, transition_source, "+", changed_item["history_date"])
            historical_transition_source.objects.create(**data)

        case "changed":
            data["id"]["source_id"] = get_id_values_from_item(data["id"]["source_id"], reversing=reversing)
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk

            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(
                **get_id_values_from_dict(data["id"], reversing=reversing)
            )

            del data["id"]

            # The source is the only thing that can change, so we
            # can use what exists above, since it is the same data.
            transition_source.source_id = state.pk
            transition_source.save()

            add_history_to_data(
                data,
                transition_source,
                "~",
                changed_item["history_date"],
                fields=(
                    "id",
                    "source_id",
                    "transition_id",
                ),
            )
            historical_transition_source.objects.create(**data)

        case "deleted":
            workflow = model_workflow.objects.get(**data["id"]["source_id"]["workflow_id"])
            data["id"]["source_id"]["workflow_id"] = workflow.pk
            data["source_id"]["workflow_id"] = workflow.pk
            state = model_state.objects.get(**data["id"]["source_id"])
            data["id"]["source_id"] = state.pk
            data["source_id"] = state.pk
            workflow = model_workflow.objects.get(**data["id"]["transition_id"]["workflow_id"])
            data["id"]["transition_id"]["workflow_id"] = workflow.pk
            data["transition_id"]["workflow_id"] = workflow.pk
            transition = model_transition.objects.get(**data["id"]["transition_id"])
            data["id"]["transition_id"] = transition.pk
            data["transition_id"] = transition.pk

            transition_source = model_transition_source.objects.get(**data["id"])

            del data["id"]

            add_history_to_data(data, transition_source, "-", changed_item["history_date"])
            historical_transition_source.objects.create(**data)
            transition_source.delete()


def add_history_to_data(history_data, obj, history_type, history_date, fields=()):
    # For changed history
    for field_name in fields:
        history_data[field_name] = getattr(obj, field_name)

    # For all history
    history_data["history_change_reason"] = history_change_reason
    history_data["history_date"] = history_date if keep_history_date else timezone.now()
    history_data["history_relation_id"] = obj.pk
    history_data["history_type"] = history_type
    history_data["id"] = obj.pk


def get_id_values_from_item(values, reversing=False):
    # The changed fields have a tuple with 2 values, the other fields do not.
    # Testing as tuple instead of length, because values could be a dictionary with 2 keys, or a 2 character string.  A single value can't be a tuple.
    if type(values) is tuple:
        return values[1 if reversing else 0]

    return values


def get_id_values_from_dict(id_data, reversing=False):
    results = {}
    for field_name, values in id_data.items():
        results[field_name] = get_id_values_from_item(values)

    return results


def make_sure_permissions_exist(apps, schema_editor):
    app = django_apps.get_app_config(migration_app_label)
    create_permissions(app, interactive=False)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_changed", "0004_change_workflow"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow,
            reverse_code=backwards_migrate_workflow,
        ),
    ]
