# Generated by Django 5.2.15 on 2026-01-05 10:15
# Modified using VUEDA makeworkflowmigrations command.  Please do not delete this comment.
# Never modify this migration.  It stands in for work authored on another machine, so the test can
# apply it rather than fake it.
import copy
import datetime

from django.conf import settings
from django.db import migrations

from vueda.workflow.management.commands.makeworkflowmigrations import backwards_migrate_workflow
from vueda.workflow.management.commands.makeworkflowmigrations import forwards_migrate_workflow
from vueda.workflow.management.commands.makeworkflowmigrations import make_sure_permissions_exist


history_change_reason = "Workflow Migration - 0002_workflow_migrations_2026_01_05"
migration_app_label = "workflow_received_codes"
changed_data = [
    {
        "changes": {
            "code": "received_codes_workflow",
            "content_type_id": {"app_label": "workflow_received_codes", "model": "workflowreceivedcodes"},
            "historical_app_label": "workflow_received_codes",
            "historical_model": "workflowreceivedcodes",
            "id": {"code": "received_codes_workflow"},
            "name": "Received Codes Workflow",
        },
        "history_date": datetime.datetime(2026, 1, 5, 10, 10, 1, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "workflow",
    },
    {
        "changes": {
            "code": "state_1",
            "id": {"code": "state_1", "workflow_id": {"code": "received_codes_workflow"}},
            "name": "State 1",
            "workflow_id": {"code": "received_codes_workflow"},
        },
        "history_date": datetime.datetime(2026, 1, 5, 10, 10, 2, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "id": {
                "state_id": {"code": "state_1", "workflow_id": {"code": "received_codes_workflow"}},
                "workflow_id": {"code": "received_codes_workflow"},
            },
            "state_id": {"code": "state_1", "workflow_id": {"code": "received_codes_workflow"}},
            "workflow_id": {"code": "received_codes_workflow"},
        },
        "history_date": datetime.datetime(2026, 1, 5, 10, 10, 3, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "initialstate",
    },
    {
        "changes": {
            "code": "shared_code",
            "id": {"code": "shared_code", "workflow_id": {"code": "received_codes_workflow"}},
            "name": "Shared Code",
            "workflow_id": {"code": "received_codes_workflow"},
        },
        "history_date": datetime.datetime(2026, 1, 5, 10, 10, 4, tzinfo=datetime.UTC),
        "history_type": "added",
        "model_name": "state",
    },
    {
        "changes": {
            "code": "shared_code",
            "id": {"code": "shared_code", "workflow_id": {"code": "received_codes_workflow"}},
            "name": "Shared Code",
            "workflow_id": {"code": "received_codes_workflow"},
        },
        "history_date": datetime.datetime(2026, 1, 5, 10, 10, 5, tzinfo=datetime.UTC),
        "history_type": "deleted",
        "model_name": "state",
    },
]


def forwards_migrate_workflow_through_imports(apps, schema_editor):
    # Copied changed_data, so tests can migrate forwards and backwards.
    forwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def backwards_migrate_workflow_through_imports(apps, schema_editor):
    # Copied changed_data, so tests can migrate forwards and backwards.
    backwards_migrate_workflow(apps, copy.deepcopy(changed_data), history_change_reason)


def make_sure_permissions_exist_through_imports(apps, schema_editor):
    make_sure_permissions_exist(migration_app_label)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vueda_workflow", "__latest__"),
        ("workflow_received_codes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=make_sure_permissions_exist_through_imports,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=forwards_migrate_workflow_through_imports,
            reverse_code=backwards_migrate_workflow_through_imports,
        ),
    ]
