import os

from django.db.migrations import RunSQL


# While creating tests, I discovered that if you modify the operations on a migration
# if an environment variable exists, and then want to run the migration without modified
# operations, you can't.  So, the best place to skip doing a migration is within the
# code, so the operation still exists and is run.  So this class exists as a way to skip
# all or specific migrations when testing, so we can verify that the workflow migrations
# generated by the makeworkflowmigrations management command actually work.


class SkippableRunSQL(RunSQL):
    def __init__(
        self,
        *args,
        skippable=False,
        skippable_env_variable="migration_skip",
        skip_all_env_variable="skip_migration_when_setting_up_db",
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.skippable = skippable
        self.skippable_env_variable = skippable_env_variable
        self.skip_all_env_variable = skip_all_env_variable

    def _run_sql(self, *args, **kwargs):
        skip_all = os.environ.get(self.skip_all_env_variable, "").lower() == "true"
        skip = self.skippable and os.environ.get(self.skippable_env_variable, "").lower() == "true"

        if skip_all:
            return

        if not skip:
            super()._run_sql(*args, **kwargs)
