import os

from django.db import migrations


# While creating tests, I discovered that if you modify the operations on a migration
# if an environment variable exists, and then want to run the migration without modified
# operations, you can't.  So, the best place to skip doing a migration is within the
# code, so the operation still exists and is run.  So this class exists as a way to skip
# all or specific migrations when testing, so we can verify that the workflow migrations
# generated by the makeworkflowmigrations management command actually work.


class SkippableRunSQL(migrations.RunSQL):
    def __init__(
        self,
        *args,
        skippable=False,
        skippable_env_variable="migration_skip",
        skip_all_env_variable="skip_migration_when_setting_up_db",
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.skippable = skippable
        self.skippable_env_variable = skippable_env_variable
        self.skip_all_env_variable = skip_all_env_variable

    def _run_sql(self, *args, **kwargs):
        skip_all = os.environ.get(self.skip_all_env_variable, "").lower() == "true"
        skip = self.skippable and os.environ.get(self.skippable_env_variable, "").lower() == "true"

        if skip_all:
            return

        if not skip:
            super()._run_sql(*args, **kwargs)


def clean_migrations(which_app=None):
    workflow_added_migrations_data = {
        "tests/workflow_added/migrations": ("__init__.py", "0001_initial.py", "0002_create_workflow_added_workflow.py"),
    }
    workflow_changed_migrations_data = {
        "tests/workflow_changed/migrations": (
            "__init__.py",
            "0001_initial.py",
            "0002_create_workflow_changed_permissions.py",
            "0003_workflow_migrations_2024_05_14.py",
            "0004_change_workflow.py",
        ),
    }
    workflow_deleted_migrations_data = {
        "tests/workflow_deleted/migrations": (
            "__init__.py",
            "0001_initial.py",
            "0002_create_workflow_deleted_permissions.py",
            "0003_workflow_migrations_2024_05_13.py",
            "0004_delete_workflow.py",
        ),
    }
    match which_app:
        case "workflow_added":
            existing_migration_data = workflow_added_migrations_data

        case "workflow_changed":
            existing_migration_data = workflow_changed_migrations_data

        case "workflow_deleted":
            existing_migration_data = workflow_deleted_migrations_data

        case _:
            existing_migration_data = {}
            existing_migration_data.update(workflow_added_migrations_data)
            existing_migration_data.update(workflow_changed_migrations_data)
            existing_migration_data.update(workflow_deleted_migrations_data)

    for path, existing_migrations in existing_migration_data.items():
        for root, _dirs, files in os.walk(path):
            for filename in files:
                if filename not in existing_migrations:
                    os.remove(os.path.join(root, filename))
